### ISSUE TITLE
HA-Error: Integration of the vaillant-component in home assistent

### ISSUE THREAD

**Issue by ThoEngel** [thomasgermain/vaillant-component#1]
**Environment**: 
Home Assistant 0.96.5
Vaillant-component  0.96

I copied the vaillant-component files to my home-assistant (raspberry pi: /config/custom_components/vaillant). 
The Configuration /config/configuration.yaml:
```
vaillant:
  username: "myemail"
  password: "mypassword"
```
After restart of HA i get the following HA-error:
```
Setup failed for vaillant: No setup function defined.
13:37 setup.py (ERROR)
```
What is going wrong?

**Comment by thomasgermain** [comment]
Hmm strange,
You're doing all good.

I just pushed the last modification I did. Could you retry are you using these files ? https://github.com/thomasgermain/home-assistant/tree/vaillant/homeassistant/components/vaillant

**Comment by ThoEngel** [comment]
yes, it works with the new version.

**Comment by thomasgermain** [comment]
Great, please let me know if there is any problem
