### ISSUE TITLE
Getting 0 zones 

### ISSUE THREAD

**Issue by JanGillis** [thomasgermain/vaillant-component#102]
Versions:
Multimatic app V 3.7.453
Home Assistant 2021.10.6
Multimatic integration: v1.10.0

Getting following error

> Logger: homeassistant.components.climate
> Source: custom_components/multimatic/climate.py:86
> Integration: Climate (documentation, issues)
> First occurred: 17:17:31 (1 occurrences)
> Last logged: 17:17:31
> 
> Error while setting up multimatic platform for climate
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
>     await asyncio.shield(task)
>   File "/config/custom_components/multimatic/climate.py", line 86, in async_setup_entry
>     rbr_zone = [zone for zone in zones_coo.data if zone.rbr][0]
> IndexError: list index out of range
> 

Because of 0 zones 

> 2021-10-23 17:17:31 INFO (MainThread) [custom_components.multimatic.climate] Adding 0 zones
> 2021-10-23 17:17:31 INFO (MainThread) [custom_components.multimatic.climate] Adding 10 rooms

All info of rooms seems available and system is working through multimatic app

> 2021-10-23 17:20:09 INFO (MainThread) [custom_components.multimatic.climate] Info rooms [Room(time_program=TimeProgram(days={'monday': TimeProgramDay(settings=[TimePeriodSetting(start_time='00:00', target_temperature=17.0, setting=None, hour=0, minute=0, ........

Can you please take a look what could be causing this?

**Comment by javiergarcia** [comment]
Hello,

I have the following setup:

Versions:
Multimatic app V 3.8.9
Home Assistant 2021.12.3
Multimatic integration: v1.11.0
Model IsoFast H-Condens MA 36, SRT 380F

Most of the sensors are detected in Home-assistant but no climate entity is detected. Multimatic apps detects one zone but not HA.

Any crue?

Best

**Comment by thomasgermain** [comment]
Hello, 

I think this is the same problem as above. Actually the mutimatic app including some functionalities of senso app. 
The integration is only compatible with "pure" multimatic API

**Comment by adokitkat** [comment]
Hi, 

I have encountered a similar problem.  I had an old version of this component (when it called only "vaillant") and I updated to the latest version via HACS. Before when the old component was functional zones were registered and I could create thermostat UI elements.

 After install at first there were no zones. Then after several minutes Zone 2 appeared (unused in my house - I have only 2 zones and Zone 1 is used) but Zone 1 is still not there. IDK why it suddenly appeared in entities. Only thing I did was checking my Vaillant app on a phone, I changed nothin in my Home Assistant. 
 
 Everything should be updated to the latest version.

**Comment by thomasgermain** [comment]
This is a quite common error, sometimes the API is not returning some mandatory information (here is the mode the zone is running, AUTO, ON, etc;). It happens often after an update. It happened to me yesterday. My system updated at 3am and until 8pm the API was returning wrong data, even the mobile app was unuseable
