### ISSUE TITLE
Easier upgrade procedure?

### ISSUE THREAD

**Issue by johanvh83** [thomasgermain/vaillant-component#104]
Hello Thomas,

Using your integration since about 2 years and works without any problem. My congratz!
I just upgraded from V1.7.0 to the new version V1.10.1.
This is the way I did it:
1/ removed the Multimatic integration from the configuration - integration page.
2/ had a look in my files and the folder 'multimatic' under 'custom integration' was still there. I renamed it.
3/ Installed Multimatic integration V1.10.1 with HACS and restarted
4/ The custom integrations folder had again a subfolder 'multimatic'
5/ Installed the integration in HA (had to enter again the login, password and S/N)

Above procedure worked and the multimatic integration is up and running and updated but I'm curious if there is an easier way.

P.S. I have 3 thermostats which gives also the humidity. This is not imported in HA. Would it be a big job to do it?

**Comment by thomasgermain** [comment]
Hello,

SInce 1.5.0 version, you don't have to do such things, you can directly update through HACS without deleting folder etc.


About your thermostat, are they VR51 ? If yes, it's already supported: this is a attribute of climate.
Otherwise, if the humidity value is available in the mobile app, I can certainly integrate it

**Comment by johanvh83** [comment]
Hi,
Thanks for your prompt reply.
I installed 1.7.0 manually so I couldn't use HACS to upgrade. I believe I will be informed by HACS now, if you make an update and can manage it from HACS.

Yes, I have 3 pcs VR51. I checked all attributes and indeed the humidity is listed, I didn't know.
It seems the default climate lovelace card doesn't display the humidity.

What do you mean with 'if the humidity value is available in the mobile app, I can certainly integrate it'

**Comment by thomasgermain** [comment]
> What do you mean with 'if the humidity value is available in the mobile app, I can certainly integrate it'

There is some information that can be displayed by the boiler/water heater/VRCXX that are not displayed inside the mobile app. I often have request to integrate such stuff, but since it's not available in the mobile app, I can't get them.
