### ISSUE TITLE
dhw_circulation binary sensor problem

### ISSUE THREAD

**Issue by kalatos86** [thomasgermain/vaillant-component#107]
Dear Community, 

I am using multimatic 1.11.0 withe the HomeAssistant. My devices are VR720 controller together with VR920 which is allows internet connection. I noticed that binary sensor dhw_circulation is changing between on / off according to schedule set in the Vaillant controller which is good but does not change the state to off when I manually disable heating the water on the controller or mobile app binary sensor does not react. Problem is that I have automation to correlate this binary sensor with external electric heater.

Thanks in advance,
Lukasz

**Comment by thomasgermain** [comment]
Hello,

as far as I know, circulation and hot water are two independent component. So you can turn them on/off independently.

According to the doc here: https://elearning.vaillant.com/vrc700/ci/en/documents/uk/infopool/Operating_instructions.pdf, point 5.3.3 (page 14), if hot water is turned off, it doesn't seem to turn circulation off.

```
5.3.3 Operating modes for hot water generation
5.3.3.1 Automatic mode
Operating mode → Domestic hot water → Auto
– The Auto operating mode controls the hot water generation in accordance with the desired temperature set for
DHW circuit and the time periods set.
Within the time period, hot water generation is switched on
and maintains the hot water in the domestic hot water cylinder at the preset temperature. Outside the time period, hot
water generation is switched off.
5.3.3.2 Comfort mode
Operating mode → Domestic hot water → Day
– The Day operating mode controls the hot water generation in accordance with the desired temperature set for
DHW circuit, without taking the time periods into consideration.
5.3.3.3 Off
Operating mode → Domestic hot water → Off
– Hot water generation is switched off and the Frost protection function is active.
5.3.4 Operating modes for circulation
The operating mode for the circulation always corresponds
to the operating mode for the hot water generation. You cannot set a different operating mode.
```

**Comment by kalatos86** [comment]
Thank you for that. Nevertheless I wrote the mail to the local Vaillant support and they confirmed my assumption. I have check also behavior of the physical devices and the fact is that when I manually turn off water heating the circulation pump has also stopped working. The issue is that binary_sensor.dhw_circulation remains on. As this is binary sensor in HA I can only see the status. IS there any way to change the value of binary_sensor.dhw_circulation ex by the service? 
If not then the question why the status of binary_sensor.dhw_circulation remains on while controller switching of the physical circulation pump?

**Comment by thomasgermain** [comment]
Does circulation is off on the application ? Actually, I can only rely on what the API gives me.

**Comment by kalatos86** [comment]
What I understood from the Vaillant support is that when heating water is disabled from the mobile application or right from the wall controller then the water circulation pump is also physically switched off and thus working well. Nevertheless this is not visible in the mobile app meaning the schedule for circulation pump is still visible but as long as the water heating is turned off the controller bypasses the schedule and does not turn on the pump. Questions here if the integration somehow trigger this change and set dhw_circulation binary sensor accordingly.

**Comment by thomasgermain** [comment]
Yep understand your point, but the integration (and the underlying connector to the vaillant API) only rely on what API is returning. There is no way to know from the API that the device is physically turned off.

**Comment by kalatos86** [comment]
This is interesting as the device (pump) is managed by VR700 controller. This means that such information should be somewhere in the Vaillant API.

**Comment by thomasgermain** [comment]
If you know where, I would be happy to integrate it, but I never found such things.
There are a lot of info in the VRC700 (heating curve, min/max temp of the circuit, etc) which are not in the API :/

**Comment by VaillantHassIo** [comment]
@kalatos86 does it never switch off? I can replicate the issue by manually start hotwater boost. even without cancellation the circulation sensor remains in state "on". i can only assume that the API is not being queried again for this state 

@thomasgermain is there an intervall pollig circulation or only during certain actions/state changes?

**Comment by thomasgermain** [comment]
By default the integration is polling the API every 2min

**Comment by VaillantHassIo** [comment]
@kalatos86 when my HeatPump produces HotWater it doesn't enable the Circulation. (Neither App nor HA) So i will need to check, if Quick Boost enabled\disables the Cirucaltion nad if this mirrors into HA as per thomas

**Comment by kalatos86** [comment]
Dear Colleges first of all thanks for active support you are trying to give.

My observation is following:
- normally  dhw_circulation entity is switching between on/off well according to the schedule set in Vaillant controller 
- also while using service QM_HOTWATER_BOOST through HA state of dhw_circulation is set in the proper way meaning if QM_HOTWATER_BOOST is switched on then  dhw_circulation is also on. When I manually would like to switch off QM_HOTWATER_BOOST using RemoveQuickMode then dhw_circulation is also switched off
- problem occurring when I'd like to switch off heating water by switching it of from the mobile app or right from the controller. IT seems that Vaillant controller switched off physical circulation pump but dhw_circulation still switch between on/off according to the Vaillant schedule - and here is the issue.

Hope I described it in the way you will understood it :)

BR,
Lukasz

**Comment by thomasgermain** [comment]
> It seems that Vaillant controller switched off physical circulation pump and that's the desired action but dhw_circulation still switch between on/off according to the Vaillant schedule - and here is the issue. 

Are you talking about the binary_sensor ? Or the mobile app ? (Or both ?)

I did some tests: I have hot water, but no circulation. I can set a schedule for my hot water AND circulation. 

First test: set hot water off (either off or not on schedule) and scheduled circulation ON, here is the result:
Circulation is ON ("marche" means on) while hot water is off.
![Screenshot_20220107-193602_multiMATIC](https://user-images.githubusercontent.com/12560542/148591335-27620436-bb94-4aaa-9f8e-0a4f07c993be.png)

Second test: Hot water on (either on or on shcedule) and scheduled circulation OFF:
circulation is still off ("arrêt" means off) while hot water is on
![Screenshot_20220107-193647_multiMATIC](https://user-images.githubusercontent.com/12560542/148591195-3be94d50-965d-45ec-b0d9-31a7b4cac8f9.png)


I also tested with HOT WATER BOOST quick mode and both hot water and circulation are ON.

Normally, the circulation binary sensor should have the same behavior.

Maybe the behavior is different if you have circulation ? But as far as I know, there is no way to know if circulation is available or not, as far as there is at least hot water, everything is available at API side.

**Comment by kalatos86** [comment]
Well I am speaking about binary sensor ant it's status in HomeAssistant. I don't have option to operate circulation expect to schedule the time. I cannot say manually switch it off because there is no such option.

So If the hot water option is auto then circulation is working according the the it's schedule.

If I manually run the profile of boost water and the circulation is out of the schedule it will switch on. I i will remove boost hot water then circulation will switch off.

Whats the problem here why binary sensor in HA switching according to the schedule even if I changed hot water to off? This is the problem. Here the VR700 physically switch off the circulation pump but as I have some automation based on dwh_circulation like steering electric heater it becomes tricky why it behaves like that. 

![obraz](https://user-images.githubusercontent.com/75856476/148703576-0beaed5a-25be-4d69-bf17-e850844f8c58.png)

**Comment by VaillantHassIo** [comment]
so basically you are saying, when Quick Boost is enabled and Circulation is turned on and overlapps the automatic time shedule for circulation it will turn cirucaltion off, even though the sheduled time setting is running? 

Does this happen with HA only? Let say,you run quick boost on VaillantMultimatic App in the same scenario, will it turn off circulation when quick boost finishes?

**Comment by thomasgermain** [comment]
> so basically you are saying, when Quick Boost is enabled and Circulation is turned on and overlapps the automatic time shedule for circulation it will turn cirucaltion off, even though the sheduled time setting is running?

Nope, hot water boost quick mode set circulation ON (whatever the schedule is). When switching hot water boost off, the circulation (as well as hot water) switch back to their schedule.

@kalatos86 what does "ZALACZ" means ? 
Did you try to turn your hot water ON (not the hot water boost) while the schedule of the circulation is off ? What does it do ? (in the mobile app).
-> When I'm doing that, my hot water is ON, but my circulation remains off.

Do you have any error in the integration ?

**Comment by kalatos86** [comment]
> so basically you are saying, when Quick Boost is enabled and Circulation is turned on and overlapps the automatic time shedule for circulation it will turn cirucaltion off, even though the sheduled time setting is running?
> 
> Does this happen with HA only? Let say,you run quick boost on VaillantMultimatic App in the same scenario, will it turn off circulation when quick boost finishes?

It is working as the @thomasgermain wrote.




> > so basically you are saying, when Quick Boost is enabled and Circulation is turned on and overlapps the automatic time shedule for circulation it will turn cirucaltion off, even though the sheduled time setting is running?
> 
> Nope, hot water boost quick mode set circulation ON (whatever the schedule is). When switching hot water boost off, the circulation (as well as hot water) switch back to their schedule.
> 
> @kalatos86 what does "ZALACZ" means ? Did you try to turn your hot water ON (not the hot water boost) while the schedule of the circulation is off ? What does it do ? (in the mobile app). -> When I'm doing that, my hot water is ON, but my circulation remains off.

For me this works the same. But still why when the hot water is OFF and physical circulation pump is not running dwh_circulation parameter is changing according to it's schedule

> 
> Do you have any error in the integration ?

In the main logs I have only information about custom integration which is normal. Where to find details multimatic logs?

**Comment by prezesBB** [comment]
if we cannot turn the circulation on manually, can we create an entity containing the circulation schedule? If necessary (with a script / button), reset the schedule to turn off the circulation (manually) and set it again (automatically) to turn it on. I mean controlling the circulation independently of water heating. 
I asked vaillant technical support and from the APP level, it is not possible to control the circulation outside the schedule. The ON / OFF / AUTO function is missing as in the other functionalities.

**Comment by kalatos86** [comment]
I wondering why this is missing from Vaillant :)

**Comment by thomasgermain** [comment]
> if we cannot turn the circulation on manually, can we create an entity containing the circulation schedule? If necessary (with a script / button), reset the schedule to turn off the circulation (manually) and set it again (automatically) to turn it on. I mean controlling the circulation independently of water heating. I asked vaillant technical support and from the APP level, it is not possible to control the circulation outside the schedule. The ON / OFF / AUTO function is missing as in the other functionalities.

You can have a look here https://github.com/thomasgermain/pymultiMATIC/ (this is the underlying connector the integration is using to get data). Using the `Connector`, you can basically do whatever requests you want. You could have 2 requests, one to set the schedule always ON and another one the set it always OFF
