### ISSUE TITLE
Don't appears the sensor for outdoor temperature

### ISSUE THREAD

**Issue by ZancaAngelo** [thomasgermain/vaillant-component#113]
I have installed the component, from the logs, I have no error, but the external temperature sensor is not displayed. The other entities are correctly read.

What can I do?

Version H.A 2021.12.10
Component 1.12.21

![Immagine 2022-01-24 153243](https://user-images.githubusercontent.com/50366331/150802403-87125070-de27-4e66-bc59-ac20909708f3.png)
![Immagine 2022-01-24 153209](https://user-images.githubusercontent.com/50366331/150802422-014ab2c1-a199-4d26-be53-85444d6e3c04.png)

**Comment by thomasgermain** [comment]
Hello,

This is a bit strange, but senso is not fully supported, the API is almost -but not exactly- the same as multimatic API.

Could you check here: https://github.com/thomasgermain/pymultiMATIC/tree/master/script
1) get `print_response.ps1` (for windows) or `print_response.sh` for linux
2) open powershell (for windows) or terminal for linux
3) `./print_response.xx username password https://smart.vaillant.com/mobile/api/v4//facilities/{serial-number}/systemcontrol/v1/status`. Don't forget to put your serial number.

Could post the result ?

Normally, you should receive a response which looks like this:
```json
{
  "body": {
    "datetime": "2021-06-23T11:43:12.000Z",
    "outside_temperature": 12.5
  },
  "meta": {
    "resourceState": [
      {
        "state": "SYNCED",
        "timestamp": 1624441392223,
        "link": {
          "rel": "self",
          "resourceLink": "/facilities/xxx/systemcontrol/v1/status"
        }
      }
    ]
  }
}
```

Thanks !

**Comment by ZancaAngelo** [comment]
Dear Thomas,
thanks for the reply, i tried to follow your indications, but i couldn't get the script to work.
The pymultimatic module I downloaded and unzip in the following path:
    /home/pi/Downloads/pymultiMATIC/script

From the SSH terminal I placed myself in the path indicated above and I launched the following command:
    sh print_response.sh username password https://smart.vaillant.com/mobile/api/v4/facilities/2...........2/systemcontrol/v1/status

The answer obtained is the following:
    pi@raspberrypi:~/Downloads/pymultiMATIC/script $ print_response.sh: 18: jq: not found
    (23) Failed writing body
    {"errorCode":"INVALID_PARAMS"}curl: (3) URL using bad/illegal format or missing URL

Where am I doing wrong?

**Comment by ZancaAngelo** [comment]
I followed your advice to run the script from my pc, and for my convenience, I wrote the user and password and url values inside the script.
the result I got is the following
 
![Immagine 2022-02-04 101723](https://user-images.githubusercontent.com/50366331/152503535-5e732453-a0cd-43e5-af13-4ca05adb5be7.png)

**Comment by thomasgermain** [comment]
Thanks for the feedback.

This is what I thought it was, some part of your system is under the "senso" API (as I said, this is pretty much the same, but still, with some differences). It means your system is not fully compatible with the integration.

There is no plan to support senso (except somebody is submitting a PR), because myVaillant is being launched (or should be launched pretty soon) and It should unify all different APIs vaillant has.

I'm sorry for the inconvenience :/
