### ISSUE TITLE
Current fan speeds of hvac

### ISSUE THREAD

**Issue by sammy98** [thomasgermain/vaillant-component#114]
Hi

did i miss something or is the current fan speed from the hvac not exposed to home-assistant?
In the vaillant app is the current fan-speed shown - can that be seen home assistant too?

Current used version: 
integration 1.12.1
hass 2021.12.10

Edit: i remember that as i had used the ebus directly, there were only information about night- and day-level and the interval of  day-level.
I had to calculate the current level by mysel, but then i am missing the night / day levels and the interval probably

**Comment by thomasgermain** [comment]
Hello,

This is available at API side. I can add it as a state attribute of the fan:)

**Comment by sammy98** [comment]
That would be awesome!

**Comment by VaillantHassIo** [comment]
+1
