### ISSUE TITLE
Circulation on/off

### ISSUE THREAD

**Issue by nnarta** [thomasgermain/vaillant-component#115]
Hi! Is there any way to switch hot water circulation on/off? I can't find such device.

**Comment by thomasgermain** [comment]
Hello,

There is no such functionality at API level. Basically, if you cannot do it through the mobile app, you won't be able to do it through the integration.

You can have a look here for some background: https://github.com/thomasgermain/vaillant-component/issues/94 and https://github.com/thomasgermain/vaillant-component/issues/107
