### ISSUE TITLE
Turns on UNAVAILABLE

### ISSUE THREAD

**Issue by MisfitPunisher** [thomasgermain/vaillant-component#119]
Hi friends,

sometimes all the devices and entities of my Vaillant equipment became unavailable. I have to reload the integration to resolve the issue.

I paste some errors of the logfile:

**_Unexpected error fetching multimatic_quick_mode data: Cannot get token at https://smart.vaillant.com/mobile/api/v4/account/authentication/v1/token/new, status: 503, response: Service Unavailable,payload: None
09:35:05 – (ERROR) Multimatic (custom integration) - message first occurred at February 10, 2022, 22:28:03 and shows up 8 times
Unexpected error fetching multimatic_outdoor_temperature data: Cannot get token at https://smart.vaillant.com/mobile/api/v4/account/authentication/v1/token/new, status: 503, response: Service Unavailable,payload: None
09:35:05 – (ERROR) Multimatic (custom integration) - message first occurred at February 10, 2022, 22:27:57 and shows up 2 times
Unexpected error fetching multimatic_live_reports data: Cannot get token at https://smart.vaillant.com/mobile/api/v4/account/authentication/v1/token/new, status: 503, response: Service Unavailable,payload: None
09:35:05 – (ERROR) Multimatic (custom integration) - message first occurred at February 10, 2022, 22:27:54 and shows up 2 times
Unexpected error fetching multimatic_hvac_status data: Cannot get token at https://smart.vaillant.com/mobile/api/v4/account/authentication/v1/token/new, status: 503, response: Service Unavailable,payload: None
09:35:05 – (ERROR) Multimatic (custom integration) - message first occurred at February 10, 2022, 22:28:09 and shows up 2 times
Unexpected error fetching multimatic_dhw data: Cannot get token at https://smart.vaillant.com/mobile/api/v4/account/authentication/v1/token/new, status: 503, response: Service Unavailable,payload: None
09:35:05 – (ERROR) Multimatic (custom integration) - message first occurred at February 10, 2022, 22:27:51 and shows up 2 times
Unexpected error fetching multimatic_holiday_mode data: Cannot get token at https://smart.vaillant.com/mobile/api/v4/account/authentication/v1/token/new, status: 503, response: Service Unavailable,payload: None
09:35:05 – (ERROR) Multimatic (custom integration) - message first occurred at February 10, 2022, 22:28:06 and shows up 8 times
Unexpected error fetching multimatic_zones data: Cannot get token at https://smart.vaillant.com/mobile/api/v4/account/authentication/v1/token/new, status: 503, response: Service Unavailable,payload: None
09:35:05 – (ERROR) Multimatic (custom integration) - message first occurred at February 10, 2022, 22:27:44 and shows up 2 times_**

**Comment by thomasgermain** [comment]
Hello,

actually nothing I can do about it. The server returns an HTTP 503: https://developer.mozilla.org/fr/docs/Web/HTTP/Status/503, it means the server is not ready to handle a request
