### ISSUE TITLE
[Feature Request] Theoretical COP Calculation based on environmental Yield & Energy Consumption

### ISSUE THREAD

**Issue by VaillantHassIo** [thomasgermain/vaillant-component#121]
It would be nice to have sensor with a theoretical COP Calcuation for  day | week | month

As the API provides Energy Consmption & Environmental Yield for  day | week | month a sensor could be create using a simple calculation such as  sensor.COP = (  Environmental Yield + Energy Consumption ) / Energy Consumption

**Comment by thomasgermain** [comment]
You can also have a look at https://www.home-assistant.io/integrations/utility_meter/ to extract daily value for a sensor
