### ISSUE TITLE
QM_COOLING_FOR_X_DAYS disrupts component

### ISSUE THREAD

**Issue by Leticron** [thomasgermain/vaillant-component#13]
When switching to cooling manually on the main thermostate "Kühlen Manuell für X Tage" I always disrupt the Vaillant component. The logs from HA are posted below:

<pre><code>Logger: homeassistant.helpers.entity
Source: custom_components/vaillant/hub.py:75
First occurred: 12:57:10 PM (107 occurrences)
Last logged: 4:32:20 PM

Update for water_heater.vaillant_control_dhw fails
Update for sensor.vaillant_domestichotwatertanktemperature fails
Update for binary_sensor.vaillant_control_dhw fails
Update for sensor.vaillant_outdoor_temperature fails
Update for binary_sensor.vaillant_system_update fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 279, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 470, in async_device_update
    await self.async_update()
  File "/config/custom_components/vaillant/entities.py", line 48, in async_update
    await self.hub.update_system()
  File "/config/custom_components/vaillant/hub.py", line 75, in _update_system
    self.system = await self._manager.get_system()
  File "/usr/local/lib/python3.7/site-packages/pymultimatic/systemmanager.py", line 87, in get_system
    quick_mode = mapper.map_quick_mode(full_system)
  File "/usr/local/lib/python3.7/site-packages/pymultimatic/model/mapper.py", line 20, in map_quick_mode
    mode = QuickModes.get(quick_mode.get("quickmode"))
  File "/usr/local/lib/python3.7/site-packages/pymultimatic/model/quick_mode.py", line 191, in get
    return cls._VALUES[name]
KeyError: 'QM_COOLING_FOR_X_DAYS' </pre></code>

Is there a possibility to map this state "Kühlen für X Tage" to a supported HVAC state so that the component does not fail?

Regards

**Comment by thomasgermain** [comment]
Hi,

thanks for reporting. This quick mode doesn't seem to be in the doc :/

So of course, I can add the mapping for the component, but then I will need some input from you, since this quick mode is not documented, what does it actually do when you activate it ? And do you have to fill any other data to activate the mode ? (Like you have to fill some dates to activate holiday mode).

Thanks,

Thomas

**Comment by Leticron** [comment]
As this is more of less new for me, I kindly ask you to provide me with an example from the other mods what exactly you need? I will then try to compile that information for you and report back.

**Comment by bveitschegger** [comment]
The only parameter for "QM_COOLING_FOR_X_DAYS" is the number of days the cooling function should be active ('X days').

**Comment by Leticron** [comment]
Regarding the number of days: Those can be either set in the Vaillant app or on the wall-mounted control unit.

**Comment by xrado** [comment]
getting same error

**Comment by thomasgermain** [comment]
I have another question, when you activate this mode, what does it trigger ?
I guess it should activate the "DAY" cooling temperature ?

**Comment by xrado** [comment]
yes, it activates the DAY cooling temperature

**Comment by Leticron** [comment]
Same here - DAY cooling temperature is activated

**Comment by thomasgermain** [comment]
Hi,

sorry for the delay :( I had less time to focus to the project.

So Apparently vaillant created new stuff for cooling and they included it inside the same application. But the underlying connector of this component (done by me) is not supporting cooling at all and I don't have any cooling to test. So the goal is to support it, but it will take me some time to be able to make it work correctly.

I'm gonna see what I can do

**Comment by xrado** [comment]
My Vaillant heap pump can cool too. Somehow cooling doesn't work for me in auto mode (still figuring out why not), so I have to set it to "manual cooling" for X days. After X days system automatically switches back to auto cooling. If you need any help with testing let me know.

**Comment by thomasgermain** [comment]
Hello,

dev is almost done, but I need to cover a use case, but I can't test it:
- let's say your zone is currently cooling (either AUTO mode, or DAY mode)
what will the installation do if you set a quick veto for that zone :stuck_out_tongue_closed_eyes:  ?

I think the quick veto should take precedence, can somebody confirm it ?

Thanks !

**Comment by xrado** [comment]
@thomasgermain what do you mean by "quick veto"?

**Comment by thomasgermain** [comment]
When you open your mobile app -> you select a zone (mine is in french, but I guess you know this screen):
![zone1](https://user-images.githubusercontent.com/12560542/89512825-0e3ae200-d7d4-11ea-8343-0f6336142608.jpg)

then you change the temperature, you should have a screen like this:
![zone2](https://user-images.githubusercontent.com/12560542/89512893-26126600-d7d4-11ea-881b-739bb37c5de4.jpg)

then you click activate, it will create a quick veto (you can desactivate it when you want).

I just would like to know if the quick veto takes precedence over the cooling mode (I know it does over the heating mode). Just to be sure i'm doing it the right way.

Thanks

**Comment by xrado** [comment]
whatever you click you get this alert. When you click on snow icon, you get cancel option. Temperature can’t be changed in the app, but I can change it on the termostat (Desired cooling temperature) with the wheel.
Anything else cancels manual cooling mode

**Comment by thomasgermain** [comment]
ah yeah, but you have a quick mode enabled. 
But as I can see in the API, you can also configure schedule for cooling. Is that right ? So I guess you can configure it, for example; to cool from 8am to 10pm and target temperature is 24. Is that correct ? In that case you won't need to activate the quick mode.

**Comment by xrado** [comment]
yes this is a manual cooling mode, there is also "auto" and "day" mode for cooling, but as I said "auto" never starts cooling for me (have to contact the company in charge) ..haven't tried day mode yet

**Comment by thomasgermain** [comment]
Ah yeah, ok, this is actually annoying indeed. If could try DAY mode then and activate a quick veto, it could be nice :grinning: so I can be sure what I did is correct. 

Thanks a lot

**Comment by Leticron** [comment]
@xrado:

Regarding your "auto" mode not working for cooling:
I got the information from my technician who installed the equipment that the "auto" mode ONLY starts cooling if the outside temperarture during the night is ABOVE 21° C. If this is not the case the auto mode does not activate. For me I was not aware of that and therefore thought the equipment is defect. You probably could check if the outside temperature during nights has been consistently below 21° C for this summer so far.

@thomasgermain:

I only have the options "On", "Auto" and "Off" in the app, there is no day mode in the app but on the wall-mounted control unit I can select "Day" as an option - currently testing what it does regarding to the quick veto.

**Comment by thomasgermain** [comment]
@Leticron 
yes, translations are quite strange. Actually 
- `DAY` mode  is for heating (day is the technical name, in french translation this is "Configuration désirée" , in english "desired configuration").
- `ON` mode is for cooling (on is also the technical name). But I don't know the translation since I don't have the option

**Comment by xrado** [comment]
@Leticron thanks for the info! In which mode do you run cooling now?
@thomasgermain I have same options as @Leticron says

..also the mobile app is quite bad, when you turn off heating and turn on cooling, first screen is still showing heating "off", cooling status is hidden two steps away

**Comment by thomasgermain** [comment]
I also have on question, maybe not the good place, but i'm looking for advice.
Actually, I don't know what to do with that use case:
- Given you have heating and cooling for a zone
- I click to the off icon in the climate entity 
- should I turn off heating AND cooling or only heating or only cooling ? This is really annoying.

I'm also having a look at splitting a zone into 2 climate entities, one for cooling, one for heating, but it sounds it's not user friendly

**Comment by Leticron** [comment]
@xrado I currently use the "Day" mode and cooling is working. I can verify that by seeing the power consumption of the cooling in the app.

@thomasgermain In the app I am not able to produce a quick veto for cooling in "day"/"on" mode. Temperatures are being taken from the time program and when altering the time program (e.g. 8 am to 10 pm for cooling at 21°C) the temperature simply gets set to the selected value.

Regarding your other question for clicking the off icon: 
From my experience I have only one mode active at the same time (either heating or cooling) for my house (which is only 1 zone). Therefore switching off both entities with clicking the off button would be fine for me. Other suggestions are of course also welcome.

**Comment by thomasgermain** [comment]
Actually, if I split a zone into 2 entities, it means we will have 2 entities with the same name (one for heating and one for cooling), from friendliness point of view this is not good, but this is much easier to develop. 

But maybe as you said, if OFF button is pressed in HA, I can set OFF operating mode for both cooling and heating (same when AUTO is pressed, heating and cooling go to AUTO mode). But it means you can't turn heating off and have cooling still ongoing (or the opposite)

**Comment by thomasgermain** [comment]
I started a post in HA community, maybe this is a better place: https://community.home-assistant.io/t/hvac-mapping-question/216365

**Comment by thomasgermain** [comment]
Hello,

you can find a **beta** version here: https://github.com/thomasgermain/vaillant-component/tree/cooling. Since this is a beta, you could have bugs of course :stuck_out_tongue_closed_eyes:, please let me know if you have any issue. Also, **the doc is not up to date yet**. Lot's of things has changed regarding `hvac_mode` and `preset`

I can't fully test it myself because I don't have cooling system.

Thomas
