### ISSUE TITLE
Configuration via UI fails on HA 2022.4.0

### ISSUE THREAD

**Issue by Pagten** [thomasgermain/vaillant-component#130]
When installing the multimatic integration on a fresh HA 2022.4.0 deployment via HACS as described in the readme file, I am unable to configure the integration via the UI. I get the following error message:

![image](https://user-images.githubusercontent.com/1167521/162590789-fb92b92a-37ff-4f4e-9a5a-d2e1c9b3184e.png)

I expected this to be possible since the readme explicitly says the integration can be configured via the UI. Perhaps I'm doing something wrong or maybe there is a bug causing UI configuration to fail on HA 2022.4.0.

**Comment by thomasgermain** [comment]
Are you running the 1.12.5 version ?

**Comment by thomasgermain** [comment]
I just tried with HA 2022.4.0 and 2022.4.3 and I can set up correctly the integration through the UI

**Comment by Pagten** [comment]
> Are you running the 1.12.5 version ?

I am.

> I just tried with HA 2022.4.0 and 2022.4.3 and I can set up correctly the integration through the UI

Must be something with my specific setup then. I just tried adding the integration again and got the same error. I checked the logs this time and I saw this error:
```
Logger: homeassistant.config_entries
Source: config_entries.py:745
First occurred: April 9, 2022, 10:01:48 PM (4 occurrences)
Last logged: 8:28:07 PM
Error occurred loading configuration flow for integration multimatic: No module named 'pymultimatic'
```

**Comment by Pagten** [comment]
I just upgraded from 2022.4.0 to 2022.4.5 and now the UI configuration works.
