### ISSUE TITLE
Cannot control the buffer tank

### ISSUE THREAD

**Issue by Woempia** [thomasgermain/vaillant-component#131]
We can easily control the boiler which works great but we cannot control the buffer tank. Would there be any plans to add this ?

**Comment by thomasgermain** [comment]
Are you able to do it through the multimatic app ?

**Comment by Woempia** [comment]
No you can't so probably it wont be possible then
You can however on the multimatic itself (not the app) choose to have an offset, ie that in case of excess solar it increases the temperature higher in the buffer than it normally would as a way to store energy / heat

**Comment by thomasgermain** [comment]
Yes, there are plenty of configuration you can't touch in the multimatic app.
