### ISSUE TITLE
Hourly updates from VR900?

### ISSUE THREAD

**Issue by salzrat** [thomasgermain/vaillant-component#135]
Hi,
I have managed to integrate the values from my VR900 (Gas for heating and water, as well as electricity for those) in my energy dashboard.

However, it seems these values are only updated once per day. Unfortunately, also the time when this is updated changes once in a while, which makes daily values in the energy dashboard quite useless because you often see spikes and valleys due to these changes.

In the Multimatic app, I can see hourly values. Would it be possible to also have the multimatic component provide hourly updates to the energy counters?

**Comment by thomasgermain** [comment]
Hi,

EMF reports are refreshed every 30min. I don't have any EMF reports myself, so this is pretty hard to test.

But if you say, you can have hourly values in the APP, it should be possible to have it in the integration, I will have a look, but it may take some time to test.

Could you try to call multimatic.request_hvac_update service every ~30min ? The service is requesting an update to vaillant server, so the server will retrieve data from your installation.

**Comment by salzrat** [comment]
Could you tell me how to do that?

**Comment by thomasgermain** [comment]
You can create an automation like this:

```yaml
- id: '1652122001949'
  trigger:
  - platform: time_pattern
    hours: /1
  condition: []
  action:
  - service: multimatic.request_hvac_update
    data: {}
```

**Comment by salzrat** [comment]
So I added the automation and in developer tools confirmed that it works and really executes every 60min, but no change. Any way I could debug this further?

**Comment by thomasgermain** [comment]
No, I will see if I can do different queries to the API.

**Comment by salzrat** [comment]
Hi,
any updates to this? While recently updating my homeassistant to the newest version, I noticed that I got multiple readings over the day due to multiple reboots/restarts of homeassistant. So I think there must be something that can be done to get hourly updates...

**Comment by thomasgermain** [comment]
Well, this is actually quite hard to do, mostly because of the error handling.

There is no hourly update API call out of the box. So the integration will have to guess all the parameters:
- which device is compatible (I would guess that all EMF devices are compatible, but not sure)
- time range, this one is quite easy since it's between hour H and H-1. But then comes the error handling, if the call for 10 to 11 fails, the integration has to remember the next call should be 10 to 12 and you will lose some precision on the energy dashboard
- function, the function for which you want the hourly consumption (cooling, dhw, heating, central heating). The integration can guess it based on the data inside the API (but it has still to be coded)
- energy type (CONSUMED_ELECTRICAL_POWER,  CONSUMED_PRIMARY_ENERGY, ENVIRONMENTAL_YIELD, etc;)
- start and offset, I don't know exactly if these parameters can be usefull.

I can also lead to a lot of API calls (and we know that servers are not so stable), for example an heat pump can heat, cool and dhw it means the integration has to do 1 call per energy type (4?) per function (3?) = ~12 api calls 

Please, also remember that the API is not documented at all, so I have to figure out what are the format of the parameters and they can influence the result.

**Comment by salzrat** [comment]
Ok, I don't know too much about that, but how is it working now? Do you just connect daily? Or is there a callback from the API?

**Comment by thomasgermain** [comment]
For now, consumptions sensors are refresh every 30min, but it sounds there is only one refresh per day at vaillant server side.

You should have an entity  with an id like `sensor.xxx_CONSUMED_ELECTRICAL_POWER` (and others). This is the total consumption from the beginning of your installation. This sensor is configured to work with energy dashboard (so the dashboard can extract the daily consumption).

As I said, this is apparently only refreshed once a day, which is not super accurate, but there is nothing to configure, so the API returns every compatible device and this is only one single API calls.

**Comment by salzrat** [comment]
So how come I once got a result like this, I think when I restarted HA a couple of times due to updates:

![image](https://user-images.githubusercontent.com/9115325/198252956-a780d7dc-3063-431e-aa7b-bafb1a3b1cd5.png)

**Comment by thomasgermain** [comment]
Which entities are you using here ? 
Could you show the history for a specific entity (for 2 days for example) ?

As I said `it sounds there is only one refresh per day at vaillant server side`. There is no doc explaining how they are gathering information from the installation nor how often they are doing it, so it's just assumption.

It could also be that your boiler didn't consume anything for one hour

**Comment by salzrat** [comment]
These are my sources:
![image](https://user-images.githubusercontent.com/9115325/198268033-aea8d6ef-37ba-49f4-bace-417db375be50.png)
 
and here's the central heating eletrical power entity, for example (you can see the time around the updates there are more steps):

![image](https://user-images.githubusercontent.com/9115325/198268372-f0e429dc-260b-4071-94e0-0686b0900a7b.png)

**Comment by thomasgermain** [comment]
Ok, so it sounds like they are sometimes more than one update per day at vaillant server. But we can also see big jumps.

So honestly, I don't know what to do exactly. I can make the "consumption sensor refresh time" configurable, so people can put whatever they want and see if it helps to get accurate value

**Comment by salzrat** [comment]
What is the refresh time in the current version?

**Comment by thomasgermain** [comment]
This is 30min (and not configurable). There is also an initial

**Comment by salzrat** [comment]
This is interesting. 30min should be sufficient to record what I was seeing. Is there any difference in the way the integration refreshes when HA starts and in the regular 30min interval?

**Comment by salzrat** [comment]
which one in your code?

**Comment by thomasgermain** [comment]
Here: https://github.com/thomasgermain/vaillant-component/blob/master/custom_components/multimatic/coordinator.py#L149 to get me EMF report.

You can set the logger level to DEBUG to see when it does the call to the API

**Comment by salzrat** [comment]
Ok, I'll monitor this some more. There do seem to be more frequent updates now, even without restarting. Maybe this is since the update to the new HA 2022.10 and update to the integration...

**Comment by hvbargen** [comment]
This may be silly, but could this be caused by some kind of faulty caching? Maybe it's necessary to add http headers to avoid caching? I'm asking this because years ago I had a similar behavior in one of my programs which called a web service.

**Comment by thomasgermain** [comment]
It worth giving a try, I'll release a version with some cache request header

**Comment by robbedenys** [comment]
I installed the integration yesterday and also only had one or two consumption updates that day (and those were after I restarted HA I think).

Yesterday evening I created an automation running every hour to automatically reload the Multimatic integration and since then I have hourly gas consumption values in the energy dashboard. 

So the data is there but something goes wrong while fetching it. 
I first tried the "request_hvac_update" service in the automation but that didn't work. Reloading the integration does.

**Comment by thomasgermain** [comment]
@robbedenys are you using 1.13.0 ?

**Comment by robbedenys** [comment]
Yes, I am using 1.13.0.

**Comment by robbedenys** [comment]
I just noticed while comparing the values from the MultiMatic app and those from the HA Energy management, that the values from HA are two hours behind those in Multimatic. So my consumption between 0:00 - 1:00 this morning in multimatic is displayed as 2:00 - 3:00 in HA. The values are correct but everything is shifted two hours.

**Comment by Kaot93** [comment]
Having a automation which does the following works for me for having more than one update per day, but I think it messes with made settings like quick veto or something.

```
alias: "Reload: multimatic"
description: ""
trigger:
  - platform: time_pattern
    hours: /1
condition: []
action:
  - service: homeassistant.reload_config_entry
    data: {}
    target:
      device_id:
        - c08629b3e68173000843656f3b33cf89
mode: single
```

**Comment by thomasgermain** [comment]
Do you have fresh data everytime the integration is reloaded ?

I can see two main differences between a classic refresh and the reload of the integration:
- a new "technical" session is created (this is handled by HA itself)
- the integration re-authenticates

**Comment by Kaot93** [comment]
Yes after maybe 5 minutes after the restart I receive fresh data. Else I got 1 update per day. 

So maybe the data slot freezes and can't get updated if not completely freed? 

Is there any log I could provide? 
I attached a screenshot, before and after.
![Screenshot_20230319-092537](https://user-images.githubusercontent.com/48554228/226162828-f19b634a-9982-4a2a-b31d-51f7cacafd7e.png)

**Comment by thomasgermain** [comment]
and you get fresh data for 1h until next reload ? If yes, could you try to stop the automatic integration reload and see when data are not refreshed anymore ?

> So maybe the data slot freezes and can't get updated if not completely freed?
> 
> Is there any log I could provide? 

At this point I don't know exactly where to look at, but I will probably release a new version with more logs

**Comment by thomasgermain** [comment]
You can still set "custom_components.multimatic" and "pymultimatic" to debug

**Comment by Kaot93** [comment]
I only get one update of the data, at pretty much exactly h:05:05 after the reload. There is no additional data before the next reboot.
![Screenshot_20230319-112025](https://user-images.githubusercontent.com/48554228/226169056-96d0ab46-c5fa-4ea4-8503-1a6108ef5db7.png)


I'll add the debug logs to my config.

**Comment by Kaot93** [comment]
Attached a few hours of log file, tried to reduce as much as possible. Maybe it's useful for you.

[home-assistant (1).log](https://github.com/thomasgermain/vaillant-component/files/11011262/home-assistant.1.log)

**Comment by thomasgermain** [comment]
Is this with the reload ?

Data sounds right, I guess the API only refreshes itself once an hour.

Could you show me a graph where data are stuck for more than 1h ?

**Comment by Kaot93** [comment]
This is the graph of a whole day before the reload automation.
![Screenshot_20230319-214040](https://user-images.githubusercontent.com/48554228/226207808-7012bbdc-686c-404e-a783-3861df60514d.png)

I will attach the log of the night without the reload automation tomorrow if that helps.

**Comment by Kaot93** [comment]
And the log from tonight:

[home-assistant (2).log](https://github.com/thomasgermain/vaillant-component/files/11015167/home-assistant.2.log)

As expected there was no data updated.
![Screenshot_20230320-082338](https://user-images.githubusercontent.com/48554228/226272962-a33ecc52-ce72-417c-9806-fa34250a08f9.png)

**Comment by thomasgermain** [comment]
Nice thanks.

I will check what I can do (maybe forcing a re-login every 30min) to see if it changes something

**Comment by martinalig** [comment]
Hey, I can observe the same issue here with my setup. What I noticed: Every time I open the iPhone multiMatic app, I can see fresh data in HA after a few minutes. Not sure how this relates to each other, but could be due to some caching. I will further look into the requests that the iPhone app makes, maybe I can see a difference to you implementation. Could you give me a pointer to the python code, that does the actual requesting for the data? Thanks.

**Comment by salzrat** [comment]
Oh, that might explain why I sometimes see more than one update a day as previously reported. Those are maybe days where I check the app more often!
So maybe the values get updated when you login, and maybe the multimatic app has some API it uses for refresh, or it just does a new login every time?

**Comment by salzrat** [comment]
I think I created a new user for homeassistant. Where can I find the user I'm using for the integration?

**Comment by thomasgermain** [comment]
I don't know where the configuration are stored for the integrations. But you had to enter user password while configuring the integration

**Comment by salzrat** [comment]
what would be the configuration variable? I could grep for it in the config dir...

**Comment by martinalig** [comment]
> @salzrat, @martinalig are you both log in with the same user in your app and HA ? If yes, the integration will re-authenticate by itself (since the API prevents having same users logged in multiple times), so that might explain why you can see some refresh.

I use a dedicated account for HA

> @martinalig I disabled caching (at least, I asked the server to not use cache, but the server can still ignore it). The actual call is done here: https://github.com/thomasgermain/pymultiMATIC/blob/593d17572e4872023c5bacf0eaed4d1b27c6aacf/pymultimatic/systemmanager.py#L214.

Thanks, I will try to look into this and come back

**Comment by thomasgermain** [comment]
So, version https://github.com/thomasgermain/vaillant-component/releases/tag/1.14.0b03 is available.

It does a re-login every 1h. Please let me know if it works (and if the re-login doesn't cause issue).

You can now have more debug logs by configuration `custom_components.multimatic` and `pymultimatic` logger to `debug`. Pay special attention before sharing the debug logs, it will print the user (not the password ;)) you are logged in with and all the requests (+ parameters) and responses exchanged with the API.

**Comment by salzrat** [comment]
Yes, now it works here as well. The numbers are an hour late compared to the Multimatic-App, but that can probably not be avoided. I.e., if I have a consumption between 8:00 and 9:00 in Multimatic, it will show up as 9:00-10:00 in Homeassistant. When does the query happen? Does it depend when the integration is first started, or is it a fixed time? Maybe one could try doing it just a few minutes before the hour, if the values from the server are accurate, maybe this gives the best match?

**Comment by martinalig** [comment]
Also works here. Thanks a lot!
Regarding 

> Yes, now it works here as well. The numbers are an hour late compared to the Multimatic-App, but that can probably not be avoided. I.e., if I have a consumption between 8:00 and 9:00 in Multimatic, it will show up as 9:00-10:00 in Homeassistant. When does the query happen? Does it depend when the integration is first started, or is it a fixed time? Maybe one could try doing it just a few minutes before the hour, if the values from the server are accurate, maybe this gives the best match?

This is also something I noticed. I intercepted and looked at the requests the iPhone app is doing: The Multimatic API also returns the hourly values. So instead of just storing the full total, we could also store the hourly values? Is this something you have already thougth about? Or is the a specific reason, you just store the total values?

**Comment by Kaot93** [comment]
I get only one update per h:
![Screenshot_20230324-133034](https://user-images.githubusercontent.com/48554228/227521923-2d04b1ac-2978-4832-862b-075f84d9a837.png)

In my opinion the sensors go way more often to unavailable than before. Should I share my log?
![Screenshot_20230324-133502](https://user-images.githubusercontent.com/48554228/227522817-4c25c27c-c094-4ba1-ad06-c133c0ff6347.png)

**Comment by hvbargen** [comment]
I think this is unrelated to the latest changes.

**Comment by salzrat** [comment]
It works better now, but it doesn't seem to capture all the hourly changes. Here are from 2 days ago for example...
![Bildschirmfoto 2023-03-25 um 12 40 58](https://user-images.githubusercontent.com/9115325/227715445-593a18cf-eaf4-496a-8930-c0046218e422.png)
![2023-03-25 12 42 04](https://user-images.githubusercontent.com/9115325/227715447-cc04878f-ed90-4d86-a189-43b5798c6d90.png)

**Comment by martinalig** [comment]
Hey, I checked the last few days, and the values in HA are now identical to the ones  in the multimatic App. (at least the daily sums are the same, not yet sure about the hourly values)
Thanks a lot for your work.

**Comment by salzrat** [comment]
So any idea on how to make the reports match the ones by the app? Today, everything matched nicely, except for being exactly 1 hour late.

**Comment by Kaot93** [comment]
Wouldn't it be enough to make the re-login on /45 of each hour? 

I'm fine with how it is atm. The recent offline problematic was caused by multimatic servers as it seems.

**Comment by salzrat** [comment]
or maybe /55, but we can't control that at the moment, right?

**Comment by Kaot93** [comment]
Well @thomasgermain should be able to change it.

/55 could be a bit tricky, at least with my reboot automation the update time was mostly more than 5 minutes.

**Comment by Kaot93** [comment]
Hey everyone, 

Since a few days I get no updates from the energy consumption at all anymore. 

Somebody know what happened there?

![Screenshot_20230507-215939](https://user-images.githubusercontent.com/48554228/236700065-e0545c4b-3e16-4d47-8a08-2d43f883dd9f.png)

Best wishes

**Comment by salzrat** [comment]
I can only say it's working without problems here...

**Comment by Kaot93** [comment]
Strangely it's working again for me. Don't know what happened here. 
So everything fine again 👍

**Comment by robbedenys** [comment]
I think there are some issues with Vaillant's servers again, I also don't get correct data into HA, and the data in the Multimatic app is also not right.
