### ISSUE TITLE
How to change mode from "heating" to "cooling" //flexoTHERM VWF 87/4

### ISSUE THREAD

**Issue by moritzschieder** [thomasgermain/vaillant-component#141]
Many thanks Thomas for the great work!

I have an issue with the following use case:
Changing the mode of my heat pump from "heating" to "cooling"

Setup:
Vaillant flexoTHERM VWF 87/4 (this heat pump is capable of cooling - I can change the mode in the multiMATIC app)
Vaillant sensoNET VR 921
HA OS 8.4
Multimatic integration 1.12.7

Integration in HA worked well and I can see the following devices & entities:

<img width="726" alt="Screen Shot 2022-08-18 at 09 28 55" src="https://user-images.githubusercontent.com/33522982/185309928-b254df17-24c7-4af9-a9b1-e4085d9f7cd6.png">

<img width="662" alt="Screen Shot 2022-08-18 at 09 29 15" src="https://user-images.githubusercontent.com/33522982/185309997-900ba596-d2fe-4f40-8f14-27fc8fda0131.png">

However, I do not see any entity related to changing the mode from "heating" to "cooling"

Any help highly appreciated!

**Comment by thomasgermain** [comment]
Hello,
You should have a climate entity. The climate entity is not linked to the heat pump, but you should find it in entities related to the multimatic integration

**Comment by moritzschieder** [comment]
Thanks for the super fast reply!

I do not have/find a climate entity. Any ideas why?

**Comment by thomasgermain** [comment]
Do you have a zone or room in multimatic app ?
Normally you should have climate entity per zone and room.

In order to debug, can you set log level to debug for the integration and reload the it and post it here ?

**Comment by thomasgermain** [comment]
I guess the VR921 is causing some troubles to the integration :/

Could you have a look here: https://github.com/thomasgermain/pymultiMATIC/tree/master/script and pick up print_response script (.sh if you're using linux, or ps1 for windows powershell script).

And run it like this: `print_response.sh user password https://smart.vaillant.com/mobile/api/v4/facilities/<your_serial>/systemcontrol/v1/zones`

Could post the response here ? (You might need to remove some private info). It should give you some details about the zones you have

**Comment by moritzschieder** [comment]
Here is the response:

<img width="1237" alt="Screen Shot 2022-08-20 at 19 18 01" src="https://user-images.githubusercontent.com/33522982/185756619-c56ef9ac-6ae8-4784-8e53-f9917564977b.png">

Does this make sense?

**Comment by thomasgermain** [comment]
You have to remove `<` and `>` from the url and just let your raw serial id

**Comment by moritzschieder** [comment]
I have tried this:

`sh print response.sh user password https://smart.vaillant.com
/mobile/api/v4/facilities/21193…6827N5/systemcontrol/v1/zones`

and receive the following:

`{"errorCode": "FACILITY NOT _COMPATIBLE" )#`

**Comment by moritzschieder** [comment]
Hi Thomas, after some hours of reading I have found the possible reason: I own the VRC 720 :(

Any hope on a potential future integration of the VRC 720?

Anyhow, many thanks for your support and dedication with this topic, really appreciated!

**Comment by thomasgermain** [comment]
Hello,

Sorry for the delay, I had a crazy week :sleepy: 

For now there is no support foreseen, because it's pretty hard for me to test it without the hardware and also because my-vaillant should rollup and unify all the API.

But I'm also open to receive some PR to support it if anybody wants to do it.
