### ISSUE TITLE
home assistant

### ISSUE THREAD

**Issue by nickfysiek** [thomasgermain/vaillant-component#142]
I installed it trough hacs and now it shows up, i can also find it in my custom folder, but how to i get it to show the entities?

**Comment by thomasgermain** [comment]
Hello,

Did you add the integration to HA ? I mean in the integration screen, you click add integration (bottom right), search for multimatic and set your login/password ?

**Comment by nickfysiek** [comment]
For some reason i couldnt find it in repositories yesterday, now it showed up and it works!
________________________________
Van: Thomas Germain ***@***.***>
Verzonden: zondag 28 augustus 2022 9:35
Aan: thomasgermain/vaillant-component ***@***.***>
CC: nickfysiek ***@***.***>; Author ***@***.***>
Onderwerp: Re: [thomasgermain/vaillant-component] home assistant (Issue #142)


Hello,

Did you add the integration to HA ? I mean in the integration screen, you click add integration (bottom right), search for multimatic and set your login/password ?
