### ISSUE TITLE
Odd-on repo

### ISSUE THREAD

**Issue by sipi58** [thomasgermain/vaillant-component#143]
Hi,
I'd like to test this solution on my Vaillant ecoCompact boiler but I can'i add this repo to Home Assistant.

How can I add this repo?

Thank you for your help.

**Comment by thomasgermain** [comment]
Hello, you first need HACS to be installed and you can check how to add the repo to HACS https://hacs.xyz/docs/faq/custom_repositories/

**Comment by sipi58** [comment]
Hello, it is right but I can't know what is the repo's exact URL.. When I insert this URL:
https://github.com/thomasgermain/vaillant-component
I get an error message that isn't valid repo...
What is the correct URL this repo?
Many thanks.

**Comment by thomasgermain** [comment]
I did a fix, apparently something became deprecated at HACS.

And yes, the URL is: https://github.com/thomasgermain/vaillant-component

Could you have a try ?

Thanks
