### ISSUE TITLE
Integration not listed in Homeassistant 

### ISSUE THREAD

**Issue by rbartholomay** [thomasgermain/vaillant-component#146]
Hi!

i use the following Homeassistant:

```
Home Assistant 2022.9.4
Supervisor 2022.08.6
Operating System 8.5
Frontend 20220907.2 - latest
```

and it seems that the component is loaded because of the warning:

```
2022-09-17 21:09:44.152 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration multimatic which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
```

but after a restart and a second restart the multimatic integration is not listed in Homeassistant.

any ideas?

**Comment by thomasgermain** [comment]
Hello,

I don't see what could be the problem. Indeed it sounds the integration is loaded since you see the warning.

You can try to set multilatic log to debug level, just to be sure that the integration is refreshing data every 2 minutes.

Maybe you can try to refresh your browser cache ?

**Comment by rbartholomay** [comment]
Hi,

i try to set the custom log via:

```
logger:
  default: warning
  logs:
    custom_components.multimatic: debug
```

but in the logs I only get the warning again and in the device list it‘s missing. I use the HACS method for installing. I will try the manual method also…


Bye, René

**Comment by thomasgermain** [comment]
Did you add the integration through integration screen ? (I mean, setting your user/password ?)

**Comment by rbartholomay** [comment]
the integration is screen is not visible  - because I cannot select the integration - it's missing.
Am I right that installation via HACS only needed the multimatic package? Or are there other dependencies?

Bye René

**Comment by lecocqe** [comment]
Hello,

procedure is as follows.

1) install Multimatic via HACS
2) Add integration via "parameters"
       if it's not listed in "add integration" button, clear the cache of your browser and restart Home Assistant (via parameters - system). then try to add integration again

hope it will help

best regards

**Comment by thomasgermain** [comment]
Hey @rbartholomay is it working ?

**Comment by rbartholomay** [comment]
Hi!

sorry for the late answer. Currently I cannot make a „real“ test, because i must downgrade to haos 8.5. I use another integration that will have bugs with the newer version. So currently I have a „mixed“ version that is not really a good system for testing.
You can close this issue - I will reopen it when I can use the current version of all for really testing…

Sorry for that…
