### ISSUE TITLE
Multimatic Error Status working?

### ISSUE THREAD

**Issue by caroso-de** [thomasgermain/vaillant-component#147]
Hi, I just got the integration up and running after the vaillant services were temporarily unavailable.
Now I'm wondering whether the multimatic errors sensor is working properly. My system is currently in an error state, which the App reflects correctly (F.55/10, defective CO sensor), but the sensor is reporting "ok/off" 

Is this an issue with the data coming from the api or with the sensor itself? I'm happy to check API responses if that helps, but I don't know which endpoints are involved.

vc276 vrc700 vr900

Thank you!

**Comment by thomasgermain** [comment]
Hello, the sensor should definitely work, the API endpoint is: https://smart.vaillant.com/mobile/api/v4/facilities/{serial}/hvacstate/v1/overview.

You can check script here: https://github.com/thomasgermain/pymultiMATIC/tree/master/script (sh for linux and ps1 for windows), usage is quite simple: `./print_response.sh user password url`

**Comment by caroso-de** [comment]
thank's I' give it a try and report back

**Comment by caroso-de** [comment]
Ok, here it is. binary_sensor.multimatic_errors reports `off`; i don't see a binary_sensor.<name_of_the_boiler> entity. Maybe there is still another problem?

```
"errorMessages": [
            {
                "deviceName": "VC 276/5-7 (N-DE)",
                "type": "LIMP_HOME",
                "title": "FLIDE",
                "statusCode": "N.22",
                "description": "...",
                "hint": "...",
                "timestamp": 1663503743906
            },
            {
                "deviceName": "VC 276/5-7 (N-DE)",
                "type": "MAINTENANCE",
                "title": "Komfortsicherungsbetrieb aktiv",
                "statusCode": "M.22",
                "description": "Ausfall/Defekt des CO-Sensors",
                "hint": "Das Gerät läuft ohne Modulation auf ca. 60% der max. Gerätebelastung, 1) E.18-Wert auslesen/notieren, dann CO-Sensor tauschen, 2) Wenn E.18 = 0, dann zusätzlich Zündung und Verbrennung kontrollieren",
                "timestamp": 1663503743906
            }
        ]
````

**Comment by thomasgermain** [comment]
Yeah the authentication error is well know, the API just reject another authentication with the same user/password "too soon" after another. It should fixed by itself.

So, the binary_sensor.multimatic_errors stays off because the type of error is "LIMP_HOME" and "MAINTENANCE". When there is an error, normally the type is ERROR and the code starts with "F". (This is something I coded, so I can improve it).

Also, in order to have a binary_sensor.<name_of_the_boiler>, the API should return an errors with type "STATUS", which is giving the current status, for example, the error messages I received from the API are like this:

```
"body": {
    "errorMessages": [
      {
        "deviceName": "VC BE 246/5-3",
        "type": "STATUS",
        "title": "Mode été : aucune demande d’eau chaude sanitaire",
        "statusCode": "S.31",
        "description": "Le mode chauffage est désactivé et il n’y a pas de demande d’eau chaude sanitaire.",
        "hint": "...",
        "timestamp": 1562356114295
      },
    ]
  }
```

the `type` stays always "STATUS" but if the code change to something Fxxx I know there is an error. 

For you, it seems the status is coming from somewhere else :/

**Comment by thomasgermain** [comment]
You an check this repo: https://github.com/thomasgermain/pymultiMATIC, this is where the actual API calls are done.

The starting point is the SystemManager (which is using the low level Connector to do API calls)

**Comment by caroso-de** [comment]
> Yeah the authentication error is well know, the API just reject another authentication with the same user/password "too soon" after another. It should fixed by itself.
> 
> So, the binary_sensor.multimatic_errors stays off because the type of error is "LIMP_HOME" and "MAINTENANCE". When there is an error, normally the type is ERROR and the code starts with "F". (In the integration I only displaying the one with ERROR type, but I can add them all in the binary_sensor_multimatic_errors).

That would be great. A defective CO-sensor is a very common issue with this type of heaters and as a result the device operates far from optimal efficiency. Without proper notification, this often remains unnoticed for a while. 
I'm a bit surprised that the API doesn't report the error 'F.55' that the heater currently displays.

As a suggestion: what about setting the multimatic_errors sensor to on if errorMessages are not empty?

> 
> Also, in order to have a binary_sensor.<name_of_the_boiler>, the API should return an errors with type "STATUS", which is giving the current status, for example, the error messages I received from the API are like this:

I see, thanks for the explanation

**Comment by caroso-de** [comment]
so I browsed pymultiMATIC and I have to say not being a python expert I don't want to fiddle around with the project as a whole at this point. But regarding the status problem: would this do the trick?

```
Index: pymultimatic/model/mapper.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/pymultimatic/model/mapper.py b/pymultimatic/model/mapper.py
--- a/pymultimatic/model/mapper.py	(revision 86019d20225d8db50a7d9f3f6c39c2c98a786870)
+++ b/pymultimatic/model/mapper.py	(date 1663613252888)
@@ -466,7 +466,7 @@
     """Map *errors*."""
     errors = []
     for error in hvac_state.get("body", {}).get("errorMessages", []):
-        if error.get("type") == "ERROR":
+        if error.get("type") != "STATUS":
             errors.append(
                 Error(
                     error.get("deviceName"),

```

**Comment by thomasgermain** [comment]
Yes, this is what I had in mind. 

I will also dig in the doc to see what `statusCode` = `Mxx` means. I know that `Sxx` means it's OK and `Fxx` means error, but I don't know for `Mxx`

**Comment by caroso-de** [comment]
Great, I'll have a look myself, too.

**Comment by thomasgermain** [comment]
So, (I've been really busy these past few days :O) versin https://github.com/thomasgermain/vaillant-component/releases/tag/1.12.8 should allow to retrieve more hvac messages.

Fell free to reopen if this is not working as expected

**Comment by caroso-de** [comment]
Awesome, thank you! I don't have the broken sensor available any more, so I can't test against my installation.  Nevertheless, I had a look at #151 and I'm very confident that this will work 👍 Will switch back from my fork today.

p.s. thanks a lot for the effort you're putting in this component, including incorporating my api resonses into your tests. This is highly appreciated.
