### ISSUE TITLE
Keeps resetting to auto heating

### ISSUE THREAD

**Issue by colesadam** [thomasgermain/vaillant-component#148]
Hi, I have a problem where I try to change the heating temperature (enabling quick veto) and it registers the change (as confirmed in the VRC700 app) but resets back to auto within minutes. 

Logbook doesn't show any automation changes so this may well not be caused by the component but wondering if anyone else has seen this behaviour?

**Comment by colesadam** [comment]
I'm not sure if it's the same, I've had this for a while where no matter where I make the change using the API (either through the VRC 700 Android App or Home Assistant) the change is registered but a few minutes later it resets back to Auto (from quick veto). All that happens in the logbook is showing the entity changing state with no associated automation etc. Mind you I find the Vaillant system incredibly flaky with frequent dropouts of availability.

**Comment by thomasgermain** [comment]
So you mean, even if you use the app, it also resets to AUTO ?

From HA point of view: the integration sets the quickveto (and force HA to reflect the change) and send the request to the API. The integration refreshes data every 2 min (by default), so since, the quickveto request is not processed by the API, the API still thinks there is not quickveto and return AUTO mode (and the integration can only trust what it receives from the API)

**Comment by colesadam** [comment]
Even if I use the app the same thing happens. I've noticed this doesn't seem to happen at night where I have an automation setting a quick veto for 30 minutes, but during the day I can either change in the app or change in HA, see the change reflected in the app then minutes later it's gone back to AUTO. I have a similar automation that set's a quick veto at 8.30 and it usually only lasts a few minutes.

**Comment by colesadam** [comment]
Hi Thomas. I've not had a lot of joy from Vaillant, it got to the point where the internet gateway just cycled for a week and they sent an engineer out but he couldn't find any problem and then it magically fixed itself. The app itself has very poor ratings but, as a developer myself, it feels like lots of their problems are on the back end. Posting here in case other people have had the same issues I suppose, if not I'll close this off.

**Comment by thomasgermain** [comment]
I totally agree with you, their infrastructure is really poor. if I check my HA history, I have about 1h/day of dowtime (it means ~5% downtime, in 2022 it's just incredible).

Can I close the issue ? 

By the way, if you contacted them, let me know about their response if any ;)

**Comment by colesadam** [comment]
Haven't really got any coherent response I'm afraid. I'll close this one off.
