### ISSUE TITLE
Missing climate entity, outside temperature sensor and service set_quick_mode not working

### ISSUE THREAD

**Issue by flobo1990** [thomasgermain/vaillant-component#149]
Hi thomasgermain,

the integration works basically, thanks for your work.
But a few things don't seem to work in my setup:
Heat pump VWF58/4
VR921

I have no climate entity "climate.xxx" and no sensor "sensor.outside_temperature". However, in the Multimatic app these values are displayed.
This is all I receive:
![image](https://user-images.githubusercontent.com/61708287/192586437-6ee48f48-c37e-40d1-b030-aa96d5bac791.png)

Furthermore, the service: multimatic.set_quick_mode does not work:

service: multimatic.set_quick_mode
  data:
    quick_mode: QM_HOTWATER_BOOST

Thought about this I could trigger the function "hot water fast", as it is called in the Multimatic App.
I get the error "Error calling the service multimatic/set_quick_mode. Cannot put https://smart.vaillant.com/mobile/api/v4/facilities/21210900202609620938012014N2/systemcontrol/v1/configuration/quickmode, status: 409, response: {"errorCode": "FACILITY_NOT_COMPATIBLE"},payload: {'quickmode': 'QM_HOTWATER_BOOST'}}
"
Am I doing something wrong?

Thanks for your help.

flobo1990

**Comment by thomasgermain** [comment]
So, I added a small note on the readme about the VR921. It sounds like, in certain cases, that the VR921 is using a different API than the one supported in the integration.

I'm gonna close all the issues related to the incompatibility. But I'm still open to receive a PR to support this API.
