### ISSUE TITLE
The heating phase for hot water is displayed wrong

### ISSUE THREAD

**Issue by bloug30** [thomasgermain/vaillant-component#150]
Hello,

By visualizing the heating phase, this one does not seem to correspond with a 2 hour shift

![1](https://user-images.githubusercontent.com/112944115/193088128-7a47140d-262a-48d0-84ed-a3b63b6e7d93.JPG)
![2](https://user-images.githubusercontent.com/112944115/193089927-572df186-3b99-46e4-a704-b51026e4e614.JPG)

Tell me how to help you for other tests

Thx

**Comment by thomasgermain** [comment]
What timezone are you ?

Do HA and multimatic app have the same timezone ?

**Comment by bloug30** [comment]
sorry for my late reply, yesterday it was impossible to access to multimatic apps (service unavailable)
I actually have one hour of delay on the multimatic app  (app does not manage the hourly delay for winter/summer )

HA is also in GMT+1 Paris instead of GMT+2 so both are on the same time zone.

I just re-set the whole thing to GMT+2 and I'm waiting to confirm the delay or not (if the valiant servers don't fall today)

**Comment by bloug30** [comment]
Thanks for your feedback

I preferred to wait to check the cycles following the change to GMT+2 in HA.
Unfortunately I always have a delay and there it seems to be 3 hours...

![Capture](https://user-images.githubusercontent.com/112944115/194215534-20f9ba82-b854-491a-b9e8-0c08e6b79cf8.JPG)

I don't have a timezone type setting on the mobile app, just the date/time to enter. 

![Screenshot_20221006-062040_VRC 700](https://user-images.githubusercontent.com/112944115/194215455-09159ab2-169e-44bc-bc12-5f047e39b64a.jpg)


I confirm that the time on the app and on the multimatic is the same time.

Now, even if I have an error on my time zone, this should **not influence the offset between the two elements!**
Do you have any other leads?

thx

**Comment by thomasgermain** [comment]
Hmm Strange, because in the multimatic app, I can set a timezone, see:
![Screenshot_2022-10-06-06-50-40-64_a23d235124f522f2f4eac702e62a32e9](https://user-images.githubusercontent.com/12560542/194223156-0021e0a9-31fd-4b8b-9589-a84d430fe043.jpg)

So, I think that the app knows somehow which timezone your are (because it heats when you ask for it), but I guess the time program is stored in a different format in the API. In order to be sure, could you:
- go there: https://github.com/thomasgermain/pymultiMATIC/tree/master/script
- download correct script for you (.sh for linux, .ps1 for window)
- run it (in powershell for windows): `./print_response.sh user password url`
- in your case, url is: `https://smart.vaillant.com/mobile/api/v4/facilities/<serial>/systemcontrol/v1/dhw/Control_DHW/hotwater/configuration/timeprogram` (replace <serial> with your actual serial number
- show me the response (you might have to remove some data from the response, like your serial, etc).

Thanks

Thomas

**Comment by bloug30** [comment]
Sorry I'm not a powershell pro...

I downloaded the file for windows: **print_response.ps1**
I opened powershel ISE in administrator mode.
I opened the script 
I typed the command:
C:\Users\pages\Desktop\print_response.ps1 **<my_vaillant_login>** **<My_vaillant_password>** https://smart.vaillant.com/mobile/api/v4/facilities/**<My_vaillant_serial>**/systemcontrol/v1/dhw/Control_DHW/hotwater/ config/timeprogram


I must have missed something, here is the screenshot:

![1](https://user-images.githubusercontent.com/112944115/194343354-53904515-a245-49ab-b0a5-3e7cc2bb4dc6.png)

**Comment by lecocqe** [comment]
Don't use < > in command 😉

**Comment by thomasgermain** [comment]
It sounds the download of the script went wrong, you can download the script directly from here: https://raw.githubusercontent.com/thomasgermain/pymultiMATIC/master/script/print_response.ps1

**Comment by bloug30** [comment]
you won't like the answer :s  :

**PS C:\WINDOWS\system32> C:\Users\pages\Desktop\print_response.ps1 ******* ****** https://smart.vaillant.com/mobile/api/v4/facilities/2***************************4/systemcontrol/v1/dhw/Control_DHW/hotwater/configuration/timeprogram**
<!doctype html><html lang="en"><head><title>HTTP Status 404 â€“ Not Found</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:
14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 404 â€“ Not Found</h1><hr class="line" /><p><b>Type</b> Status Report</p><p><b>Description</b> The origin server did not 
find a current representation for the target resource or is not willing to disclose that one exists.</p><hr class="line" /><h3>Apache Tomcat/mobilDIALOG-Live</h3></body></html>



sorry

**Comment by thomasgermain** [comment]
My bad, here is the correct url:
`https://smart.vaillant.com/mobile/api/v4/facilities/<serial>/systemcontrol/v1/dhw/Control_DHW/hotwater/timeprogram`

**Comment by bloug30** [comment]
There is no harm :)

`{"body":{"monday":[{"startTime":"00:00","mode":"OFF"},{"startTime":"05:30","mode":"ON"},{"startTime":"21:00","mode":"OFF"}],"tuesday":[{"startTime":"00:00","mode":"OFF"},{"startTime":"05:30","mode":"ON"},{"startTime":"20:00","mode":"OFF"}],"wednesday":[{"sta
rtTime":"00:00","mode":"OFF"},{"startTime":"05:30","mode":"ON"},{"startTime":"21:00","mode":"OFF"}],"thursday":[{"startTime":"00:00","mode":"OFF"},{"startTime":"05:30","mode":"ON"},{"startTime":"21:00","mode":"OFF"}],"friday":[{"startTime":"00:00","mode":"OF
F"},{"startTime":"05:30","mode":"ON"},{"startTime":"20:00","mode":"OFF"}],"saturday":[{"startTime":"00:00","mode":"OFF"},{"startTime":"07:10","mode":"ON"},{"startTime":"21:00","mode":"OFF"}],"sunday":[{"startTime":"00:00","mode":"OFF"},{"startTime":"07:10","
mode":"ON"},{"startTime":"21:00","mode":"OFF"}]},"meta":{"resourceState":[{"state":"OUTDATED","timestamp":1665084957000,"link":{"rel":"self","resourceLink":"/facilities/<My_vaillant_serial>/systemcontrol/v1/dhw/Control_DHW/hotwater/timeprogram"}}]}}`


thank you for your time !

**Comment by thomasgermain** [comment]
Ok, so, my next question is: could you confirm you start your hotwater at 5:30 (and end at 20:00) ?

**Comment by thomasgermain** [comment]
What about this one ?
> Also, what does it output if you run the following template in HA: `{{now()}}` ?

**Comment by bloug30** [comment]
Sorry I didn't really understand the question what do you want me to do?
{{now()}}

set to manual? and redo the command in powershell?

**Comment by bloug30** [comment]
I think I understood 

I create this template in configuration.yaml : 

`template:
  - sensor:
      - name: "Date and time"
        state: "{{now()}}"
        icon: "mdi:calendar-clock"`



![Capture5](https://user-images.githubusercontent.com/112944115/194469165-4c990849-c314-4459-b572-09beee252e8b.JPG)

as I write it is 6:42 a.m.

**Comment by thomasgermain** [comment]
It looks good. By the way you can go to "developer tools" (bottom left in the side bar) -> template. There you can type any kind of template and see the actual result.


How did you install HA ? (docker, HA OS, VM, something else) ?

**Comment by bloug30** [comment]
Thanks for the tip, it's really easier ! 
My HA is : Home Assistant Core 2022.5.0  from Qnap docker 

HA sends info to a MariaDB database (MariaDB 10.5.8 ) ; 

I use phpmyadmin with MariaDb (from qnap).
I have two databases: one for HA and the other for Fibaro system, on the fibaro database I have no error with dates.

When I look at phpmyadmin:

SELECT @@system_time_zone; result: CEST
SELECT @@GLOBAL.time_zone; result: SYSTEM
SELECT @@SESSION.time_zone; result: SYSTEM
select now(); Result: the time is ok

same result on both databases

On my php.ini :  

[Date]
date.timezone = "Europe/Paris"

And even if I change the time zone in HA the BDD keeps a 2h00 offset.

it seems that the error is when HA sends the data to the MariaDb database

Pour cela dans configuration.yaml : 
```
recorder: 
 db_url: !secret mariadb_url
```
and in : secrets.yaml : 
```
mariadb_url: mysql://root:MyPass@192.168.1.10:3307/HA?charset=utf8mb4
```
maybe I'm missing something for the date time ?!

![BDD_HA_utc_plus2JPG copie](https://user-images.githubusercontent.com/112944115/194554422-01684e70-2ba0-45d3-9c04-1b23bddd2085.jpg)

**Comment by thomasgermain** [comment]
I think mariaDB is ok, I guess it internally stores dates in UTC format. 

Do you have any other wrong entity history, with the same offset or only the multimatic one ?

Did you specified the timezone when starting your docker container ?
Do you have any access to your container ? The idea is to access the CLI of the container and type the command `date` to see if the container has the right date.

**Comment by bloug30** [comment]
I have terminal access
```
/config # date
Fri Oct  7 19:06:39 UTC 2022
/config # 
```
now it's 21h06

**Comment by thomasgermain** [comment]
ah ! That could be the issue. 

Could you run your docker with your specific timezone ? I think you can just pass a `TZ` env var

**Comment by bloug30** [comment]
I modified my container by changing the TZ

/config # date
Sat Oct 8 06:30:45 CEST 2022
/config#

the time of registration in the database remains in UTC

but to think about it this does not change the problem which is the two hour difference between my two curves:
ECS set point
ECS water temperature
no matter the time zone

I think the problem is quite different

there, the setpoint is supposed to rise to 57° at 7:00 AM
it's 7:12 still nothing!

**Comment by bloug30** [comment]
![Screenshot_20221008-073545_VRC 700](https://user-images.githubusercontent.com/112944115/194690991-8be88408-c5c9-48c1-82a0-aff6300f3c45.jpg)
![6](https://user-images.githubusercontent.com/112944115/194691047-518f7692-3692-4749-805b-59297989fdb5.JPG)

**Comment by thomasgermain** [comment]
Do you have any error in the log ?

Did you restarted mariaDB ?

You could also try to use the default database, to see if it fixes something

**Comment by bloug30** [comment]
No error in the log of HA ,

here error un container console  : 
```
2022-10-08 06:28:56 ERROR (MainThread) [custom_components.multimatic.coordinator] Unexpected error fetching multimatic_holiday_mode data: Unable to authenticate at https://smart.vaillant.com/mobile/api/v4/account/authentication/v1/authenticate, status: 401, response: {"errorCode":"NOT_AUTHORIZED"},payload: None
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 191, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 150, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/multimatic/coordinator.py", line 533, in _fetch_data_if_needed
    return await self._fetch_data()
  File "/config/custom_components/multimatic/coordinator.py", line 526, in _fetch_data
    return await getattr(self.api, self._method)()
  File "/config/custom_components/multimatic/coordinator.py", line 141, in get_holiday_mode
    self._holiday_mode = await self._manager.get_holiday_mode()
  File "/usr/local/lib/python3.9/site-packages/pymultimatic/systemmanager.py", line 43, in wrapper
    return await func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pymultimatic/systemmanager.py", line 292, in get_holiday_mode
    raw = await self._call_api(urls.system_holiday_mode)
  File "/usr/local/lib/python3.9/site-packages/pymultimatic/systemmanager.py", line 80, in wrapper
    return await func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pymultimatic/systemmanager.py", line 857, in _call_api
    response = await self._connector.request(method, url, payload)
  File "/usr/local/lib/python3.9/site-packages/pymultimatic/api/connector.py", line 157, in request
    await self.login(True)
  File "/usr/local/lib/python3.9/site-packages/pymultimatic/api/connector.py", line 67, in login
    await self._authenticate(token)
  File "/usr/local/lib/python3.9/site-packages/pymultimatic/api/connector.py", line 125, in _authenticate
    raise ApiError(
pymultimatic.api.error.ApiError: Unable to authenticate at https://smart.vaillant.com/mobile/api/v4/account/authentication/v1/authenticate, status: 401, response: {"errorCode":"NOT_AUTHORIZED"},payload: None
```

yes a have restart mariadb. The setpoint information does not go up in HA also.
Here is my last test with the powershell:

```
{"body":{
"monday":[{"startTime":"00:00","mode":"OFF"},{"startTime":"05:30","mode":"ON"},{"startTime":"21:00","mode":"OFF"}],
"tuesday":[{"startTime":"00:00","mode":"OFF"},{"startTime":"05:30","mode":"ON"},{"startTime":"21:00","mod e":"OFF"}],
"wednesday":[{"startTime":"00:00","mode":"OFF"},{"startTime":"05:30","mode":"ON"},{"startTime":"21:00","mode":"OFF"}],
"thursday":[{"startTime":"00:00","mode":"OFF"},{"startTime":"05:30","mode":"ON"},{"startTime":"21:00 ","mode":"OFF"}],
"friday":[{"startTime":"00:00","mode":"OFF"},{"startTime":"05:30","mode":"ON"},{"startTime":"21:00","mode":"OFF"}],
"saturday":[{"startTime":"00:00","mode":"OFF"},{"startTime":"07:00","mode":"ON"},{"startTime":"21 :00","mode":"OFF"}],
"sunday":[{"startTime":"00:00","mode":"OFF"},{"startTime":"07:10","mode":"ON"},{"startTime":"21:00","mode":"OFF"}]},
"meta":{"resourceState":[{"state":"OUTDATED","timestamp":1665216426000,"link":{"rel":"self"," resourceLink":"/facilities/******/systemcontrol/v1/dhw/Contr
```

**Comment by bloug30** [comment]
![Capture](https://user-images.githubusercontent.com/112944115/194697141-ce8ead06-20e8-44fe-accf-c4fc44c634c9.JPG)

here, we see that the triggering of the setpoint starts at 7:10 a.m. (57°)
so my boiler does not start at the time of the application or the multimatic (both are at the same time) but on UTC time?!
on the other hand, end at the right time?

**Comment by thomasgermain** [comment]
I guess you shouldn't base yourself on the date you see here:
- I don't see any timezone for the date on your printscreen
- is it the date directly coming mariaDB or somehow modified by phpmyadmin ?

Also, isn't 7:10 am what you configured in the multimatic app ? How does it look like in HA ?

**Comment by bloug30** [comment]
**> * I don't see any timezone for the date on your printscreen**
several post above I explain the time difference on my database
![194554422-01684e70-2ba0-45d3-9c04-1b23bddd2085](https://user-images.githubusercontent.com/112944115/194700670-a0241342-fe69-4f28-8907-d8d8db695e84.jpg)


**> Also, isn't 7:10 am what you configured in the multimatic app ? How does it look like in HA ?**

yes I have configured 7:10 but there is quad even the time difference on the base which should appear!

If I indicate 7:00 a.m. on the database should appear (-2:00 a.m.): 5:00 a.m.

**Comment by thomasgermain** [comment]
As I said you shouldn't base yourself on the date of the database.

What does HA show in the history now that you have a correct timezone on your container ?

Also, did you try with the default HA database ?

**Comment by bloug30** [comment]
**> As I said you shouldn't base yourself on the date of the database.**
it is true . I actually solved the problem with the dates through the management of the time difference via the TimeZone of HA
as well as that of Grafana

I think that the error yesterday of "not starting the ECS instruction" is due to too many requests (mobile app .. powershelll ... HA restart etc ...) because this morning everything is ok.

I now have to check if the DHW setpoint T° corresponds to the T° curve

**> What does HA show in the history now that you have a correct timezone on your container ?**
The correct Time it's Ok !

**> Also, did you try with the default HA database ?**
Unfortunately no :(  I am too new and I have already had trouble integrating the data into maria DB !
The table structures is the one generated by HA



Could you confirm something for me please?
With a gas boiler it is currently not possible to retrieve consumption information (Gas and/or Electricity)?

**Comment by thomasgermain** [comment]
I'm glad you eventually have the correct history ;)


About the  consumption it depends on the devices you have, but basically, if you can't see it in the app, it means you won't see it in HA.

You can try the powershell script with this url: https://smart.vaillant.com/mobile/api/v4/facilities/<serial>/emf/v1/devices to be sure.

**Comment by bloug30** [comment]
Thank you very much for your help and you time
