### ISSUE TITLE
Does not work anymore

### ISSUE THREAD

**Issue by GLehnhoff** [thomasgermain/vaillant-component#153]
I used the Add-on with the Thermostat card for a while, only to see the temperature. Unfortunately, since Oct 8 or 9 there is no change anymore. It seems that the Thermostat card or this plug in does not get any data anymore. 

![image](https://user-images.githubusercontent.com/5453201/195317935-727e1b75-e247-49eb-a9d3-244428898533.png)

**Comment by thomasgermain** [comment]
Hello,

If you open your app, do you have any fresh data ?

Also, do you have any errors in the log ?

I personally have an automation which is calling multimatic.request_hvac_update every hour. This service is actually asking the server to fetch last data from your local devices.

**Comment by GLehnhoff** [comment]
I close this issue as it seems not to be a problem of the plugin. In the meanwhile all data has been updated in the app and in the plugin. However, it took about an hour after the reset of VR900.
