### ISSUE TITLE
Operating state

### ISSUE THREAD

**Issue by bloug30** [thomasgermain/vaillant-component#154]
Hello,
I want to retrieve the operating status of the boiler (heating, inactive etc..)
So I created a sensor:

```
  #Current temperature setting
      - name: "multimatic_etat_plancher"
        unique_id: multimatic_etat_plancher
        state: "{{state_attr('climate.control_zo1_********', 'hvac_action')}}"
        unit_of_measurement: ''
        state_class: 'measurement'
```
I notice that I often have a status: “**unknown**”    Is it possible to find the meaning of this state?

![Capture](https://user-images.githubusercontent.com/112944115/195756964-9b558e06-0975-4a00-ae0f-c9eaaa789680.JPG)

merci

**Comment by thomasgermain** [comment]
Hi,

could you check if you have any error in the log when the sensor become unknown ?
It can happen if there is an error at vaillant server level.
It can also happens after HA started but before the integration fetches data

**Comment by bloug30** [comment]
no error in the log, 
but indeed, after restart HA I get an "UnKnow" . You are right!
Thanks again !
