### ISSUE TITLE
Hi Thomas

### ISSUE THREAD

**Issue by magerkurth** [thomasgermain/vaillant-component#155]
Do you have access to sensors and readings which are not provided in the mobile GUI? For example:

- burner modulation
- flow return temp
- TRV temperatures which are joined under a room thermostat VR15

BW

Joerg

**Comment by thomasgermain** [comment]
Hello, 

unfortunately, no. I can only have access to what you can see in the app.

You may be able to get these info via ebusd: https://fromeijn.nl/connected-vaillant-to-home-assistant/ (you can also find other links on google). It requires more work, but you can have access to more sensors.

Thomas
