### ISSUE TITLE
Multimatic server issues

### ISSUE THREAD

**Issue by johanvh83** [thomasgermain/vaillant-component#156]
Hi,
First of all my apologies because this is not an issue from your integration but I didn't know where else to ask this question.
Last weeks I have many problems with the Multimatic server connection; very offen offline, unavailable or online but not operational. To be honest I experience also some Wifi issues in my house. So I'd like to aks your recent experience?
I have opened a Vaillant support ticket and they answered that they recently and frequently restarting the server because of improvements...
In the past I used the manual preset_mode and managed all from Home Assistant by just changing the temperature of rooms. 
Due to the server/wifi? problems, very often changes from HA were not made to the Multimatic system. Very annoying in the morning to awake in a cold house/room.
As a workaround I thought to put the system at night in comfort (auto) mode, so the Multimatic timing takes over.
After few hours, I change the preset_mode to manual to work as before.
The problem is when the Multimatic server is offline or non operational.
Even if I use the service 'request hvac update' some entities are not reflecting the actual state.
I did some simulations by unplugging the Multimatic wifi module. The binary_sensor.multimatic_system_online remains online...
It was my idea to make an automation with repeat until actions in order to be sure that at night the rooms go to 'comfort' mode but as I said, some entities doesn't reflect the real state...
I'm wondering how you use your Multimatic system with the server issues...

**Comment by thomasgermain** [comment]
Hi,

I have the same kind of problems with the server stability (data are not available, not refreshed, etc.). Hopefully, I don't play that much with climate entities. I only have few automations regarding climates, and the most used one is actually detecting that there is nobody home when this is time to heat the bathroom and create a quick veto to not heat it.

I would suggest to put everything in comfort mode as much as possible because once is configured, it (hopefully) doesn't need a cloud connection to adjust the temperature target automatically.

Regarding the binary_sensor.multimatic_system_online, it actually checks if **your** system is online and can be reached by the vaillant server. So for example: vaillant server is up and running, but you unplug your VR9XX. The integration will work fine but (after some delay), this binary_sensor should go to off.

Regarding the unreliability of the server, maybe you can create some script (for example to set target temperature) which will:
- call a climate service
- wait X seconds
- ensure the state has changed
- if state not changed, retry

Hope it helps,

Thomas

**Comment by johanvh83** [comment]
Hi Thomas,

Thanks for your reply. At least now I know it wasn't not only my Wifi network that occured the problems.
It's not acceptable for a well-known A-brand mutinational as Vaillant to provide such a poor amateuristic service!
Several moments of the day I change the temperature based on home-presence but due to the problems especially for the 'critical' moments (read morning) I use the comfort (auto) mode that works without cloud service.
Later on I switch to manual to manage the day and at night I send the command to change again to comfort, up to 5 times with an interval of 1 hour after I checked the state.
Thanks to the workarounds it's more reliable.

**Comment by johanvh83** [comment]
Hi Thomas,

Every time I have problems, I open a support ticket from the application (Help -> Feedback).

They answered me that they are aware of the communication problems.
The development team is doing the almost to optimise a new server.

Between now and the end of 2023 everyone will receive an invite to switch to a new application that works with the new server and this should resolve all problems.

I'm afraid there is a big chance that your existing integration will not longer work on this new server.

**If so, I really hope you can again but a lot of effort to find out how the communication works and you are able to create a new or updated integration for Home Assistant!**

The relialability is a big issue now but I hope we don't loose everything once their new server and application is up and running.

**Comment by thomasgermain** [comment]
As far as I know, "myVaillant" should be the new "thing" and it should unify most of the API, but not sure if multimatic will be migrated. I can only find information about the migration on the Germain website and it's foreseen (for my config) in Q3 2023.

The community also find some student job offer to develop a python connector for myVaillant, so HA and other home automation could use it.

Anyway, if I migrate to myVaillant I will probably do something, if nobody did already

**Comment by johanvh83** [comment]
Hmm, Q3 2023 is something else than between now and end of the year...
Today I had again problems. Most entities were N/A and the 'binary_sensor.multimatic_system_online' was unavailble, while the Multimatic application on my mobile worked.
I had to reload your integration before it started to work again.
Is it a big job to make an additional feature to reload your integration as a Home Assistant service call?

**Comment by thomasgermain** [comment]
Maybe you can use: https://www.home-assistant.io/integrations/homeassistant#service-homeassistantreload_config_entry

About myVaillant, I found this: https://upgrade.myvaillant.com/vaillant
In Belgium/French, I can't even find any mention to multimatic, like it won't get migrated nor any schedule.
Same for english.
But in german: https://www.vaillant.de/heizung/produkte/mobile-apps/myvaillant-app/, their talking about multimatic, so I hope it will get migrated,. There is also a schedule, but I don't think this is up to date.

![image](https://user-images.githubusercontent.com/12560542/200161311-9f8bc095-e05f-4958-93a4-d2f5e05c0013.png)
