### ISSUE TITLE
Setpoint for heating circuit

### ISSUE THREAD

**Issue by SebTech** [thomasgermain/vaillant-component#158]
Hi

Thank for an AWSOME integration!

Is there a way to change the Target_temperature for the heating loop?
The loop that is measured with: sensor.flowtemperaturesensor_#

**Comment by thomasgermain** [comment]
Hello,


There is no way to change it.

The flow temperature sensor is actually the temperature of the water that goes out of the boiler.

You can change the curve through the VRCXX, but I guess there are some computation at the boiler to optimized the water temperature
