### ISSUE TITLE
Automatic datetime updates

### ISSUE THREAD

**Issue by vit-** [thomasgermain/vaillant-component#159]
In my local area, we are experiencing frequent power grid shutdowns. When Multimatic returns back online it has incorrect datetime settings. Since Multimatic doesn't seem to have NTP-based time sync, it would be great if Homeassistant could update Multimatic's datetime settings automatically.

**Comment by thomasgermain** [comment]
So, apparently there is a way to set the datetime manually through the API.

I'm not sure what it exactly does. But I could check if it does something interesting and add a service (multimatic.set_datetime ?) so it can be called easily in an automation

**Comment by thomasgermain** [comment]
Hello,

version https://github.com/thomasgermain/vaillant-component/releases/tag/1.12.9 adds a new multimatic.set_datetime service.

If the datetime is no provided, it uses now. 

Let me know if it doesn't work ;)

**Comment by xrado** [comment]
@thomasgermain cool! is it possible also to get the multimeric datetime?

**Comment by thomasgermain** [comment]
I don't know, I'll have a look within next week. 
But be aware that datetime sensor are a bit tricky, because of timezone conversion

**Comment by vit-** [comment]
The service seems to work fine. Thank you so much for such a quick implementation!
