### ISSUE TITLE
Is it down?

### ISSUE THREAD

**Issue by BartoszJarek** [thomasgermain/vaillant-component#161]
It looks like integration is not working any more after recent maintenance. Today I lost connection with all devices. I tried to reinstall integration but now I am unable to login (using MultiMATIC credentials). 
Can someone confirm ? 

I am using multiMATIC 700 controller with hear pump + RecoVAIR ventilation unit

**Comment by lecocqe** [comment]
Just back on-line.

 



 

A question: in case no internet, does the ambisense system work ?

 

Best regards,

 

From: BartoszJarek ***@***.***> 
Sent: 02 November 2022 13:47
To: thomasgermain/vaillant-component ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [thomasgermain/vaillant-component] Is it down? (Issue #161)

 

It looks like integration is not working any more after recent maintenance. Today I lost connection with all devices. I tried to reinstall integration but now I am unable to login (using MultiMATIC credentials).
Can someone confirm ?

I am using multiMATIC 700 controller with hear pump + RecoVAIR ventilation unit

**Comment by BartoszJarek** [comment]
I am not using ambisense system. I am able to control all via MultiMATIC app on iOS.
