### ISSUE TITLE
No matching statistics found

### ISSUE THREAD

**Issue by salzrat** [thomasgermain/vaillant-component#163]
I just noticed that when I want to configure a gas consumption source (click "edit" on the source in settings), I get "No matching statistics found"). I noticed this because costs suddenly were much too high, so it seemed to interpret the entity as "Wh" instead of "kWh". 

The consumption does still seem to get reported correctly in the dashboard, which is strange...

**Comment by thomasgermain** [comment]
Hello,

Sorry, I don't get what you're trying to edit, is it an entity from the integration ?

Could you also give me the entity id for which the unit doesn't seem to be correct ?

By dashboard, you mean the HA energy dashboard ?

Do you have any error in the log or a screenshot ?

**Comment by salzrat** [comment]
The entity name is:
VC 206/5-7 (H-AT/CH) CENTRAL_HEATING CONSUMED_PRIMARY_ENERGY
the entity-id is:
sensor.nonegateway_ll_bai00_0291_eco_gas_pr_ebus_central_heating_consumed_primary_energy_2...... (many digits)

But it seems the entity cannot be found in the HA energy dashboard configuration:

![image](https://user-images.githubusercontent.com/9115325/201344968-0fdfb725-4c8c-4348-a88b-98a2b2c62484.png)

although it's still being shown in the dashboard, with correct kwh but wrong cost (I changed the cost just before to EUR per Wh instead EUR per kWh, but this is not reflected yet in the number):
![image](https://user-images.githubusercontent.com/9115325/201345773-43184938-7852-4564-9e43-b87e3faf4900.png)

**Comment by thomasgermain** [comment]
Could you show me all the attributes of this entity ? (Developer tools -> states -> filter by name or id). 

How did you manage to get something in the dashboard if you can't add the entity ?

For the wrong values, this is due to HA energy dashboard, I think it should fixed by itself the next hour.

**Comment by salzrat** [comment]
this?

![image](https://user-images.githubusercontent.com/9115325/201373764-56452d63-5308-433d-941b-8d99d80c46eb.png)

overall the multimatic integration has 6 devices and 17 entities, I now filtered by "none", as "nonegateway" appears in all these sensors that are related to consumption.

It was working before, so maybe something is still in the system, but I wouldn't be able to readd it if I deleted it...

**Comment by thomasgermain** [comment]
Entities attributes look good to me.

What version of HA do you have ?

**Comment by salzrat** [comment]
2022.11.2, everything updated to the latest version…

**Comment by thomasgermain** [comment]
Sounds like there issue with gas stuff in HA: https://github.com/home-assistant/core/issues/81953 or https://github.com/home-assistant/core/issues/81891.

**Comment by thomasgermain** [comment]
@salzrat do you have any update on this one ?

Feel free to close it if it works :)

**Comment by salzrat** [comment]
It does seem to work now. When I edit the sensor, I can select all available sensors. And in the static price box, EUR/Wh is correctly listed. Not sure why one can't switch it to EUR/kWh, but it works.
