### ISSUE TITLE
Humidity and dew point attribute

### ISSUE THREAD

**Issue by Levante75** [thomasgermain/vaillant-component#164]
Installed my VR920 and the Multimatic integration. Works perfect, great job, thank you
Do see any possibility to add humidity and dew point as an attribute?
Both are visible on the VR700 thermostat but not in Multimatic, so I guess the answer is "no". No big deal!

**Comment by thomasgermain** [comment]
Hi,

Unfortunately, as you said, the integration can only access Hat the mobile has.
