### ISSUE TITLE
I need help with  "M3u Parser Project"

### ISSUE THREAD

**Issue by Seyf25** [thomasgermain/vaillant-component#169]
Hello Thomas,
I couldn't understand how to use the project I linked below, can you help me? The project is very beautiful and works as far as I understand, but I could not run it.
I had to ask here because the "Issues" section is not open there. Thanks in advance for your help.

https://github.com/thomasgermain/m3u-parser

**Comment by thomasgermain** [comment]
Hello,

Well, this is a pretty old project :sweat_smile: .

Anyway, you can use it like this: `new Parser().parse(<inputStream>)` and it gives you a list of all entries in your m3u

**Comment by Seyf25** [comment]
You are amazing Thomas!
That much of your answer was enough for me. And it still works very well 😅 😃
