### ISSUE TITLE
little help ?

### ISSUE THREAD

**Issue by bloug30** [thomasgermain/vaillant-component#171]
Hello Thomas,

I want to retrieve information about Fibaro HC3. Is it possible to have a little help for the connection steps ? if **it's not private, of course** ?

I guess there are two steps?
The first with a GET to obtain a Token?
and the second with POST to send query commands

```
function QuickApp:multimatic()
    self.http:request("https://smart.vaillant.com/mobile/api/v4/account/authentication/v1/token/new", {
        options={
            method = "POST",
            data = '{"smartphoneId": "pymultiMATIC",  "username": "My_Vaillant_Login", "password": "My_Vaillant_Passwaord"  }',
            headers = {
		[ 'Content-Type' ] = 'application/json',
                [ 'Accept' ] = 'application/json', 
            }
        },
        success = function(response)
            if response.status == 200 then
               self:debug('ok')
               local jsonResponse = json.decode(response.data)
            else
                self:debug('Error : '  .. response.status .. response.data)
            end
        end,
        error = function(error)
            self:debug('error: ' .. error)
        end
    })
end
```
I think my data is wrong:
`data = '{"smartphoneId": "pymultiMATIC",  "username": "My_Vaillant_Login", "password": "My_Vaillant_Passwaord"  }',`

Thank you for any help you can give me

**Comment by thomasgermain** [comment]
Hello, 

you can check this repo: https://github.com/thomasgermain/pymultiMATIC, more specifically https://github.com/thomasgermain/pymultiMATIC/blob/d2b02a1f62f721e69cedb89b9ce2f082a34139c5/pymultimatic/api/connector.py#L52

Indeed, there are 2 steps, get a token and authenticate.

Your first request to get a token sounds good, but you are missing the new "magic" header:  https://github.com/thomasgermain/pymultiMATIC/blob/d2b02a1f62f721e69cedb89b9ce2f082a34139c5/pymultimatic/api/connector.py#L16

**Comment by bloug30** [comment]
Thank you very much for your support !!

```
Server-Timing: intid;desc=a14a1c0a3195fea7
Set-Cookie: JSESSIONID=2507CAEB82F5C45923C38840575EC01A; Path=/; Secure; HttpOnly
Allow: POST
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: 0
Strict-Transport-Security: max-age=31536000 ; includeSubDomains
X-Frame-Options: DENY
Content-Type: text/html;charset=utf-8
Content-Language: en
Content-Length: 759
Date: Thu, 08 Dec 2022 05:01:11 GMT
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Strict-Transport-Security: max-age=31536000; includeSubDomains;
X-Frame-Options: SAMEORIGIN
Set-Cookie: TS01b0e19c=01e5b3f1f837a236502d2968b9b957dbaef8eca42668155bb40d4f93f80e60284179856775b29ca06e1d7e16bf46ce7e2eb9a9cc8d; Path=/; Secure; HTTPOnly
```
Could you confirm to me that with this request in Status 405 (Get) or 400 (POST) this one is indeed finished?
Is the Token on:
**`Set-Cookie: JSESSIONID=2507CAEB82F5C45923C38840575EC01A`**
to continue to step 2? or the "Token" is something else?

Step2 
MEthod POST :

        params = {
            "smartphoneId": self._smartphone_id,
            "username": self._user,
            "password": self._password,
        } 
`https://smart.vaillant.com/mobile/api/v4/account/authentication/v1/authenticate`
```
        token_res = await self._session.post(url=urls.new_token(), json=params, headers=HEADER)
        if token_res.status == 200:
            json = await token_res.json()
            return str(json["body"]["authToken"])
```

Thank you

**Comment by thomasgermain** [comment]
Are you using a dedicated user ? If you ask multiple token "too soon" for the same user it can return a 401.

Also, are you sure your user/password is correct :D ?

**Comment by bloug30** [comment]
I have onluy one User, I disabled multimatic in HA.
and I checked my user/password :(

`{"smartphoneId": "pymultiMATIC",  "username": "aa@aa.com", "password": "1a2B#"  }`

same thing on reqbin :(

**Comment by bloug30** [comment]
![a](https://user-images.githubusercontent.com/112944115/206847974-bd733b17-f8ae-46c1-b0b8-e8f8bb9c6f6b.JPG)
![b](https://user-images.githubusercontent.com/112944115/206848000-ac87c881-640f-4d38-a742-c42a81f3692e.JPG)
![c](https://user-images.githubusercontent.com/112944115/206848012-e1c6676b-8fb8-483f-8616-063df5d789df.JPG)
![d](https://user-images.githubusercontent.com/112944115/206848040-45bcdaf8-a237-4f13-904a-7e501b98d13f.JPG)

**Comment by bloug30** [comment]
Ok,

N°1 : POST Cmd To get Token                 ===> Status 200 Ok
N°2:  POST cmd ti authenti   with Token  ===> Status 200 Ok

N°3:  GET cmd with URL like :
`
https://smart.vaillant.com/mobile/api/v4/facilities/21***S*e*r*i*a*l***N4/system/v1/details

```

function QuickApp:login()
    print('Connexion à la requette N°2 -  avec le Token : ' .. token )
        self.http:request("https://smart.vaillant.com/mobile/api/v4/account/authentication/v1/authenticate", {
        options={
            method = "POST",
            data = '{ "smartphoneId": "pymultiMATIC", "username": "' .. log .. '", "authToken": "' .. token .. '" }' ,
            headers = {
				[ 'content-type' ] = 'application/json;charset=UTF-8',
                [ 'Accept' ] = 'application/json',
                [ 'Vaillant-Mobile-App' ] = 'multiMATIC v2.1.45 b389 (Android)',
            }
        },
        success = function(response)
            if response.status == 200 then
               self:debug('Connection avec le Token : Ok')
               local jsonResponse = json.decode(response.data)
               print("")
               self:get() -- Commande GET 
            else
                self:debug('Error : '  .. response.status .. response.data)
            end
        end,
        error = function(error)
            self:debug('error: ' .. error)
        end
    })
end


function QuickApp:get()

    print('SEND Get CMD :' .. test )
        self.http:request("https://smart.vaillant.com/mobile/api/v4/facilities/21***S*e*r*i*a*l***N4/system/v1/details", {
        options={
            method = "GET",
            headers = {
		[ 'content-type' ] = 'application/json;charset=UTF-8',
                [ 'Accept' ] = 'application/json',
                [ 'Vaillant-Mobile-App' ] = 'multiMATIC v2.1.45 b389 (Android)',
            },
             --data = test
        },
        success = function(response)
            if response.status == 200 then
               self:debug('Connection Ok')
               local jsonResponse = json.decode(response.data)

               self:debug(response.data)

            else
                self:debug('Error : '  .. response.status .. response.data)
            end
        end,
        error = function(error)
            self:debug('error: ' .. error)
        end
    })
end

```

again 401 where i'm bad ?

**Comment by thomasgermain** [comment]
Once the authentication is done, you should receive a cookie, this cookie should be included in all calls you want to do.

I don't know what is `self.http`, maybe you need to configure it in order to send to cookie ?

**Comment by bloug30** [comment]
Thank, 

Does it's :

`Set-Cookie: JSESSIONID=A7C5E08EF9BA57D0AA83AF2B61C3B8DC`
or 
`Set-Cookie: TS01b0e19c=01e5b3f1f8e4a950f1f49eea73579757dca64d61386a6f719154cfc7c620485737c49d50bf64ccb5e9df73bd80f232653dd3dacabe`
?

`self.http:request` is the command to make request on Fibaro QuickApp

function QuickApp:login()
    print("____________________________________________________________")
    print('Connexion à la requette N°2 -  avec le Token : ' .. token )
        self.http:request("https://smart.vaillant.com/mobile/api/v4/account/authentication/v1/authenticate", {
        options={
            method = "POST",
            data = '{ "smartphoneId": "pymultiMATIC", "username": "' .. log .. '", "authToken": "' .. token .. '" }' ,
            headers = {
				[ 'content-type' ] = 'application/json;charset=UTF-8',
                [ 'Accept' ] = 'application/json',
                [ 'Vaillant-Mobile-App' ] = 'multiMATIC v2.1.45 b389 (Android)',
            }
        },
        success = function(response)
            if response.status == 200 then
               self:debug('Connection avec le Token : Ok')
               SetCookie = response.headers['Set-Cookie']  -- Je récupère le Set-Cookies
                for i = 1, #SetCookie do
                    if SetCookie:byte(i) == string.byte(";") then
                        SetCookie1 = SetCookie:sub(0,i - 1)
                        break
                    end
                end

               print('COOKIES : ' .. SetCookie1)

               self:get() -- Commande GET 
            else
                self:debug('Error : '  .. response.status .. response.data)
            end
        end,
        error = function(error)
            self:debug('error: ' .. error)
        end
    })
end


function QuickApp:get()

test =  '{ "https://smart.vaillant.com/mobile/api/v4/facilities/'.. serial .. '/system/v1/details" }'

```
    print("____________________________________________________________")
    print('N°3 - SEND GET cmd ! avec le Cookies : ' .. SetCookie1 )
        self.http:request("https://smart.vaillant.com/mobile/api/v4/facilities/21164500201971170933016633N4/system/v1/details", {
        options={
            method = "GET",
            headers = {
				[ 'content-type' ] = 'application/json;charset=UTF-8',
                [ 'Accept' ] = 'application/json',
                [ 'Vaillant-Mobile-App' ] = 'multiMATIC v2.1.45 b389 (Android)',
                [ 'Set-Cookie' ] = SetCookie1,
                [ 'Set-Cookie' ] = SetCookie2,
            },
        },
        success = function(response)
            if response.status == 200 then
               self:debug('Connection Ok')
               local jsonResponse = json.decode(response.data)

               self:debug(response.data)

            else
                self:debug('Error : '  .. response.status .. response.data)
            end
        end,
        error = function(error)
            self:debug('error: ' .. error)
        end
    })
end

```
I manage to retrieve the 1st cookie from request 2 and place it in the GET command but not the second.
I guess that's the most important one

**Comment by bloug30** [comment]
@thomasgermain  Me again :)  401 again 👎 

should the retrieved cookies be placed in the "header" of the GET command ?
and should i use : 
data = '{ "smartphoneId": "pymultiMATIC", "username": "' .. log .. '", "authToken": "' .. token .. '" }'

```

    print('N°3 - SEND GET cmd ! avec les Cookies 1 & 2 ...' )
        self.http:request("https://smart.vaillant.com/mobile/api/v4/facilities/2*S*E*R*I*A*L*4/storage/default", {
        options={
            method = "GET",
            data = '{ "smartphoneId": "pymultiMATIC", "username": "' .. log .. '", "authToken": "' .. token .. '" }' ,
            headers = {
		[ 'content-type' ] = 'application/json;charset=UTF-8',
                [ 'Accept' ] = 'application/json',
                [ 'Vaillant-Mobile-App' ] = 'multiMATIC v2.1.45 b389 (Android)',   --- Magic Header 
                [ 'Set-Cookie' ] = cookie1,                                        --- Cookie : JJSESSIONID= From authentication " Header "
                [ 'Set-Cookie' ] = cookie2                                         --- Cookie : TS01b0e19c=  From authentication " Header "
            },
        },
        success = function(response)
            if response.status == 200 then


```


```
[13.12.2022] [06:11:11] [DEBUG] [QUICKAPP621]: ____________________________________________________________
[13.12.2022] [06:11:11] [DEBUG] [QUICKAPP621]: Connexion à la requette N°1 - authentification ....
[13.12.2022] [06:11:12] [DEBUG] [QUICKAPP621]: Authentification : Ok
[13.12.2022] [06:11:12] [DEBUG] [QUICKAPP621]: Get Token : 06b64a147d024910a26a73d8c509a30f
[13.12.2022] [06:11:12] [DEBUG] [QUICKAPP621]: ____________________________________________________________
[13.12.2022] [06:11:12] [DEBUG] [QUICKAPP621]: Connexion à la requette N°2 - avec le Token : 06b64a147d024910a26a73d8c509a30f
[13.12.2022] [06:11:12] [DEBUG] [QUICKAPP621]: Connection avec le Token : Ok
[13.12.2022] [06:11:12] [DEBUG] [QUICKAPP621]: ____________________________________________________________
[13.12.2022] [06:11:12] [DEBUG] [QUICKAPP621]: N°3 - SEND GET cmd ! avec les Cookies 1 & 2 ...
[13.12.2022] [06:11:12] [DEBUG] [QUICKAPP621]: Error : 401
```

**Comment by bloug30** [comment]
ahahah 

`boiteacookies = cookie1..';'..cookie2`

```
            headers = {
                 [ 'Cookie' ] = boiteacookies,                 
                 },
```
