### ISSUE TITLE
Outside temperature missing

### ISSUE THREAD

**Issue by a1466d44-d3dc-4c0b-90c7-315b088731d7** [thomasgermain/vaillant-component#173]
Hi, and thank you for your great work!

I have only a little question: On the Vaillant sensor App, teh outside temperature is displayed on the top middle part or the first screen. So the information seems to exist somewhere in the API.
But I seem to be unable to find an object that represents the outside temperature in Home Assistant.
Is it because it does not exists, or because I am unable to find it? :)

Best regards

**Comment by lecocqe** [comment]
see https://community.home-assistant.io/t/vaillant-multimatic-integration/87240/348

outdoor temp is an attribute

**Comment by a1466d44-d3dc-4c0b-90c7-315b088731d7** [comment]
Thank you for your response. but unfortunately I have no idea how to check the attribute of a climate object, as I have not found such a thing. therefore I cannot configure a template sensor without the proper name.
Do you have a tip that could point me in the right direction?
thank you in advance

**Comment by a1466d44-d3dc-4c0b-90c7-315b088731d7** [comment]
Ahh I see, VR921 is not fully supported. so that why some attributes are missing...
If I could I'd really like help someone who is able to develop a proper extension by sharing from my environment what's needed.

Best regads and thank you in advance. I think this issue can be closed
