### ISSUE TITLE
Thermostat support for controlling DHW

### ISSUE THREAD

**Issue by pawelgarbacz** [thomasgermain/vaillant-component#175]
Hi, I have vaillant-component integrated with my Home Assistant setup and it's connecting to Vaillant heat pump that works as two functions - general underfloor and running water heating source.

In HA dashboards I added Thermostat card to control the general heating and it works very well:

```
  - type: thermostat
    entity: climate.control_zo1_2*********************n9
    name: ''
```

I tried to do the same, but vaillant-component does not expose dedicated thermostat (climate control) for DHW function and it would be nice if it has been supported the same way. Water heating in fact has similar features: current temperature, temperature setting, mode of operation, etc.

Since there is no climate control for water heating I tried alternate approach to create Generic Thermostat in configuration like this:

```
climate:
  - platform: generic_thermostat
    name: Ciepła woda
    heater: water_heater.control_dhw_2*********************n9
    target_sensor: sensor.domestichotwatertanktemperature_2*********************n9
```

Unfortunately this does not work as I would expect - Thermostat card presents for this generic thermostat the current (big number) temperature correctly (it displays same value as the target_sensor reports) but the temperature set in the controller (small number below the big number) is presented as a completely strange value (33.9 currently) and honestly I have no idea where does it come from.

Screenshot below presents both Thermostat cards:
![thermostats](https://user-images.githubusercontent.com/92933509/209790524-72af3f6d-340f-42f2-9ac5-3c51413cf3e8.png)

Entity attributes as I can see in developer tools are as follows:

```
hvac_modes: heat, off
min_temp: 7
max_temp: 35
target_temp_step: 0.1
current_temperature: 38.5 (this is correct)
temperature: 33.9 (this comes from I have no idea where)
hvac_action: off
friendly_name: Ciepła woda
supported_features: 1
```

At the same time water_heater entity has following attributes:

```
min_temp: 35
max_temp: 70
operation_list: ON, OFF, AUTO
current_temperature: 38.5
temperature: 44
target_temp_high: null
target_temp_low: null
operation_mode: AUTO
away_mode: off
friendly_name: Termostat ciepłej wody
supported_features: 7
```

and the attributes of the underfloor heating climate entity are like here:

```
hvac_modes: auto, off
min_temp: 5
max_temp: 30
preset_modes: comfort, day, sleep, home, party, away, system_off
current_temperature: 22.2
temperature: 22
hvac_action: heating
preset_mode: comfort
friendly_name: DOM
supported_features: 17
```

In entities I can find another entity: water_heater.control_dhw_2*********************n9 which represents and allows to control the settings for the water heater, but it's done through a normal Entity card only and visually it would be more convenient if it was done through a thermostat.

Therefore I wonder if it is possible to add/convert existing water_heater entity into climate entity so it would be compatible with the Thermostat card? If it is not the way it should work question is why Generic Thermostat binds some strange temperature setting which does not even appear anywhere near Vaillant's attributes?

**Comment by thomasgermain** [comment]
Hello,

I was actually annoyed by this `water_heater` in HA, because this is pretty limited, but this is the way HA integrates water heater, so I will stick to it.

Personally use `mushroom-climate-card` which allows a water heater.

As you said, there is a way to create generic thermostat out of the water heater. I don't know how it works, but for sure `sensor.domestichotwatertanktemperature_2*********************n9` entity is not the target temperature, but the actual temperature.

The `temperature` attribute from `water_heater` entity is the target temperature. So I guess you should create an entity out of this attribute and reference this entity as `target_sensor`
