### ISSUE TITLE
DHW - Setpoint Hight and low

### ISSUE THREAD

**Issue by bloug30** [thomasgermain/vaillant-component#176]
Hi,
I am looking for information about DHW

**I find my hight set point :**  
`https://smart.vaillant.com/mobile/api/v4/facilities/2*************4/systemcontrol/v1/dhw/Control_DHW/hotwater/configuration`
`{“body”:{“operation_mode”:“AUTO”,“temperature_setpoint”:57.0}`

**I find my actual T°c :** 
`https://smart.vaillant.com/mobile/api/v4/facilities/2*************4/livereport/v1`
`{"unit":"°C","name":"Température de l'ECS du ballon","value":54.0,"_id":"DomesticHotWaterTankTemperature" `

But I can't find ' low setpoint ' ?
also for ECS,
it is possible to know the times when it works thanks to the calculation with programming schedules

but isn't there an information (state) that indicates it directly?

_you talk about it in an excerpt_
```
        !! It could be misleading here, since when heater is not heating,
        target temperature if fixed (35 °C) - The API doesn't allow to change
        this setting. It means if the user wants to change the target
        temperature, it will always be the target temperature when the
        heater is on function. See example below:

        1. Target temperature when heater is off is 35 (this is a fixed
        setting)
```

I know : 

- /systemcontrol/v1/dhw/Control_DHW/circulation
- /systemcontrol/v1/dhw/Control_DHW/circulation/configuration
- /systemcontrol/v1/dhw/Control_DHW/circulation/configuration/timeprogram

- /systemcontrol/v1/dhw/Control_DHW/hotwater
- /systemcontrol/v1/dhw/Control_DHW/hotwater/configuration
- /systemcontrol/v1/dhw/Control_DHW/hotwater/configuration/operation_mode                  **Erreur 405**
- /systemcontrol/v1/dhw/Control_DHW/hotwater/configuration/temperature_setpoint         **Erreur 405**
- /systemcontrol/v1/dhw/Control_DHW/hotwater/configuration/timeprogram                       **Erreur 404**

MErci pour votre aide :)

**Comment by thomasgermain** [comment]
Hello,

sorry for the late reply.

There is no way to set low setpoint for hotwater.  Normally, the app of the VRC700 should only allow you to set target temperature from 35 to 70.

**Comment by bloug30** [comment]
Sorry I worded my request badly,

I don't want to ""**set**"" low/high points ,  I want to " **get**"  values  high / low and also "get" value if the ECS is in a heating state or standby

**Comment by thomasgermain** [comment]
Ah I see, there is no perfect way to do it.

There is no way to get it directly. You have to get the timeprogram for the hot water and for each timeframe you have the start time and the target temperature. So based on the current time you can find the right timeframe and you have to target temperature.

**Comment by bloug30** [comment]
I see there is therefore nothing next to the API.
I also calculate like this because (fortunately) I have a simple schedule.

I close ticket. :)

**Thank you again and happy holidays to you and your loved ones!**
