### ISSUE TITLE
Request: Retrieve all status codes

### ISSUE THREAD

**Issue by barryward-wrd** [thomasgermain/vaillant-component#180]
Would it be possible to retrieve all of the status codes from the Boiler? I would like to be able to detect short cycling of the boiler ie S.24 and S.04. alternatively is there a simple way I could implement this myself via a python change?

Thanks for all your hard work.

Barry

**Comment by thomasgermain** [comment]
Hello,

depending on your type of boiler, there is a binary sensor with the name of your boiler, something like `binary_sensor.vc_be_246_5_3` which is `on` in case of error. In this entity, there is an attribute `Status code` which is the status code you want and `title`, which is a description of the status code

**Comment by barryward-wrd** [comment]
Thanks Thomas, this is exactly the function I was looking to use however the extended attributes are only present when the fault code is not a status code. (!=“STATUS” in the pymultimatic mapper.py) I would like to be able to read and store the current status codes.

Thanks in advance

Barry Ward

Sent from my iPhone

On 5 Jan 2023, at 08:11, Thomas Germain ***@***.***> wrote:

﻿

Hello,

depending on your type of boiler, there is a binary sensor with the name of your boiler, something like binary_sensor.vc_be_246_5_3 which is on in case of error. In this entity, there is an attribute Status code which is the status code you want and title, which is a description of the status code

**Comment by thomasgermain** [comment]
Attributes are always present.

There are two different kind of messages coming from the API:
- STATUS: it depends on the kind of boiler, it gives the status of the boiler
- ERROR: it gives the error coming from any kind of device (boiler, VR920, etc).

In case of ERROR, this is also a `binary_sensor.multimatic_errors`, which is on when ERROR message is coming from the API. In that case, there is also `Status Code` and `title` for each error

**Comment by barryward-wrd** [comment]
Ah I see. I don’t have a device for binary_sensor.“boilername” I only have binary_sensor.multimatic_errors. I’m not sure what I need to do to get the other device to be present.

I’m happy to share any details you need if you could help out.

Many thanks.

Barry Ward

Sent from my iPhone

On 5 Jan 2023, at 09:13, Thomas Germain ***@***.***> wrote:

﻿

Attributes are always present.

There are two different kind of messages coming from the API:

  *   STATUS: it depends on the kind of boiler, it gives the status of the boiler
  *   ERROR: it gives the error coming from any kind of device (boiler, VR920, etc).

In case of ERROR, this is also a binary_sensor.multimatic_errors, which is on when ERROR message is coming from the API. In that case, there is also Status Code and title for each error

**Comment by thomasgermain** [comment]
The binary_sensor."boilername" is only available if there is a `STATUS` message in the API.

I guess it depends on the boiler type, some users of the integration reported to have while other users don't

**Comment by barryward-wrd** [comment]
It seems very strange in my case as sometimes I get temperature and status and other times are do not and they are unavailable



On 9 Jan 2023, at 13:53, Thomas Germain ***@***.***> wrote:



The binary_sensor."boilername" is only available if there is a STATUS message in the API.

I guess it depends on the boiler type, some users of the integration reported to have while other users don't

**Comment by thomasgermain** [comment]
Do you have any error in the log ? Most of the time this happens because the API is not available
