### ISSUE TITLE
Unable to load integration after core upgrade to latest

### ISSUE THREAD

**Issue by TonyJr1** [thomasgermain/vaillant-component#187]
After upgrading core, now current versions are:
`Home Assistant 2023.1.6
Supervisor 2022.12.1
Operating System 9.4
Frontend 20230110.0 - latest`

Two error messages:
Logger: homeassistant.setup
Source: setup.py:202
`Setup failed for custom integration multimatic: Requirements for multimatic not found: ['pymultimatic==0.6.7']`

Logger: homeassistant.util.package
Source: util/package.py:98
`Unable to install package pymultimatic==0.6.7: ERROR: Cannot install pymultimatic==0.6.7 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts [notice] A new release of pip available: 22.3 -> 22.3.1 [notice] To update, run: pip install --upgrade pip`

The integration remains in a Not Loaded state.

**Comment by thomasgermain** [comment]
Please, use version 1.12.12
