### ISSUE TITLE
How to set duration for quick veto?

### ISSUE THREAD

**Issue by hvbargen** [thomasgermain/vaillant-component#191]
Note: I am using VR921 and Xavier Griffons PR.

If I rotate the temperature wheel in the HA UI,  this works:
I can see in the SensoComfort that the target temperature is changed per quick veto for 6 hours.

How can I configure this duration?

BTW If I try to call the service set_quick_veto manually, this results in an error message:

Unexpected error for call_service at pos 1: Cannot put https://smart.vaillant.com/mobile/api/v4/facilities/.../systemcontrol/tli/v1/zones/Control_ZO1/configuration/quick_veto, status: 400, response: {"errorCode":"INVALID_PARAMS"},payload: {'temperature_setpoint': 22.0, 'duration': 60.0}
![image](https://user-images.githubusercontent.com/37015738/216830375-d9e475ca-b1a5-4e94-a820-d901ea3bee50.png)

**Comment by hvbargen** [comment]
@xaviergriffon  Regarding the how-to-set question: It seems that the 6 hours is hard-wired in coordinator.py line 254:

veto = QuickVeto(6, target_temp)

Can we make this configurable somehow?

**Comment by xaviergriffon** [comment]
Good test!
There is a unit conflict between Multimatic and Senso. For Senso, the unit is in hours.
We will have to adapt the controls according to the application.

For the default duration parameter, I think it should be set in the configuration as for the number of minutes between refreshes.

**Comment by hvbargen** [comment]
Yeah, that sounds reasonable.

**Comment by xaviergriffon** [comment]
I pushed a correction on my branch.
You need to re-download the addon and after restarting, check the commit.
<img width="353" alt="Capture d'écran 05 02 2023 à 19 20 55 PM" src="https://user-images.githubusercontent.com/5923066/216837755-cc2fe2d9-4a46-450a-a1ef-46776c0848a7.png">

<img width="387" alt="Capture d'écran 05 02 2023 à 19 22 51 PM" src="https://user-images.githubusercontent.com/5923066/216837758-006b0e4b-9752-43b0-85a1-f315030ca28a.png">

**Comment by hvbargen** [comment]
On my SensoComfort, the default duration is 3h.
