### ISSUE TITLE
Control the offset temperature to use cheeper energy prices or photovoltaics 

### ISSUE THREAD

**Issue by kirk-loeten** [thomasgermain/vaillant-component#198]
The instruction of the VR920 describes the implementation of a SMA to lift the warm water temperature by an offset.

I use [tibber](https://tibber.com) as energy provider with hourly changing prices. So I am able to control the wallbox and start it automatically if the price is low. Now I like to control the heating system in the same way.

Do you know someone with this components (SMA, energiemanagement, ... ) for reengineering?

**Comment by thomasgermain** [comment]
I never dug the photovoltaics part and I didn't find anything related to SMA. But I will definitely have a look at it.

Could it be that this is related to EEBUS ? 

Could you check your link, it seems dead ?

Maybe you can ask here: https://community.home-assistant.io/t/vaillant-multimatic-integration/87240 if somebody has such configuration

**Comment by kirk-loeten** [comment]
I have a VRC 700 / 2. The VRC 700 / 5 is the first generation with EEBUS. I have to change the VRC.  

[PDF Manual for Vaillant VR920 DE FR IT](www.vaillant.de/documents/download/369502)

**Comment by kirk-loeten** [comment]
I think this problem could not fix with the data from the app and EEBUS is not a part of your project.

**Comment by kirk-loeten** [comment]
In my chase I need the VR920 and i have the VR900. I tested the service "Water_Heater.Set temperature" and it works fine. Now I try to set the Temperatur for the heater with quick veto.

**Comment by kirk-loeten** [comment]
In my chase I need the VR920 and i have the VR900. I tested the service "Water_Heater.Set temperature" and it works fine. Now I try to set the Temperatur for the heater with quick veto.

**Comment by kirk-loeten** [comment]
In my chase I need the VR920 and i have the VR900. I tested the service "Water_Heater.Set temperature" and it works fine. Now I try to set the Temperatur for the heater with quick veto.
