### ISSUE TITLE
hvac modes

### ISSUE THREAD

**Issue by rhgiter** [thomasgermain/vaillant-component#204]
Thanks for this add on :-) 

how do I make hvac modes ?

**Comment by thomasgermain** [comment]
Hello,

You mean changing the hvac mode ? You can do it through the climate entity.
There is no way to create new hvac mode and available hvac mode are configured in the integration. Do you need a new one ?

**Comment by rhgiter** [comment]
Maybe I cant understand what hvac modes are for 

ex. "KOMFORT" I would like 20 degress and "UDE" 20 degress 

![image](https://github.com/thomasgermain/vaillant-component/assets/61065752/8a7537aa-b55f-4f55-9f48-ba333445b9f6)

**Comment by thomasgermain** [comment]
Yeah havac mode and preset mode are not so intuitive. 
Here is the doc: https://developers.home-assistant.io/docs/core/entity/climate/#hvac-modes and https://developers.home-assistant.io/docs/core/entity/climate/#presets

In the integration, there are 2 hvac modes: OFF and AUTO (this is the first dropdown, "drifttype"). I can't add any hvac modes.
There are also preset modes,  to me, there is no real difference with hvac modes. They basically match what you can do with the mobile app. You can check here https://github.com/thomasgermain/vaillant-component#expected-behavior (Modes mapping) how the integration reacts and what the integration does when changing preset mode and hvac modes
