### ISSUE TITLE
Multimatic is not loading after HA update 

### ISSUE THREAD

**Issue by michalkruczek** [thomasgermain/vaillant-component#205]
Hi' after last update to HA:
Home Assistant 2023.5.4
Supervisor 2023.04.1

Bellow error occured:

`Setup failed for custom integration multimatic: Unable to import component: cannot import name 'ApiError' from 'pymultimatic.api' (/usr/local/lib/python3.10/site-packages/pymultimatic/api/__init__.py`

**Comment by thomasgermain** [comment]
Hello,

which version of the integration are you using ?

I just had a try with 2023.5.4, and the integration is loading correctly

**Comment by michalkruczek** [comment]
Hi, Thomas. I'm using current version 1.14.0 of this integration - installed via HACS.

**Comment by mike4001** [comment]
1.14.0 couldn't be installed because it required Home Assistant 2023.6.0. If you click install it fails.

1.13.0 works fine for 2023.5.4

Not since about an hour 2023.6.0 is released and I could also update to MultiMatic Integration 1.14.0 without any problems

**Comment by thomasgermain** [comment]
Thanks for your feeback @mike4001 

@michalkruczek do you have any other error in your log ? How are you running HA (OS, docker, etc) ? Which version of python are you using ?

**Comment by antonclaeys** [comment]
I'm running 2023.6.1, want to do a new install of MultiMatic (1.14) and when I try to add it, it keeps loading on "Please wait, starting configuration wizard for multimatic"

**Comment by thomasgermain** [comment]
> I'm running 2023.6.1, want to do a new install of MultiMatic (1.14) and when I try to add it, it keeps loading on "Please wait, starting configuration wizard for multimatic"

Please create a separate issue, since it doesn't seem to be the same problem as the one describe in this issue. (And please provide your logs, if there is any error)
