### ISSUE TITLE
Hot Water Implementation faulty

### ISSUE THREAD

**Issue by mike4001** [thomasgermain/vaillant-component#207]
Hi,

I am using your integration basically without any problems but one point -> Hot Water Temperature is just not working. It shows the wrong value and is not changeable.

![image](https://github.com/thomasgermain/vaillant-component/assets/26521177/3a68d6d2-e284-46a7-9005-20947be5a0ce)

It shows 35°C (Though 50 °C is set in the original Vaillant app or the control panel in my building).

If I want to change the setting I get the Error message

`Cannot put https://smart.vaillant.com/mobile/api/v4/facilities/21221800202609620938024712N9/systemcontrol/v1/dhw/Control_DHW/hotwater/configuration/temperature_setpoint, status: 400, response: {"errorCode":"INVALID_PARAMS"},payload: {'temperature_setpoint': 36.5}`

**Comment by thomasgermain** [comment]
Hello,

35 as target temperature is normal. I read somewhere in the doc that it was the minimal target temperature. If you check your history, target temperature should change from 35 to 50 and vice versa according to your configured schedules.

What version of the integration are your running ? And also, is it multimatic or senso ?

**Comment by mike4001** [comment]
Ah, OK I see now.

At the moment I am set to Auto (= Off at 22:26) so I see 35 °C. If I set it to manually On it changes to my desired temperature of 50 °C.

1) It´s a little bit confusing because when changing the value I am always changing the On value but it still displays only 35 °C because I am currently in Off Mode.
2) The Error message comes from the fact the .5 °C changes are not possible. So I can set it to 49 / 50 / 51 °C but not 49,5 °C. These give the Error message above and nothing happens.

Actually both 1) and 2) are not optimal. Don't know if they are possible to fix :-)

I am running the latest 1.14.0 with multimatic

**Comment by thomasgermain** [comment]
> 1. It´s a little bit confusing because when changing the value I am always changing the On value but it still displays only 35 °C because I am currently in Off Mode.

Yes I agree, this is confusing. This is because of 2 things:
- the target temperature changes in HA, in AUTO mode so HA can detect that the water heater is heating
- There is no quick veto for water heater and the only configurable target temperature is the setpoint temperature (=target temperature when schedule is ON in AUTO mode).
-> I'm open to any suggestion for it to be more user friendly

> 2. The Error message comes from the fact the .5 °C changes are not possible. So I can set it to 49 / 50 / 51 °C but not 49,5 °C. These give the Error message above and nothing happens.

Nice catch, I'll provide a fix

**Comment by thomasgermain** [comment]
version 1.14.1 is out with the fix ;)

**Comment by mike4001** [comment]
Thank you. No Error message anymore.

Regarding 1)

For me it would be perfect if I only see the on-value (= 50°C in my case) even if I am in Off (or Auto-Off) mode, but I assume this is not possible because the control reports 35 °C.

If I understand it correctly these 35 °C do not really exist (I do not see them in the official App or wall mounted control anywhere). It´s just that the control reports the minimum number = 35 °C when in Off-Mode. But it would not even heat to these 35 °C even it the actual temperature would be lower.
