### ISSUE TITLE
Banned by Vaillant

### ISSUE THREAD

**Issue by Acey-yo** [thomasgermain/vaillant-component#209]
Hello everyone,

I haven't gotten into the app and HomeAssistant integration for weeks.
Now I have written to the Vaillant App Support and it turned out that they blocked me with the reason that I use third-party software and they asked too often where the block came from.
They now unlock me again, with the statement that I can only use the official app, otherwise they will block me permanently.
Does anyone have experience with this or is it possible to lower the integration query rate?

Thx Toby

**Comment by mike4001** [comment]
My Integration also stopped working since about 2 hours ago.

But I cannot say if just the servers don't work at the moment.

I will wait until tomorrow and then contact Vaillant.

@Acey-yo How did you know that you were banned in the first place?

**Comment by thomasgermain** [comment]
Hello,

I'm not aware of anybody getting blocked by vaillant support for using the integration.

You can configure the refresh interval of the integration: parameters>integrations>multimatic>the cog>configure and you can set the refresh interval. My integration refreshes every minute and I don't have any issue with the support

Vaillant server have been down for 2h today, between from 3:20 to 5:20pm approximately

**Comment by Acey-yo** [comment]
> My Integration also stopped working since about 2 hours ago.
> 
> But I cannot say if just the servers don't work at the moment.
> 
> I will wait until tomorrow and then contact Vaillant.
> 
> @Acey-yo How did you know that you were banned in the first place?
> 
> EDIT: It´s back working for me for now. Seems to just have been a server-side issue. But just to be safe I adjusted my poll rate from 3 minutes to 10 minutes :-)

Hey,

wie schon oben gesagt, hatte ich seid Wochen das Problem mich nicht mehr ein loggen zu können. Dann habe ich dem Vaillant Support geschrieben und die sagten es mir dann. 
Aber es kam keine Email, Meldung oder gar etwas schriftliches.

**Comment by Acey-yo** [comment]
> Owner

Ah yeah....sry. Thx u

**Comment by igd001** [comment]
My

**Comment by igd001** [comment]
Solved by Vaillant support!!
