### ISSUE TITLE
Error in integration procedure

### ISSUE THREAD

**Issue by josepolost** [thomasgermain/vaillant-component#210]
I have installed de library by HACS and when I try to setup the integration module appears the following error:
<html> <head><title>504 Gateway Time-out</title></head> <body> <center><h1>504 Gateway Time-out</h1></center> <hr><center>nginx</center> </body> </html> 
I have installed the last version of  HA.

THank you for your support.

**Comment by thomasgermain** [comment]
Where did this error appear ?

Do you have any error in the logs ?

**Comment by josepolost** [comment]
Hi,
When I try to setup the integration.
[image: imatge.png]
It takes a lot of time and appears:
[image: imatge.png]

The information of the log is:

Logger: frontend.js.latest.202306080
Source: components/system_log/__init__.py:257
First occurred: 24 de juny de 2023, a les 20:12:38 (3 occurrences)
Last logged: 11:09:08

blob:https://ha.perguardar.cat/db322982-5619-403e-8b35-f12f72f86cda:1:100
ReferenceError: t is not defined
blob:https://ha.perguardar.cat/f7deba9c-3f6d-4640-9866-7a7e4bbe0e69:1:100
ReferenceError: t is not defined
blob:https://ha.perguardar.cat/c18781f9-8ccb-4b45-9a6e-f8e70feb470d:1:100
ReferenceError: t is not defined

Best regards,
Josep

Missatge de Thomas Germain ***@***.***> del dia dl., 26 de
juny 2023 a les 11:06:

**Comment by josepolost** [comment]
Hi,
After **_ha host reboot_** from console the integration work fine.
Thank you for your support
