### ISSUE TITLE
Entities not visible in default dashboard

### ISSUE THREAD

**Issue by zolakt** [thomasgermain/vaillant-component#219]
Sorry if this is a stupid question, but I can't see it mentioned anywhere.

Everything seems to work fine for me with a VR71 and a VR921.
I can see 16 entities. All seem to work.

However none of these entities get added to the default (auto generated) dashboard.
Is this expected?

This is the first time this has happened to me. Usually, all other entities get added there, unless I manually hide them.

I haven't taken manual control of the dashboard. If I add some other entities (e,g, through zha), they get added to the default dashboard. But the Vaillant ones are still missing.

UPDATE: Actually, the 2 climate cards for 2 zones (the ones that aren't part of any device) do show up, but the other 14 don't.
![image](https://github.com/thomasgermain/vaillant-component/assets/1048531/91507746-feb6-4670-80e3-f2236794c113)

**Comment by thomasgermain** [comment]
Hello,

Actually this is something I never tested, because I switch lovelace to manual mode.

Does it mean you cannot add other entities to your dashboard ?

**Comment by zolakt** [comment]
No, you can add all of them to a manual dashboard normally.
For the autogenerated, there is no option to add. It should just add everything automatically.

**Comment by zolakt** [comment]
I figured it out.

You define all of these sensors with EntityCategory.DIAGNOSTIC, which hides them from the autogenerated dashboard and voice assistants.

Could you change this for at least the "Outside temperature"?

Although I don't see the harm of exposing all of them, since you can always hide the ones you want with the Visibility setting

**Comment by thomasgermain** [comment]
Hello, version 1.15.1 should allow you to see more entities.

Could you confirm ?
