### ISSUE TITLE
Problem with HA 2023.09

### ISSUE THREAD

**Issue by 4ib3r** [thomasgermain/vaillant-component#220]
Hello, I have version 1.14.3 of component and after update home assistant to version 2023.9 i get error:
```
Logger: homeassistant.util.package
Source: util/package.py:108
First occurred: 22:39:04 (1 occurrences)
Last logged: 22:39:04

Unable to install package pymultimatic==0.7.0: ERROR: Cannot install pymultimatic==0.7.0 because these package versions have conflicting dependencies.
```

**Comment by avhove** [comment]
Same issue here!

**Comment by mf76130** [comment]
Logger: homeassistant.util.package
Source: util/package.py:108
First occurred: 05:49:27 (3 occurrences)
Last logged: 05:50:12

Unable to install package pymultimatic==0.7.0: ERROR: Cannot install pymultimatic==0.7.0 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts [notice] A new release of pip is available: 23.1.2 -> 23.2.1 [notice] To update, run: pip install --upgrade pip

**Comment by mf76130** [comment]
Wow superfast, here comes an update for Multimatic - lets hope it fixes it

**Comment by mf76130** [comment]
after the update multimatic blocks the reboot:
Integration error: multimatic - Requirements for multimatic not found: ['pymultimatic==0.7.0'].

**Comment by mf76130** [comment]
i can't even delete the integration, its just not doing it

**Comment by megabyte0469** [comment]
Same issue here

**Comment by mf76130** [comment]
i removed the entry for the multimac from the configuration yaml, that let me uninstall it and now no errors anymore at least

**Comment by mike4001** [comment]
I do not see any update?

And of course with the same error as postet in the first post

```
Logger: homeassistant.util.package
Source: util/package.py:108
First occurred: 07:49:25 (3 occurrences)
Last logged: 07:49:52

Unable to install package pymultimatic==0.7.0: ERROR: Cannot install pymultimatic==0.7.0 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts [notice] A new release of pip is available: 23.1.2 -> 23.2.1 [notice] To update, run: pip install --upgrade pip
```

```
Logger: homeassistant.setup
Source: setup.py:209
First occurred: 07:49:52 (1 occurrences)
Last logged: 07:49:52

Setup failed for custom integration multimatic: Requirements for multimatic not found: ['pymultimatic==0.7.0'].
```

**Comment by mf76130** [comment]
the update is 5 days old, didn't see that before, maybe you have it already installed

**Comment by mike4001** [comment]
> the update is 5 days old, didn't see that before, maybe you have it already installed

Yes, I already had that.

So we have to wait for @thomasgermain :-)

**Comment by ralphbk** [comment]
No. The problem arrived with yesterday's HA 2023.09, and the Multimatic 1.14.2 release from Aug 5 does not fix it.

**Comment by Presl1983** [comment]
same here :(

**Comment by lennartjung** [comment]
+1

**Comment by Vato9394** [comment]
+1

**Comment by MisfitPunisher** [comment]
Same here.

**Comment by sipi58** [comment]
Same issue here.

**Comment by hvbargen** [comment]
I think one solution would be to remove and reinstall the integration.

But then I fear that many sensors will be renamed and all my automations/dashboards etc don't work anymore.

So is there any chance to
- either backup the configuration, reinstall, then restore the configuration
- or solve the dependency issue without reinstalling?

**Comment by Presl1983** [comment]
i can't remove the integration but i can remove it... but it's not possible to install because the integration is configured already....

**Comment by thomasgermain** [comment]
Version https://github.com/thomasgermain/vaillant-component/releases/tag/1.14.4 should fix the issue.

Problem was coming from undocumented breaking change

**Comment by ralphbk** [comment]
That fixed it. Thanks @thomasgermain

**Comment by sipi58** [comment]
Excuse me, how can I install it if it doesn't show up in HA as an update?

**Comment by ralphbk** [comment]
> Excuse me, how can I install it if it doesn't show up in HA as an update?

You can manually trigger the update. https://hacs.xyz/docs/basic/updates/

**Comment by sipi58** [comment]
Thank you, I found manually update trigger and I updated it and it fixed the problem. Many thanks.

**Comment by lennartjung** [comment]
> 

thanks for your quick fix, enjoy your next 5 coffees ;)

**Comment by mike4001** [comment]
> > 
> 
> thanks for your quick fix, enjoy your next 5 coffees ;)

Why not

Make that 2 more :-)

**Comment by thomasgermain** [comment]
Well, since it's Friday, I will enjoy a beer 🍺 😋.

Thanks ☺️
