### ISSUE TITLE
multimatic error

### ISSUE THREAD

**Issue by sipi58** [thomasgermain/vaillant-component#221]
Hello,
I use multimatic integration with my Vaillant boiler.

I updated the HA this morning to HA Core 2023.9.0 and multimatic integration does not work. I received the error message :

Invalid config
The following integration and platforms could not be set up:
- multimatic

I found this message in the log:

Home Assistant Core
Setup failed for custom integration multimatic: Requirement for multimatic not found: ['pymultimatic==0.7.0'].
Error setup.py

Unable to install package pymultimatic==0.7.0: Error: Cannot install pymultimatic==0.7.0 because these package version have conflict dependencies. Error: ResolutionImpossible

I tried ro run “pip install --upgrade pip” command but “pip command not found”.

What can I do to solve problem?

Thanks for your help.

**Comment by bartverckens** [comment]
I have same issue.

**Comment by Vato9394** [comment]
Duplicate #220
