### ISSUE TITLE
Unable to install package pymultimatic

### ISSUE THREAD

**Issue by Krzysztonek** [thomasgermain/vaillant-component#225]
![obraz](https://github.com/thomasgermain/vaillant-component/assets/87784133/b1316323-b2b0-4f49-ad00-d7f1e385c04e)

From couple of days I get following error:
```
Logger: homeassistant.util.package
Source: util/package.py:108
First occurred: 13:12:05 (3 occurrences)
Last logged: 13:13:11
Unable to install package pymultimatic==0.7.0: ERROR: Cannot install pymultimatic==0.7.0 because these package versions have conflicting dependencies. ERROR: Resolution Impossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts [notice] A new release of pip is available: 23.1.2 -> 23.2.1 [notice] To update, run: pip install --upgrade pip
```
After performing the upgrade:
![obraz](https://github.com/thomasgermain/vaillant-component/assets/87784133/8679a4a9-30d4-4e7e-99c9-2e604fb8d026)
nothing happens, The integration still doesn't work and remains as not read. Reloading option is also not available.

**Comment by thomasgermain** [comment]
Hello, 

See https://github.com/thomasgermain/vaillant-component/issues/220#issuecomment-1711146993

**Comment by Krzysztonek** [comment]
Thank you, I found manually update trigger and it fixed the problem. Many thanks.
