### ISSUE TITLE
Authentication failed

### ISSUE THREAD

**Issue by anthurta** [thomasgermain/vaillant-component#226]
Hello, 

I am trying to login with my device, but I always get this error:

Authentication failed, check your username and password and make sure you selected the right country and device brand

In the logs I can see this:

`2023-09-28 13:35:29.115 ERROR (MainThread) [homeassistant] Error doing job: Unclosed client session
2023-09-28 13:35:29.116 ERROR (MainThread) [homeassistant] Error doing job: Unclosed connector`

I tried with other Addons and works perfectly (and with the SenseApp as well).

Any idea what is happening?

**Comment by thomasgermain** [comment]
Hello,

do you have any errors related to the integration ?

What do you mean by "you tried with other addons" ?

**Comment by anthurta** [comment]
Hello,

Sorry for the late response.

I don't see any errors related to the integration apart of the two mentioned above (that I think are related to it). Is there anything else I can do to activate debug log level that can help?

Other addons: there is another addon (multimac) that works in terms of the login phase (same with SenseApp). 

Thanks

**Comment by anthurta** [comment]
Now seems to be working fine. Thanks
