### ISSUE TITLE
authentication error (user created via myVaillant app)

### ISSUE THREAD

**Issue by yojoe** [thomasgermain/vaillant-component#229]
I created a user account via the `myVaillant` app, seems like the `sensoApp` and `multimaticApp` are deprecated now!? At least in Germany, as there is a help article in German talking about a forced upgrade and migration of users to `myVaillant`: https://vaillant.helpjuice.com/de_DE/produkte/warum-muss-ich-auf-die-myvaillant-app-wechseln

However, I always get an authentication error in Home Assistant:
```
This error originated from a custom integration.

Logger: custom_components.multimatic.config_flow
Source: custom_components/multimatic/config_flow.py:90
Integration: Multimatic (documentation, issues)
First occurred: 12:12:11 (14 occurrences)
Last logged: 13:05:34

Unable to authenticate: Cannot get token at https://smart.vaillant.com/mobile/api/v4/account/authentication/v1/token/new, status: 401, response: {"errorCode":"NOT_AUTHORIZED"}
```

So it looks like user accounts registered through the `myVaillant` app can't authenticate via the `https://smart.vaillant.com/mobile/api/v4/account/authentication/v1/token/new` interface. If I try to register an account through the "old" `sensoApp`, I get an error that my sensoNet gateway is already associated with another account. So it seems like once your system is setup/migrated to the new `myVaillant` backend, you can't use this HA integration anymore?

**Comment by thomasgermain** [comment]
Yeah myVaillant and multimatic/senso are definitely something different.

So once you migrated, you can't access multimalic or senso (and thus, you can't use this integration anymore).

I guess there is already an integration for myVaillant. I'm planning to do one, but it depends when I will (and if I ever will) be migrated to myVaillant and if there is already a good integration or not for myVaillant.
