### ISSUE TITLE
See the gas consumption

### ISSUE THREAD

**Issue by nyunity** [thomasgermain/vaillant-component#236]
Hi, 

first of all, thx for this sweet integration. At my terminal in front of the machine, I can see the total gas consumption in kW. Is it possible to get this value into Home Assistant to? 

Its possible to get this value with the EBUS?

thx
Erik

**Comment by thomasgermain** [comment]
Hi, thanks for the feedback 👍.

Are you able to see the consumption in the mobile app ? If yes, it should be visible in the integration already.

If this is visible on the device, there is a chance it can be available through EBUS

**Comment by nyunity** [comment]
Unfortunaly not. May I need the sensocomfort 720? At the Moment I have the VRC 921 Module with the vrc 700/5. Green IQ is activated, but, I can only see three sensors in the sensoAPP, the same as I got in the homeassistent.

**Comment by thomasgermain** [comment]
Unfortunately, if you can't see it in the mobile app, there is no chance for it to be available in the integration.

I don't think another gateway or another thermostat will make more data available in the mobile app, I think this is a restriction from the boiler directly

**Comment by nyunity** [comment]
@thomasgermain thanks for your reply. I asked Vaillaint directly, no answert till now. My research results, that all boilers which are able to use "Green IQ", are available to make this data available.

I'll give you my feedback from vaillant.

have a nice weekend
