### ISSUE TITLE
Rücklauftemperatur

### ISSUE THREAD

**Issue by Horrido77** [thomasgermain/vaillant-component#241]
Hi, thanks for your great work. It is highly appreciated. The one thing I am missing though is an entity for the ˋRücklauftemperatur'. I wonder if that is at all possible? 

Thanks again!

**Comment by thomasgermain** [comment]
Hello, thanks for the feedback 👍.

Don't you have an entity with a name that looks like "flowtemperaturesensor" ?

Could you show me where in the app you can see this info ?

Thanks

**Comment by Horrido77** [comment]
Thanks for your reply. I do see the flowtemperaturesensor and it gives me the value for the Vorlauftemperatur. The Rücklauftemperatur is accesable on the Vaillant heater itself, but not on the MultiMATIC iOS app. It would be also,e, if there would be a way to show it within your integration.

Thanks again!

 ![image](https://github.com/thomasgermain/vaillant-component/assets/116354789/7794ee96-f25a-485a-9dcf-dc401aa00b7e) ![image](https://github.com/thomasgermain/vaillant-component/assets/116354789/90f4f7f8-f8df-43a0-9281-e82a6da6dbfb)

**Comment by thomasgermain** [comment]
Ah I see, unfortunately, if the information is not available on the mobile app, I can't get it in the integration 😕

**Comment by Horrido77** [comment]
Alright, I kind of suspected that but thought it was worth asking. Thanks for the quick reply though. Keep up the good work and take care.
