### ISSUE TITLE
No climate, thermostat or DHW entities

### ISSUE THREAD

**Issue by raenji-sk** [thomasgermain/vaillant-component#244]
Hi, we have a dual boiler setup and I can only see the following entities:
![image](https://github.com/thomasgermain/vaillant-component/assets/16104239/c9261e9e-0838-4edc-a464-4a03bceaf8e5)
There are no entities for climate for the two zone regulators or DHW.
Can something be done about it? Let me know if you need more information from me.
I tried to setup the integration as both SensoApp and Multimatic, with or without serial number but this is the best result I can get. Oh and it is a VR921 gateway.

**Comment by raenji-sk** [comment]
Update.
I created another Vaillant account and added one with Multimatic config to get the entities listed in first post. Second is configured as SesnoApp and that one gets climate and DHW control. No idea why it is like that. Also with just one account the system got confused and entities from Multimatic were lost after adding SensoApp and vice versa...
![image](https://github.com/thomasgermain/vaillant-component/assets/16104239/fb82116e-0f52-4e95-a00b-d2358f556d76)

**Comment by thomasgermain** [comment]
Hello,

Which version of the integration are you using ?

With VR921, you should probably use senso option in the integration. And you should only setup the integration once (either senso or multimatic), but not both at the same time.

You should also create a separate user for home assistant, vaillant API doesn't like to have the same user connected multiple times from different places.

Could you setup the integration accordingly to my recommendations and check if there is any errors in the log ?

**Comment by raenji-sk** [comment]
Thanks @thomasgermain , indeed using just Senso option without serial number now does show all entitie including climate and DHW. Not sure what was wrong with it before. I tried several time over the last few weeks and always got weird results. Perhaps something in the integration or API changed...


> You should also create a separate user for home assistant, vaillant API doesn't like to have the same user connected multiple times from different places.

I know, I read it somewhere in the comments. I do have separate accounts for all users + now 2 accounts for HA.

As for integration version I always use the latest one.

**Comment by thomasgermain** [comment]
It could be that you had error during the setup.

You will see that vaillant servers are sometimes unstable, which is causing some entities to be unavailable
