### ISSUE TITLE
Configurable zone quick veto duration

### ISSUE THREAD

**Issue by zolakt** [thomasgermain/vaillant-component#255]
Would it be possible to make the quick veto for a zone configurable, at least when you set it through a service?

I've seen it the docs that is says 6 hours for a zone, although on my VRC720 is sets it to 3 hours (that is the default when you set it on the VRC720 as well). That works better for me than 6, but still it would be really helpful to have control over this for automations.

When you do it on the VRC720 you can choose from 0.5 hours to 12 hours (in 0.5 hour intervals). 
When you do it from the sensoApp you can choose the exact time until you want the veto to last.
So it should be possible to do this, somehow, through the API, since their app supports it.

There are a lot of use cases where having this would be beneficial.
e.g. I have one thermostat for two floors. It is located on the top floor, while the bottom floor only has TRV thermostats. When the temperature on the TRV falls bellow the set-back temperature. I'd like to ramp up the heating for an hour, so it goes back up. 3 hours is way too much for this. I know I can do a workaround by running my own timer and removing the veto manually, but with a lot of TRVs this can become a mess. It would be much more elegant it the veto duration was configurable,

**Comment by thomasgermain** [comment]
You should be able to configure the duration when calling the `multimatic.set_quick_veto` service:
![image](https://github.com/thomasgermain/vaillant-component/assets/12560542/5acfd2c5-3f0a-4f16-883a-f59efa09fc4b)

When creating a quick veto through climate entity, this is 3 hours by default

**Comment by zolakt** [comment]
Ah, fantastic, thanks. I missed that service documentation.
Maybe if you have time update the readme docs. It is a little misleading there.
