### ISSUE TITLE
Add to official integration in HA or to HACS

### ISSUE THREAD

**Issue by pepsonEL** [thomasgermain/vaillant-component#26]
Hi.
Is any chance to add this to official integration HA or to HACS store ?

**Comment by thomasgermain** [comment]
The plan is the include the component directly inside official HA. But I would like first to have some input for the 1.4.0 version (with th cooling).

**Comment by pepsonEL** [comment]
Ahhhhh ok. I am waiting for it to add to official HA...

**Comment by thomasgermain** [comment]
So I'm closing since it's integrated with HACS as custom repo: https://hacs.xyz/docs/faq/custom_repositories/
