### ISSUE TITLE
After copy to custom_components no show in integration

### ISSUE THREAD

**Issue by pepsonEL** [thomasgermain/vaillant-component#27]
Hi. I copy directory villant to /config/custom_components , after that reboot HA . But after reboot no show this component in Home Assistant Integration. Why ?

**Comment by lecocqe** [comment]
Hi.

2 remarks:
1) in integrations you have to add a new one and choose the right one in the list.
2) if not in list, clear cache of browser  and try to add integration

best regards,

ELE

**Comment by pepsonEL** [comment]
ok thanks now works 👍

**Comment by johanvh83** [comment]
Had same issue clearing the cache of my browser solved the problem
