### ISSUE TITLE
Failing autentication after vaillant update

### ISSUE THREAD

**Issue by MisfitPunisher** [thomasgermain/vaillant-component#270]
The vaillant APP VRC700 is gone, and I must had to move to myVaillant.
I rebuild my password, and that is working right with the myVaillant APP, but does not work on the HA multimatic integration.

The returned error is the next: 

**2024-03-06 23:37:28.578 ERROR (MainThread) [custom_components.multimatic.config_flow] Unable to authenticate: Cannot get token at https://smart.vaillant.com/mobile/api/v4/account/authentication/v1/token/new, status: 401, response: {"errorCode":"NOT_AUTHORIZED"}**

More friends with this issue?

**Comment by lecocqe** [comment]
Multimatic component integration for HA not working anymore if you are migrated to myvaillant.
You have to use an other component. 

Best regards

**Comment by ralphbk** [comment]
I just received the invitation to update to the myVAILLANT app, and came to ask if I should expect problems. Now I have my answer. @thomasgermain Any chance there will be a fix for this before myVAILLANT becomes obligatory on 1.4.2024?

**Comment by ralphbk** [comment]
> Multimatic component integration for HA not working anymore if you are migrated to myvaillant. You have to use an other component.

What other component is that?

**Comment by lecocqe** [comment]
> What other component is that? [This one](https://community.home-assistant.io/t/myvaillant-integration/542610)?

yes, i think so

**Comment by thomasgermain** [comment]
Hello,

I made a communication here: https://community.home-assistant.io/t/vaillant-multimatic-integration/87240/562.

This integration will work until you migrate, after that you will have to switch to the new integration (it requires some maintenance, since the system is quite different from multimatic).

For now, ambisense it not yet integrated, but I'm busy with @signalkraft
