### ISSUE TITLE
Vsc Ecocompact 206/4-5 90  with multimatic 700 and VR920

### ISSUE THREAD

**Issue by pepsonEL** [thomasgermain/vaillant-component#28]
Hi
I have this boiler and additiona component as write in topic. On multimatic VR700 i see that is availeble information about consuption gas and energy W. Is any chance to also this info was send to home assistant ?

**Comment by thomasgermain** [comment]
Hello,

are you able to see these information through the multimatic app (android or ios) ?

**Comment by pepsonEL** [comment]
No on android i dont see. I see on multimatic VR700

**Comment by thomasgermain** [comment]
So unfortunately I can't do anything about that.

Maybe you can get some data from ebus directly, you can have a look here https://github.com/john30/ebusd-configuration (I think it requires some work to make it work, but this is a starting point).

**Comment by pepsonEL** [comment]
I write to vaillant and wait for any answear

**Comment by thomasgermain** [comment]
Well, I also wrote to vaillant (plenty of time) but I never got any answer (except acknowledgment of receipt)

**Comment by pepsonEL** [comment]
ehhh no good. :( no good manufacturer....
