### ISSUE TITLE
binary_sensor.vaillant_system_update   - It is update firmware ?

### ISSUE THREAD

**Issue by pepsonEL** [thomasgermain/vaillant-component#29]
Hi
For what is this sensor binary_sensor.vaillant_system_update ? It show me when is available update firmware ? But firmware for what ? VR920 or boiler VSC206/4-5 or for multimatic VR700 ? Thanks

**Comment by thomasgermain** [comment]
As far as I know, this is the firmware of the gateway, so the VR920 in  your case

**Comment by pepsonEL** [comment]
ok thanks

**Comment by pepsonEL** [comment]
And it is update automatically ?

**Comment by thomasgermain** [comment]
You have to do it through your mobile (But I own the system for 2 years now and I only had one update so far)
