### ISSUE TITLE
One binary sensor for all errors

### ISSUE THREAD

**Issue by pepsonEL** [thomasgermain/vaillant-component#31]
Hi
Now component generate each binary sensor for each error on boiler. But is any chance to change this in your component to generate one binary sensor which show all error in one ? becuase now i can not add sensors which now is no generated. I can add it to lovelace after create by component and when is available on boiler. This is no good,

**Comment by thomasgermain** [comment]
Hi, 

Actually, errors coming from the API are not always related to the boiler.

Don't you have already a `binary_sensor.vaillant_<boiler model>`entity ? This binary sensor is giving the status of the boiler.

This is a legit suggestion. I will investigate a solution, but I don't want to have duplication between this new binary sensor and the `binary_sensor.vaillant_<boiler model>`.

Thanks for your input

**Comment by pepsonEL** [comment]
No i dont have this binary sensor. Look i have only this:
![vaillant](https://user-images.githubusercontent.com/71824185/99196249-7dd54b80-278b-11eb-9556-2205dc87ab8f.jpg)
My boiler mode is VSC206/4-5

**Comment by thomasgermain** [comment]
you can check release https://github.com/thomasgermain/vaillant-component/releases/tag/1.5.0b1 (please note, there are plenty of breaking changes)

**Comment by thomasgermain** [comment]
Hi @pepsonEL, is it ok for you ?

**Comment by pepsonEL** [comment]
form me works ok. I dont have any problem.
Only which found by some some time show me in HA my model boiler but now not show this sensor. No available....
