### ISSUE TITLE
Feature: Add a way to set DAY/NIGHT level for ventilation

### ISSUE THREAD

**Issue by apfelmaennchen** [thomasgermain/vaillant-component#33]
I managed to connect my RecoVair ventilation system with the VR32 bus connector to the ebus.
I can now steer the ventilation via the app. Unfortunately  there seems to be no parameter for configuring the bypass function, just ventilation levels for day and night timer program and ventilation boost as quick mode.
I attached the [system.json.txt](https://github.com/thomasgermain/vaillant-component/files/5684657/system.json.txt) which shows the relevant data in case you want to include ventilation in the component.

**Comment by thomasgermain** [comment]
Thanks for the input. Just to be sure, what are you able to do with the mobile app ? 
As far as I can see, only set night/day level and operating mode, something else ?

**Comment by thomasgermain** [comment]
you can check release https://github.com/thomasgermain/vaillant-component/releases/tag/1.5.0b1 (please note, there are plenty of breaking changes).

Fan/ventilation is untested, since I don't have any compatible device. As far as I know, you will only be able to change speed (switching operating mode to `DAY` or `NIGHT`) and turn off (operating mode `OFF`) and turn on (operating mode given in parameter: `DAY` or `NIGHT`)

**Comment by apfelmaennchen** [comment]
The app lets me set the mode to Auto, Day, Night. You can define Day and Night fan levels between 0 and 6. You can define the individual Day and Night intervals for Monday-Sunday. And I believe there is a quick-mode "burst ventilation" which puts the fan on level 6 for half an hour or so. 

I have installed 1.5.0b1 on a clean system. The component works, but there is no separate ventilation entity showing up. In the app ventilation is pretty much handled the same way as hotwater or circulation, so I would have expected a separate entity in homeassistant as well.

The climate devices (zone-1 and zone-2) now have an operating mode Auto, Fan only and Off. There as the app offers Auto, Day, Night and Off.

**Comment by thomasgermain** [comment]
ah damned.. I forgot to add the fan platform setup :facepalm: 

It should be fine with https://github.com/thomasgermain/vaillant-component/releases/tag/1.5.0b2

**Comment by apfelmaennchen** [comment]
The ventilation entity shows up now, but if I try to set it e.g. to NIGHT, I get an error message:
`Failed to call service fan/turn_on. set_fan_operating_mode() missing 1 required positional argument: 'mode'`

I checked with the developer tools, but it seems that the according fan-service is not registered/ available in home assistant.

**Comment by thomasgermain** [comment]
Ah yeah, apparently, you can turn on the fan without specifying any speed. I'll set `AUTO` by default is there is no speed specified. 

`fan.turn_on` is a built in home assistant service, so I think it should be available by default.

**Comment by apfelmaennchen** [comment]
Yes you are right, it is a built in default service, but in the developer tools is called generically `homeassistant.turn_on` as you can apply to different entity types. I have overlooked that, searching for `fan.turn_on`.

The problem with the `missing 1 required positional argument` is caused by a missing `self` in the set_fan_operating_mode() call in fan.py:

`self.coordinator.set_fan_operating_mode(self, OperatingModes.get(speed.upper())`

After fixing this, the fan integration works as desired!

I wonder if we could define DAY and NIGHT fan levels (0-6) via home assistant, as it is possible via the app - may by adding an additional service?

**Comment by apfelmaennchen** [comment]
One more thing: It is not possible to turn the ventilation OFF.
The app only allows AUTO, DAY, NIGHT as operating modes. Other operating modes cause an error message.
I have removed OFF as an operating mode (speed), but cannot get rid of the on/off switch of the fan entity.

**Comment by thomasgermain** [comment]
What modes (other than DAY, NIGHT, AUTO and OFF) would you expect ?

What do you mean by it's not possible to turn off ?

I can add a way to configure the level for DAY and NIGHT with a service. I don't want to go to far in the configuration.

**Comment by apfelmaennchen** [comment]
The ventilation cannot be turned off via the app, so operating mode OFF is not applicable.
Only allowed values are DAY, NIGHT and AUTO.
The problem is the on/off switch which will cause an error message:
![fan](https://user-images.githubusercontent.com/14122043/103298928-b0659b80-49fb-11eb-95d7-1ee47b535635.png)

**Comment by thomasgermain** [comment]
Ah ok, understand, I will remove OFF. (turn off is not working because it sets `OFF` mode).

So the fan is considered off when NIGHT mode is activate and turning it off through HA will activate NIGHT (turn on will set AUTO mode), does it seem legit to you ?

Could you do a test with the ventilation boost quick mode ?

**Comment by apfelmaennchen** [comment]
QM_VENTILATION_BOOST works as desired. It turns the heating off and puts ventilation on maximum for 30 min.
It would be nice if the ventilation entity could display that the ventilation boost quick mode is active.

NIGHT = off and AUTO = on is fine for me.
I have implemented all discussed changes and corrections locally.
So please see the attached file for your reference:
[fan.zip](https://github.com/thomasgermain/vaillant-component/files/5753772/fan.zip)

**Comment by thomasgermain** [comment]
Thanks for your help and testing :) 

Normally, the fan entity should display the ventilation boost in speed field when the quick mode is activated, what is displayed in HA when the ventilation boost is activated ?

**Comment by apfelmaennchen** [comment]
I guess currently it shows a 'None' speed as BOOST is not defined as operating mode.
![fan](https://user-images.githubusercontent.com/14122043/103344507-151e0600-4a8f-11eb-89fa-ca94ab9fdd16.png)

**Comment by thomasgermain** [comment]
The new release should be fine: https://github.com/thomasgermain/vaillant-component/releases/tag/1.5.0b03

thanks again for your testing and time :)

**Comment by thomasgermain** [comment]
Hi @apfelmaennchen, any news on this one ?

**Comment by agipablo** [comment]
Earlier in the thread, the possibility to set ventilation speed levels (1-6) for NIGHT and DAY modes was discussed. Would it be possible to add this feature?

**Comment by thomasgermain** [comment]
To me, this is the kind of configuration that should not be in HA. I mean, I think HA is for day to day usage, if you need to change such configuration, it should be done via your mobile app or your VRC7XX. 

In the same way of thinking, you can't change a zone name through HA, or you can't  set the DAY temperature for a zone neither.

**Comment by agipablo** [comment]
Thanks for your quick reply. I fully agree regarding the schedule for DAY/NIGHT, but changing the speed of the fun is something to be changed as part of day-to-day usage. I have CO2 sensors throughout the house and plan to automate the ventilation speed based on the measurements, so that I have good air quality while keeping the noise as low as possible, both during the day and at night. I believe that kind of automation is one of HA goals.

Since I have a recoVAIR installation I could help with testing, logs, sending some sample Postman requests, etc. However, my Python skills are not adequate enough to provide a pull request, hence my request here.

**Comment by agipablo** [comment]
What do you think? Would you consider adding this functionality with some help with testing, etc?

**Comment by thomasgermain** [comment]
Isn't there a quick veto also for ventilation like there is for rooms and zones ?

For now, I'm quite busy making the integration more stable (the API itself is quite unstable). 

Maybe I can create a service so you can have a way to set the ventilation level (for day and night), but, as I explained above, I'm not a big fan of that

**Comment by agipablo** [comment]
I'm afraid there is no quick veto option for ventilation, in the app you need to change the day/night setting which is permanent. A service for that would be great, I would really appreciate it.

I understand stability is a priority. Entities becoming unavailable for long periods of time will not allow reliable automation anyway.

**Comment by agipablo** [comment]
I saw that 1.11 adds the capability to set ventilation levels for day & night! That's great news for me, thank you!

How can I use this service? I tried:
```
service: multimatic.set_ventilation_day_level
data:
  level: 4
```

but got an error:

```
[547386030976] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 523, in handle_execute_script
    await script_obj.async_run(msg.get("variables"), context=context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1243, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 353, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 371, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 571, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1495, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1530, in _execute_service
    await handler.job.target(service_call)
  File "/config/custom_components/multimatic/service.py", line 121, in service_call
    await method(data=call.data)
  File "/config/custom_components/multimatic/service.py", line 154, in set_ventilation_day_level
    await self.api.set_fan_day_level(data.get(ATTR_LEVEL))
  File "/config/custom_components/multimatic/coordinator.py", line 395, in set_fan_day_level
    await self._manager.set_ventilation_day_level(level)
TypeError: set_ventilation_day_level() missing 1 required positional argument: 'level'
```

Please advise.

**Comment by thomasgermain** [comment]
I'll have a look. I'm quite busy for the moment :face_exhaling:

**Comment by VaillantHassIo** [comment]
same issue here

**Comment by VaillantHassIo** [comment]
has this been fixed with the latest release?

**Comment by thomasgermain** [comment]
I close this one. Feel free to open a new issue if there is still a problem
