### ISSUE TITLE
Multiple instances of the integration

### ISSUE THREAD

**Issue by faelterman-kaap** [thomasgermain/vaillant-component#35]
Hi, 

I just installed your component, and it connected to my system.
I have 2 different vaillant-boilers. both have a VR 920 so, I can control both via the multimatic app. 
In home assistant it sees 2 devices. HA or the component named one multimatic and another VR920.
On the integrations pages it says there are 11 entities. But some are from the one boiler, some for the other. 
Can I do something to fix this behaviour. If you need more information please do say so... I'm no developpper at all, but I'll do my best.

**Comment by thomasgermain** [comment]
Hello,

just to ensure I understand it correctly, you only have on VR920 right ?

For the VR920, you should see one device and 2 entities (system online and system update). 
The the multimatic device you should have one entity: water pressure. I don't know why, but in the vaillant system, the water pressure is linked to a "multimatic device" and not to the boiler.

You also have other entities not bind to a device like outdoor temperature, quick mode, holiday mode, etc.

**Comment by faelterman-kaap** [comment]
Hello, 

No, I have 2 boilers with each a VR920. I tried in the meanwhile with the latest beta whit out luck ; The problem is when I add the second time integration/multimatic, the system can't figure out all the different sensors. If I only do one boiler+ VR920 all is good, but when I add a second and fill in different user and serial, HA doesn't recognise climate.control... of the newly added instance.

**Comment by thomasgermain** [comment]
If you add a second time the integration, it means you have 2 serials right ? So you have 2 vr920 ?

Did you tried to specify the serial each time you add the integration (by default, the integration will pick the first serial it finds) ?

I confess, I didn't test that much when there is multiple integration running. Could you do some screenshots of both integration devices and entities ?

**Comment by thomasgermain** [comment]
Hmm I think I got it. Devices are somehow "shared" by both integration instance. Ha based itself on the `device_info` `identifiers`. Some ids are the same for all installations (like id for reports), so I added the serial number, when available. I also added the serial number on the entity_id when it's specified during the creation of the integration

I released a beta version https://github.com/thomasgermain/vaillant-component/releases/tag/1.4.1b1, it should fix your issue, could you have a look ?

**Comment by faelterman-kaap** [comment]
Hi thomas;
I'll surely try that out, but will probably be tomorrow or later. Thanks a lot for looking in to this. 

Kind regards

**Comment by faelterman-kaap** [comment]
Fantastic; Now it works. 
I have climate control of 5 zones, controlled by 2 boilers + 2 VR920's. 
The only thing I'm missing is to have entities like current (room) temperature as a separate sensor... Is this normal? 

I would like to have a graphical presentation in my dashboard of temperature vs time...

**Comment by thomasgermain** [comment]
Great fine :)

What do you mean by room ? = Ambisense ? With vr50 valve ?

Also, there is no temperature sensor for a zone, since there is already a climate, so you can extract the current temperature from there

**Comment by faelterman-kaap** [comment]
Hi Thomas, 
I mean I have 5 VRC 700 thermostats in each room. I can view the current temperature via the climate.vaillant_xxxxxxxx with the climate card in lovelace. 
I can have the outdoor temp. in a graph but no sensor."room1"...
But googling brought me to [this](https://www.reddit.com/r/homeassistant/comments/em192k/create_sensor_from_entity_attributes/
), so I imagine this is a Home Assistant thing and has not so much anything to do with the integration.

**Comment by thomasgermain** [comment]
ah ok, then you have one heating circuit per "room" ?
Yes you can create an entity based on another entity's attribute: https://www.home-assistant.io/integrations/template/.

**Comment by faelterman-kaap** [comment]
Hi, 
I'm afraid it's not completely working in 1.4.1b1. It doesn't survive a reboot. I tried to replicate the issue as good as I could, and it seems to mee; I can add the integration 2 times for the different serial numbers and everything works as intended, but after reboot it seems the devices have a double entry and as a result only one of the integrations is working and the other becomes unavailable.  
If I add one integration and fill out the form it comes with 3 devices VR920 / multimatic / "VC 486/5 - 5 (E-BE)" the latter being the model of my boiler. If I add the second integration (with the different serial number) the same happens. 
After reboot instead of each integration having 3 devices. One has 5 devices (2 x multimatic, 2 x VC486, and one VR920). The other has the 3 devices as of after installation.  But when going to the devices-list there lives only one VR920 instead of 2.

**Comment by faelterman-kaap** [comment]
<img width="1141" alt="Screenshot 2021-01-21 at 13 42 18" src="https://user-images.githubusercontent.com/58932050/105352661-7d738980-5bee-11eb-9ef4-67c762d02413.png">

**Comment by thomasgermain** [comment]
I don't think this is due to the name of the integration, I have multiple integration instantiated multiple times and it works (with the same name)

Are you still able to use **entities** correctly ? I mean, if you created both integration with different serial number, you should have entities like `binary_sensor.vaillant_[serial number 1]_quick_mode` and `binary_sensor.vaillant_[serial number 2]_quick_mode`, is it the case ?

**Comment by thomasgermain** [comment]
Ah got it ! Actually, the way integration data are stored into HA are not good (actually, integration #2 is overriding data of the integration #1), this is fix in the 1.5.0bx beta version, but I still have to apply 1.4.1b1 fix.

I'll keep you updated

**Comment by faelterman-kaap** [comment]
Great ! thanks a lot

**Comment by thomasgermain** [comment]
Here is the release, it *should* work, but my tests are limited. What is the result ?

**Comment by faelterman-kaap** [comment]
First of all, thank you very much for all your efforts. 
I'm afraid it still doesn't survive a reboot. When I add everything it works as it should, but when I restart , it's only one boiler and it's controls that survive the reboot, the other one becomes unavailable. 

Kind regards

**Comment by faelterman-kaap** [comment]
I was wondering if you give this issue anymore thought? 

Kind regards

**Comment by thomasgermain** [comment]
I still working on it, but I can't test your test case, which makes it hard to debug. But to be honest, I can't see any solution right now,  it sounds HA is messing something with integration data when restarting.

Could you do some screenshot of both integration instances ?

**Comment by thomasgermain** [comment]
maybe the 1.5.0b07 version can fix your issue: https://github.com/thomasgermain/vaillant-component/releases/tag/1.5.0b7

**Comment by thomasgermain** [comment]
Well.. there are lots of problem at vaillant side for now. I will reach you once they fixed their sh*t :angry: 

(By the way, did you deleted everything and add 2 times the integration with different serial ? Also, You might have to use 2 different users ?)

**Comment by faelterman-kaap** [comment]
>  You might have to use 2 different users

I remember I did that earlier to no avail, but I'll try it again.  I think my android app (vaillant) acted funny when I had 2 different users.

**Comment by thomasgermain** [comment]
I didn't forget you !
I did some try with version 1.7.0b0 see https://github.com/thomasgermain/vaillant-component/releases/tag/1.7.0b0.

As usual, this is quite hard for me to test, but I hope it will work for you this time !

**Comment by faelterman-kaap** [comment]
Hi, thank you very much. It will be a while untiull I'll be able to test it, cause there are some busy busy weeks on an other location of my work. 

Much appreciated

**Comment by thomasgermain** [comment]
version 1.7.0 is out, please open an new issue if you still have trouble.
