### ISSUE TITLE
Support for VMS8D

### ISSUE THREAD

**Issue by marcodewaard** [thomasgermain/vaillant-component#36]
Hi! At home we have a Vaillant heat pump setup but also a VSM8D solar system. The multimatic app does not show any information about the VMS8D but I guess the information should be available within the eBus system, right? 

Is there any possibility to get the information from the VMS8D into Home Assistent?

**Comment by thomasgermain** [comment]
Hello, 

if the info is not available inside the app, then it won't be available in the component. 

I didn't play with ebus so I can't help you, but if you can see this info on your heat pump or your vrc 700, then you should be able to find it with ebus. You can check here: https://github.com/john30/ebusd-configuration for ebusd, you may find some help
