### ISSUE TITLE
How to deal with system errors?

### ISSUE THREAD

**Issue by philippbosch** [thomasgermain/vaillant-component#37]
I have a VR921 connected to Home Assistant using your fantastic component. I'm trying to find out how to deal with errors in the heating system. 

Right now for example, there is a F.900 error that I can see in `system.errors` when using pymultimatic. I also saw that a binary sensor called `binary_sensor.vaillant_error_f_900` is currently available in Home Assistant. But I assume the sensor will become unavailable when the error is fixed. 

I'm not an HA expert and I can't see how I could set up something in HA that would alert me if there are any problems with the heating system. It feels cumbersome to watch all possible sensors for all available error codes. Is there a way to have a sensor that tells me if there are any errors at the moment, and ideally give me a list of these errors (possibly in a different sensor)? Or maybe there is a better way to approach this?

Thanks for your help and your work on this!

**Comment by philippbosch** [comment]
Oh, darn, I just saw #31. Will look into this now …

**Comment by thomasgermain** [comment]
As you see, you should try: https://github.com/thomasgermain/vaillant-component/releases/tag/1.5.0b4 (beta for now, but quite stable)
