### ISSUE TITLE
Best way to update to new version(s)...

### ISSUE THREAD

**Issue by lecocqe** [thomasgermain/vaillant-component#42]
Hello Thomas,

what is the best way to update to new version ?
- copy the new files into "custom_components"
OR
- delete the integration, copy new files and then re-add integration ?

thank you for your great work.

EL

**Comment by thomasgermain** [comment]
Hello,

if you're moving from beta to beta (I mean 1.5.0bx to another 1.5.0by) then you can just copy new files inside custom_components and restart HA.

If you're moving from 1.4.0 to 1.5.0bx, you should delete your integration, copy new files, restart and add the integration again.

I'm planing to release 1.5.0 as soon as I have feedback for senso app and multi instances, and I will make a guide to migrate

**Comment by lecocqe** [comment]
thank you for the fast reply
