### ISSUE TITLE
ActiveFunction KeyError None 

### ISSUE THREAD

**Issue by vit-** [thomasgermain/vaillant-component#46]
The integration crashes within few minutes after startup with the following exception:
```python
Unexpected error fetching multimatic data: None
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 151, in async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 139, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/multimatic/hub.py", line 104, in _fetch_data
    system = await self._manager.get_system()
  File "/usr/local/lib/python3.8/site-packages/pymultimatic/systemmanager.py", line 97, in get_system
    zones = mapper.map_zones(full_system)
  File "/usr/local/lib/python3.8/site-packages/pymultimatic/model/mapper.py", line 219, in map_zones
    zone = map_zone(raw_zone)
  File "/usr/local/lib/python3.8/site-packages/pymultimatic/model/mapper.py", line 238, in map_zone
    active_function = ActiveFunction[configuration.get("active_function")]
  File "/usr/local/lib/python3.8/enum.py", line 387, in __getitem__
    return cls._member_map_[name]
KeyError: None
```

**Comment by thomasgermain** [comment]
Unfortunately, I can't do anything about that. It seems *sometimes*, the API is giving some `None` values. 
I fixed it locally for `ActiveFunction` but now I have the same error but for the `operating_mode`. And without the `operating_mode`, most of the functionalities will be unavailable.

I'm trying to debug it locally, but well I just can see there are no value coming from the API.

**Comment by vit-** [comment]
> sometimes

Looks like it happens all the time in my case :)

This leads to all my sensors become Unavailable on the main dashboard. From the user perspective, I would prefer seeing some stale data instead of nothing. Do you think it is possible?

**Comment by thomasgermain** [comment]
I would say.. did you try restarting HA or reloading the integration ?

I'm really disappointed because I don't have any other solution to propose.

**Comment by vit-** [comment]
I've reloaded integration a few times, didn't help. I don't believe restarting HA will help, but I can try that as well.

**Comment by thomasgermain** [comment]
No I don't think so.. :disappointed:  I would say I can see tomorrow. Usually, the vaillant server is restarted every night around 3:30, maybe it will fix the issue ?

**Comment by thomasgermain** [comment]
It sounds the "nightly restart" fix it for me, does it work at your side?

**Comment by vit-** [comment]
Yup, there are no exceptions since 01:38 UTC. Thanks for the explanation, closing the issue.
