### ISSUE TITLE
Error while setting up multimatic platform for fan multimatic/fan.py:22 NoneType' object has no attribute 'ventilation'

### ISSUE THREAD

**Issue by Wiggum127** [thomasgermain/vaillant-component#54]
Seeing a specific error related to fan.py

Running HA Container, 2021.5.0, and latest version of multimatic custom component (v1.6.1).

`Logger: homeassistant.components.fan
Source: custom_components/multimatic/fan.py:22
Integration: Ventilator (documentation, issues)
First occurred: 17:40:05 (1 occurrences)
Last logged: 17:40:05

Error while setting up multimatic platform for fan
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 231, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/multimatic/fan.py", line 22, in async_setup_entry
    if hub.data.ventilation:
AttributeError: 'NoneType' object has no attribute 'ventilation'`

**Comment by thomasgermain** [comment]
Yup, something that should be fixed with the next beta, I'm currently testing the alpha.

Normally, It should only occurs if you have a previous error like #48 right ?

**Comment by Jakuzzi** [comment]
Hello Thomas,

I installed your component via HACS, but it does not autodiscover any devices. In the logs I can see the same error as Wiggum127.

Any news on this issue?

Best regards

**Comment by thomasgermain** [comment]
Hello,

same question as above, if you have this error, you should have the same kind of error as #48, is that right ?

**Comment by Jakuzzi** [comment]
Actually not.

This error occurs right after configuration of my username, password and serial number.
There is no device discovered at all.
I assumed this was due to the error.

**Comment by thomasgermain** [comment]
Are you using the sensoAPP or the multimatic app ?

**Comment by Jakuzzi** [comment]
I am using the sensoAPP. I was not aware that there is a difference with respect to the API?!

**Comment by thomasgermain** [comment]
this integration is only compatible for multiMATIC (VRC700), I guess you have a VRC720 (=sensoAPP) ?

You can't use multimatic app (due to limitation from Vaillant). There is some WIP to be able to be compatible with sensoAPP, but I don't have sensoAPP, so I can't do anything.

BUT Vaillant is planning to migrate everything (sensoAPP and multimatic) to a new platform called "myVaillant",

see here for planning: https://www.vaillant.de/heizung/produkte/mobile-apps/myvaillant-app/ (an here for country specific: https://upgrade.myvaillant.com/, but depending on the language, information is not exactly the same..)

**Comment by thomasgermain** [comment]
@Wiggum127 I guess you also have sensoAPP ?

**Comment by Jakuzzi** [comment]
I just checked and actually I have a VRC700.
The installation company told me that I could use multimatic app or sensoApp, so for no specific reason I chose sensoAPP.

By the way, some time back I experimented with pymultimatic and was able to retrieve information via the dump.py script that you provide. So there should be some communication possible?!

**Comment by lecocqe** [comment]
to test (i'm in belgium), i installed senso app (on a phone that never had sensoapp or multimatic) and have VRC700 + VR900 (which normally is used by multimatic app)...
i entered user-id +psw and it worked

**Comment by thomasgermain** [comment]
Hm strange, well maybe you can try the multimatic app, but I'm afraid some stuff on your account has been initialized which will prevent you to go back to multimatic.

**Comment by thomasgermain** [comment]
> to test (i'm in belgium), i installed senso app (on a phone that never had sensoapp or multimatic) and have VRC700 + VR900 (which normally is used by multimatic app)...
> i entered user-id +psw and it worked

and does the integration work ?

**Comment by lecocqe** [comment]
> 
> 
> > to test (i'm in belgium), i installed senso app (on a phone that never had sensoapp or multimatic) and have VRC700 + VR900 (which normally is used by multimatic app)...
> > i entered user-id +psw and it worked
> 
> and does the integration work ?

forget what is wrote. i have a VRC700 + VR920

**Comment by lecocqe** [comment]
integration is ok. only the #48 .

**Comment by lecocqe** [comment]
> 
> 
> > > to test (i'm in belgium), i installed senso app (on a phone that never had sensoapp or multimatic) and have VRC700 + VR900 (which normally is used by multimatic app)...
> > > i entered user-id +psw and it worked
> > 
> > 
> > and does the integration work ?
> 
> forget what is wrote. i have a VRC700 + VR920

but sensoapp works for me

**Comment by Jakuzzi** [comment]
Now I installed the multimatic app on a second phone.
I even created a new account for HA. Still no luck and same error message.

**Comment by thomasgermain** [comment]
> Now I installed the multimatic app on a second phone.
> I even created a new account for HA. Still no luck and same error message.

But multimatic app works or not ?

**Comment by Jakuzzi** [comment]
Yes the multimatic app works. Actually, the UI looks exactly the same as the SensoAPP.

**Comment by thomasgermain** [comment]
Can someone confirm me if it works correctly or not ?

**Comment by Wiggum127** [comment]
Upgraded to latest and greatest of HA DC (v2021.6.2) and multimatic (v1.7.0b0 via git clone) in the custom_components dir.

It resulted in all multimatic related entities being duplicated. I removed the duplicate multimatic entities which were not working, resulting in a set the full set of entities being operational.

Will keep an eye on the logs and revert back in case something pops up.

**Comment by thomasgermain** [comment]
But the way @Wiggum127 are you also in the case being "between" multimatic  and senso app (I mean you somehow switch from one to the other?

**Comment by Wiggum127** [comment]
No, I'm not using Senso or switching between something else. I do have the VRC 700 android app installed. It is using the same registration key, but a different user/pwd compared to HA.

**Comment by Jakuzzi** [comment]
After upgrading to v1.7.0b0 I now see in addition to the fan error, a warning:

Multimatic API: Cannot get https://smart.vaillant.com/mobile/api/v4/facilities/XXXXXXXXXXXXXXXXXXXX/systemcontrol/v1, status: 409, response: {"errorCode":"FACILITY_NOT_COMPATIBLE"}

and an additional error:
Unexpected error fetching multimatic data: Cannot get https://smart.vaillant.com/mobile/api/v4/facilities/xxxxxxxxxxxxxxxxxxxxxxxxxxxx/systemcontrol/v1

**Comment by Jakuzzi** [comment]
After upgrading to version 1.7.0b3 I now finally see devices and entities. The errors from v1.7.0b0 are also gone. Thanks for the work on the integration!!! 👍 

However, this newly appeared:

Logger: homeassistant.core
Source: core.py:1370
First occurred: 16:11:19 (2 occurrences)
Last logged: 16:11:19

Unable to remove unknown service multimatic/remove_quick_veto
Unable to remove unknown service multimatic/set_quick_veto

**Comment by thomasgermain** [comment]
yep, this is because the previous instance of the integration was "empty" so it tried to cleans stuff that were not here. It should be fine now you have entities and other stuff setup

**Comment by thomasgermain** [comment]
I'm gonna close this one, to me I did my best to reduce to number of errors and also, if there is an error, only few entities are unavailable. I also want a clean status of issues before releasing 1.7.0 (non beta :smile:).

Feel free to open a new issue if the problem occurs again
