### ISSUE TITLE
Multimatic does not show in HACS

### ISSUE THREAD

**Issue by Wiggum127** [thomasgermain/vaillant-component#55]
I've installed HACS.

When I remove the multimatic integration via the HA GUI and try to find the integration via HACS, multimatic is not found. Am I overlooking something ?

_Originally posted by @thomasgermain in https://github.com/thomasgermain/vaillant-component/issues/41#issuecomment-834519061_

**Comment by thomasgermain** [comment]
AH yeah, nice catch. It was originally planned to be integrated to HACS, but we decided with HACS team that it should be better to keep it as custom repo, see, https://hacs.xyz/docs/faq/custom_repositories/ for installation details.

I'll keep the issue open until I did the update on the readme

**Comment by Wiggum127** [comment]
Is showing now. case closed.
