### ISSUE TITLE
Service to get/set date and time

### ISSUE THREAD

**Issue by smmoroz** [thomasgermain/vaillant-component#57]
Hi, Thomas,

From time to time my VRC700 resets date/time to default values. As far as I know, VRC700 doesn't have any battery inside. It uses large capacitor instead. Thus as capacitor degrades with time, there could be issues with the date/time settings. 

VRC700/VR920 doesn't use NTP or similar protocol to set date/time. Thus after every reset I have to manually set date/time. It is possible to do via Mobile app. There should be an API call for this.

Is it possible to add a special HA service to your component to get/set date/time from Vaillant hardware?

Best regards,
Sergey.

**Comment by thomasgermain** [comment]
Hello,

to me, this is the same kind of config that should not be included in the integration, this is not directly related to the platform used by the integration (fan, climate, water_heater, etc).

Maybe another option would be to create a script and the trigger it when you want via an automation ?

**Comment by smmoroz** [comment]
There is already a service 'multimatic.request_hvac_update'. Why isn't it possible to add something like 'multimatic.set_date_time' service? BTW, I don't even know if such API call exists.

Of course it will be called manually or by some trigger.

**Comment by thomasgermain** [comment]
`request_hvac_update` is needed in some case to refresh data (some users reported their data were not getting updated).

From technical point of view, there is no problem adding a set_date_time service, this is more a scope problem. I don't want to add every single configuration possibilities available in the app or on the VRC700 (also, my end goal is to have the integration included in HA core, and I'm quite sure this kind of service won't pass the code review), this is why I proposed you to have a small script to the datetime and triggered it via automation

**Comment by smmoroz** [comment]
Thomas, got it. I'm fine to use the script to set the date/time. Can you please share such script?

**Comment by thomasgermain** [comment]
I don't have a script right now, but I could do that

**Comment by smmoroz** [comment]
It would be great! Looking forward to get it!

As for making this a general feature of the component, without NTP-like date/time setting the whole Vaillant hardware is more or less useless, because the time schedule only works if date/time is properly set. So, one can that this is an essential feature for your component. I believe it will be accepted by HA core team.

This feature, e.g. automatic update of date/time,  could be deeply integrated into component and could be turned on/off via component option.

**Comment by smmoroz** [comment]
Hi, Thomas,

I played a little bit with Vaillant API using pymultiMATIC as a source of information. I found only one place with facility date/time information here ``https://smart.vaillant.com/mobile/api/v4/facilities/_serialNumber_/system/v1/details``. In my case the response is like this:

```json
"body":{
  "facilityDetails":{
    "facilityName": "NAME",
    "facilityTime": "2021-06-08T19:49:35.986Z",
    "facilityTimeZone": "Europe/Moscow"
  }
},
"meta":{}
```

But [facilities_details()](https://github.com/thomasgermain/pymultiMATIC/blob/61c256f142d6bdce7e8a0c1d2e574b66cd735879/pymultimatic/api/urls.py#L292) is not reference anywhere in the code. So, it was not clear for me, if it is possible to modify ``facilityTime``.

I tried PUT method with ``https://smart.vaillant.com/mobile/api/v4/facilities/_serialNumber_/system/v1/details`` with this payload:

```json
{
  "facilityName": "NAME",
  "facilityTime": "2021-06-07T19:00:00.000Z",
  "facilityTimeZone": "Europe/Moscow"
}
```
 
It doesn't work. The response is ``HTTP Status 405 – Method Not Allowed``.

I also found that date/time information is available here: https://smart.vaillant.com/mobile/api/v4/facilities/_serialNumber_/systemcontrol/v1/status. Here is the response:

```json
"body":{
  "datetime": "2021-06-08T20:22:28.000Z",
  "outside_temperature": 19.4
}
```
But it is also not possible to set this datetime.

**Comment by smmoroz** [comment]
I have finally found the right endpoint:

https://smart.vaillant.com/mobile/api/v4/facilities/_serialNumber_/systemcontrol/v1/status/datetime

PUT method works here with this payload

```
{
  "datetime": "2021-06-08T18:00:00.000Z"
}
```

I will now try to write Python script.

**Comment by smmoroz** [comment]
Yes!

**Comment by smmoroz** [comment]
Hi, Thomas,

Let me come back to this issue. Recently I've updated multimatic component to 1.7.1. And now I see a lot of errors likes this:

```
2021-08-18 11:34:27 ERROR (MainThread) [custom_components.multimatic.coordinator] Unexpected error fetching multimatic_quick_mode data: Unable to authenticate at https://smart.vaillant.com/mobile/api/v4/account/authentication/v1/authenticate
```

I'm pretty sure that this is because my get/set date scripts interfere with multimatic component. Both scripts and component use the same login/password to login/authenticate. get_time script is executed every 5 minutes. And as far as I understand, it destroys multimatic component session/token.

What is the best way to overcome this problem? New user?

What if you reconsider adding get/set datatime service to your component?

**Comment by thomasgermain** [comment]
Hmm yeah, strange that it appears with 1.7.1, this is a minor change. 

As you said, you could use a seperate user in order to avoid authentication issues.

**Comment by smmoroz** [comment]
Thomas, I have migrated from 1.5.0 to 1.7.1. It was a big update for me ;) So, no worries.

**Comment by xrado** [comment]
@smmoroz I'm having the same problem with time being reset. I've tried your script but doesn't work anymore. I'm getting {"errorCode":"INVALID_PARAMS"} on last call, when getting the time.
