### ISSUE TITLE
Setup failed for vaillant: 'Integration not found' after update HA Core

### ISSUE THREAD

**Issue by johanvh83** [thomasgermain/vaillant-component#59]
Hi,
I've update HA Core from core-2021.5.5 to core-2021.6.2
After restarting I have a notification:
`The following integration and platform could not be set up:
vaillant`
The log shows: 
`Logger: homeassistant.setup
Source: setup.py:172`
I don't know if this refers to a file called 'setup.py'. In my vaillant folder under custom-components there is no setup.py:
![Schermafbeelding 2021-06-06 om 19 20 03](https://user-images.githubusercontent.com/76775686/120933817-36e57e00-c6fc-11eb-95e8-094d786e2f97.png)
I went back to core-2021.5.5 with the snapshot and everything started normally. 
Gave it a 2th try to core-2021.6.2 and had again the same error.
Could it be that your integrations is no longer compatible with the new core version?
Is there anything I can do from my side to solve this issue?
If a can log something for you, please send intructions.
I hope this is soon resolved.

Kind regards,
Johan

**Comment by thomasgermain** [comment]
Hello,

I moved to 2021-6.X yesterday (saturday) evening without issue, which version are you using ?

**Comment by johanvh83** [comment]
I've update HA Core from core-2021.5.5 to core-2021.6.2

**Comment by thomasgermain** [comment]
Ow, you are using a pretty old versio, you should try with the latest, https://github.com/thomasgermain/vaillant-component/releases/tag/1.6.2 (if you have HACS, you can install the integration using custom repositories). You should also have a look here about breaking changes: https://github.com/thomasgermain/vaillant-component/tree/1.5.0

**Comment by johanvh83** [comment]
Ok, thanks, what is the best way? Remove the vaillant folder in the custom components folder and re-install by HACS?

**Comment by thomasgermain** [comment]
Indeed, I think this is the easiest way

**Comment by johanvh83** [comment]
Ok, thanks. Will take a while to change everything but I believe there should be a reason you changed.
Thanks anyway, the integration remains great!

**Comment by thomasgermain** [comment]
Well yeah, I recommend to expect 15-30min to migrate due to entity name/service name changed.

You're welcome :)

**Comment by johanvh83** [comment]
Hi Thomas,
I removed the vaillant folder in the custom-components folder and installed manually the Multimatic integration.
In the meantime everything is changed. Multimatic integration setup and changed all my automations.
By changing the climate entities for all rooms, I've seen that the old vaillant entities were still present and unavailable so I've removed them manually.
The core was on core-2021.5.5, so with the Multimatic integration installed I upgraded to core-2021.6.2.
The Multimatic integration works but I still get the same message: The following integrations and platforms could not be set up: vaillant.
Any idea how to solve this because now I cannot restart HA due to this error.

**Comment by thomasgermain** [comment]
Did you delete the vaillant integration from the UI ?

**Comment by johanvh83** [comment]
No, and now it's not possible anymore:
![Schermafbeelding 2021-06-06 om 21 08 40](https://user-images.githubusercontent.com/76775686/120937035-618b0300-c70b-11eb-9cd7-8251a137c361.png)
No 3 dots to do something

**Comment by thomasgermain** [comment]
Well you can add the vaillant folder in custom_component and restart HA, I guess youbwould ne able to delete the integration After that

**Comment by johanvh83** [comment]
Thanks Thomas but in the meantime I already returned to 5.5 with vaillant and proceed than in the correct way.

**Comment by johanvh83** [comment]
Hi Thomas,
Since the upgrade I have many times that all items become unavailable.
Have seen that many experience this problem.
How can I check which version I have installed?

**Comment by lecocqe** [comment]
in the manifest.json, you have the version.

have a nice weekend,

**Comment by johanvh83** [comment]
OK, thanks, have upgraded to latest version.
Hopefully, problems as:
![Schermafbeelding 2021-06-25 om 22 52 50](https://user-images.githubusercontent.com/76775686/123484227-4c1d4080-d608-11eb-8bc5-8cde31cdd26e.png) are gone now...

**Comment by johanvh83** [comment]
Over-writing was not a good idea. Removed the multimatic folder and copied the new unpacked folder.
The manifest.json gives now the latest version: 1.7.0b1
Keep you posted about my experiences.
