### ISSUE TITLE
Change from valiant to multimatic

### ISSUE THREAD

**Issue by Zwente** [thomasgermain/vaillant-component#61]
Hi,
hopefully someone can help me.
I tried to make the changes you said:

Delete vaillant integration from HA UI
Delete vaillant folder from custom_component
Copy multimatic folder (from 1.5.0 release) and past it to custom_component
Restart HA

But I always get this  Error after restart :

2021-06-15 12:14:42 ERROR (MainThread) [homeassistant.setup] Setup failed for vaillant: Integration not found.

**Comment by thomasgermain** [comment]
Hello,

sounds like you didn't delete the vaillant integration, is the integration still available at HA integration page ? (By the way, you can directly migrate to 1.6.2)

**Comment by Zwente** [comment]
i delete the vailant integration on the integration page. but after every restart I have this picture :
<img width="1579" alt="Bildschirmfoto 2021-06-15 um 12 38 03" src="https://user-images.githubusercontent.com/62428865/122039162-aa5f4d80-cdd6-11eb-99ce-c1daa3f490b7.png">

**Comment by thomasgermain** [comment]
Quite strange, can you check your file `config/.storage/core.config_entries` if there is something related to vaillant ? If so, you can remove the entry related to vaillant

**Comment by Zwente** [comment]
i do not have the .storage folder , or I do not see it in the file editor : how can I enable it ?

**Comment by thomasgermain** [comment]
you can access it through samba if you have the addon. For the editor, maybe you have an options like "hidden folder" or so

**Comment by lecocqe** [comment]
what happens if you click on the 3 dots ?
can you clear your cache ?
did you try with different browsers ?

**Comment by Zwente** [comment]
So now I get it to deinstall everything, now the next problem after the new integration and a reboot from HA the new integration from multimatic got lost. also a new integration Leeds to the same issue
<img width="1564" alt="Bildschirmfoto 2021-06-15 um 15 25 58" src="https://user-images.githubusercontent.com/62428865/122060916-4ea0be80-cdee-11eb-82e8-3459521fefc2.png">

**Comment by thomasgermain** [comment]
What do you mean by "lost" and the "same issue" ? Do you have any error in the log ?

**Comment by lecocqe** [comment]
pay attention to the fact with the recent version sensor name contains the (very long) serial name. 
you can also manually delete those "old" sensors.

**Comment by lecocqe** [comment]
that's also true that logs are the very first step to see what's wrong

**Comment by Zwente** [comment]
Hier die Aktuelle Fehlermeldung aus dem Log

<img width="978" alt="Bildschirmfoto 2021-06-16 um 16 16 12" src="https://user-images.githubusercontent.com/62428865/122235737-39936080-cebe-11eb-9772-eaa47e3b772d.png">

**Comment by thomasgermain** [comment]
You can try to reload the integration.

This is actually issue #48, vaillant API is sending wrong responses..
