### ISSUE TITLE
Feature request: Show humidity

### ISSUE THREAD

**Issue by didiht** [thomasgermain/vaillant-component#68]
It would be nice to show humidity in HA if present.

Here is the output of **pymultimatic 0.3.2** script example, e.g. `humidity=57`
[get_system_vaillant.txt](https://github.com/thomasgermain/vaillant-component/files/6709011/get_system_vaillant.txt)

pymultimatic 0.4.0 raises exceptions due to missing 'timeprogram' in 'dhw'.

Thanks

**Comment by thomasgermain** [comment]
It sounds it can be added directly to the climate entity.

By the way, does the VR51 (thermostat) have a "child lock" option ?

**Comment by thomasgermain** [comment]
Also, do you also have a "direct" water heater ? (I mean without water tank ?)

**Comment by didiht** [comment]
It sounds it can be added directly to the climate entity.
-> **perfect**

By the way, does the VR51 (thermostat) have a "child lock" option ?
-> **Yes it has a child lock option**

Also, do you also have a "direct" water heater ? (I mean without water tank ?)
-> **Yes it is a direct water heater, there is no tank**

Thank you very much, great job!

**Comment by thomasgermain** [comment]
Ok, fine :)

May I ask you to provide me with the result of this script (it should print all your rooms) ?
- https://github.com/thomasgermain/pymultiMATIC/blob/v0_5_0/script/print_response.ps1 (powershell for windows)
-  https://github.com/thomasgermain/pymultiMATIC/blob/v0_5_0/script/print_response.sh: (bash linux)

You have to provide your username, password and the url for which the response will be printed:
`sh print_response.sh user passw ./print_response.ps1 user passw https://smart.vaillant.com/mobile/api/v4/facilities/{serial}/rbr/v1/rooms`

or for windows: `./print_response.ps1 user passw https://smart.vaillant.com/mobile/api/v4/facilities/{serial}/rbr/v1/rooms`.

Don't forget to remove some private info (like serial number, sgtin, etc.).

This is just to ensure the VR51 is the same format as VR50.

Thanks !

**Comment by didiht** [comment]
You are welcome :)

Here it is 
[rooms1_json.txt](https://github.com/thomasgermain/vaillant-component/files/6710385/rooms1_json.txt)

Thanks!

**Comment by thomasgermain** [comment]
release https://github.com/thomasgermain/vaillant-component/releases/tag/1.7.0b2 should display the humidity, could you confirm ?

**Comment by didiht** [comment]
Release https://github.com/thomasgermain/vaillant-component/releases/tag/1.7.0b2:

- Sorry, but I cannot see humidity, neither as entity nor as part of climate
- all 'binary_sensor' with 'battery', 'lock' and 'connectivity' entities have no name

Do you need more debug info?

**Comment by thomasgermain** [comment]
I'll put back  binary sensors room name.
You should be able to see attributes en dev tool

**Comment by didiht** [comment]
Ah, OK.
I can see 'current_humidity' e.g. on entity 'climate.kinderzimmer' in dev tool 👍

Thanks!

**Comment by thomasgermain** [comment]
release https://github.com/thomasgermain/vaillant-component/releases/tag/1.7.0b3 should re-add the name of room's related binary sensors

**Comment by didiht** [comment]
Confirmation! Names are re-added.
Thanks

**Comment by didiht** [comment]
And I see a new entity **hotwater** 👍 

Btw: Do you plan to show the value of **humidity** in the climate lovelace card?

**Comment by thomasgermain** [comment]
I can't do anything about the climate card. You can ask a feature request to show humidity maybe ? Or you can create an entity out of the current_humiity attribute, see https://www.home-assistant.io/integrations/template/

**Comment by didiht** [comment]
I expressed myself wrong, sorry. I mean the card of the termostat entity.

As I want to see the history I will follow your hint and create entities.

Thanks!
