### ISSUE TITLE
Manual cooling days

### ISSUE THREAD

**Issue by partydiktator** [thomasgermain/vaillant-component#69]
If i set my multimatic to manual cooling, i get the state attribute `cooling_for_x_days` A standard Lovelace card would show the following:

![image](https://user-images.githubusercontent.com/20315883/123635419-f325f600-d81b-11eb-958d-7b1d9ca80d84.png)

Is there any way to actually get the number of the days?

**Comment by thomasgermain** [comment]
I could add it to the attributes,  so you will be able to get it for automation purpose, but I don't know if you will be able see it via the climate card

**Comment by thomasgermain** [comment]
Release https://github.com/thomasgermain/vaillant-component/releases/tag/1.7.0b2 should include the feature, could you confirm ?

**Comment by partydiktator** [comment]
I'm gettimg an error message when the integration is loading:

Retrying setup: Cannot get https://smart.vaillant.com/mobile/api/v4/facilities/21202700202529220938018517N6/rbr/v1/rooms

**Comment by thomasgermain** [comment]
May I ask you to provide me with the result of this script ? I guess you should receive an HTTP 409.

https://github.com/thomasgermain/pymultiMATIC/blob/master/script/print_response.ps1 (powershell for windows)
https://github.com/thomasgermain/pymultiMATIC/blob/master/script/print_response.sh: (bash linux)
You have to provide your username, password and the url for which the response will be printed:
`sh print_response.sh user passw ./print_response.ps1 user passw https://smart.vaillant.com/mobile/api/v4/facilities/{serial}/rbr/v1/rooms`

or for windows: `./print_response.ps1 user passw https://smart.vaillant.com/mobile/api/v4/facilities/{serial}/rbr/v1/rooms.`

Don't forget to remove some private info (like serial number, sgtin, etc.).

**Comment by thomasgermain** [comment]
release https://github.com/thomasgermain/vaillant-component/releases/tag/1.7.0b3 should fix your problem

**Comment by partydiktator** [comment]
> release https://github.com/thomasgermain/vaillant-component/releases/tag/1.7.0b3 should fix your problem

i can confirm this - the integration is loading fine now.

anyway, maybe i just don't find ist but i'm not seeing the attribute für the cooling days.

**Comment by thomasgermain** [comment]
You mean the duration ?
You should be able to see it in dev tools, name should be `cooling_for_x_days_duration`

**Comment by luisdomg** [comment]
I installed 1.7.0b3, and I don't see the attribute:

hvac_modes: auto, off
min_temp: 5
max_temp: 30
preset_modes: comfort, day, sleep, cooling_on, home, party, away, system_off, cooling_for_x_days
current_temperature: 23.6
temperature: 23.5
hvac_action: cooling
preset_mode: cooling_on
friendly_name: ZONE 2
supported_features: 17

**Comment by thomasgermain** [comment]
it seems you are not in "COOLING_FOR_X_DAYS", see `preset_mode: cooling_on`, it should be `preset_mode: cooling_for_x_days` (it could be an issue on the component, since I don't have cooling system, I can't fully test it)

**Comment by luisdomg** [comment]
Don't know what to say, I set it manually and still says "cooling_on" and not cooling_for_x_days, and I remember clearly saying that before. If you want me to run some test, let me know...

climate.control_zo2_2 
ZONE 2
cool	
hvac_modes: auto, off
min_temp: 5
max_temp: 30
preset_modes: comfort, day, sleep, cooling_on, home, party, away, system_off, cooling_for_x_days
current_temperature: 23.9
temperature: 23.5
hvac_action: cooling
preset_mode: cooling_on
friendly_name: ZONE 2
supported_features: 17

![image](https://user-images.githubusercontent.com/85519959/124239160-b3138b80-db19-11eb-9d1f-2d229059bbde.png)

**Comment by thomasgermain** [comment]
Ok found it for the `cooling_for_x_days_duration` attribute (I will also add the `duration` for the quick_mode binary sensor).
Still have no clue why preset_mode is wrong, I'm checking it

**Comment by thomasgermain** [comment]
release https://github.com/thomasgermain/vaillant-component/releases/tag/1.7.0b4 should improve the cooling, let me know if you have issue

**Comment by thomasgermain** [comment]
version 1.7.0 is out and I'm doing some cleaning, please open an new issue if you still have trouble.
