### ISSUE TITLE
In HACS is no available beta 1.7.0b2

### ISSUE THREAD

**Issue by pepsonEL** [thomasgermain/vaillant-component#71]
Hi In HACS is not available beta version 1.7.0b2 ... Why ?

**Comment by thomasgermain** [comment]
Hi, if you go to HACS -> integration -> search for multimatic -> 3 dots -> update information. You also have to check the "beta" check box. Please note there might be an issue if you don't have rooms (=ambisense). But it should only be a log error and the integration should work correctly (I'll fix that in the next beta)

**Comment by pepsonEL** [comment]
ok thanks works and found new :)

**Comment by pepsonEL** [comment]
Did you know any info when new app MyVaillant will be available for users ?

**Comment by thomasgermain** [comment]
You can check here https://upgrade.myvaillant.com/, but they messed up the communication, information in french, english and german are not the same.., here is from the german version (the only one with a schedule). So apparently it already started for some people, we are already Q3 2021 (well ok, tomorrow :innocent: )

Regler | Bisherige App | Start Wechsel
-- | -- | --
sensoCOMFORT, sensoDIRECT, sensoHOME | sensoAPP | Ab Q2/2021
multiMATIC | multiMATIC App | Ab Q1/2022
Einzelraumregelung ambiSENSE | sensoAPP, multiMATIC App | Ab Q1/2023
In Kombination mit EEBUS | sensoAPP, multiMATIC App | Ab Q1/2023

**Comment by pepsonEL** [comment]
ok thanks
