### ISSUE TITLE
Unknown model

### ISSUE THREAD

**Issue by pepsonEL** [thomasgermain/vaillant-component#73]
Hi. I have multimatic integration 1.7.0b3 on my Home Assistant. And in home assistant in configuration>devices when i see my device vaillany has UNKNOWN model for this. Good will be if it show in this name example Vaillant or model boiler.... It will looks better. Please think about it.
![unknown_model](https://user-images.githubusercontent.com/71824185/124123560-bce4b280-da77-11eb-8af4-4feced02e336.jpg)

**Comment by thomasgermain** [comment]
these models are not available in the API :disappointed:

**Comment by pepsonEL** [comment]
Maybe good will be iff add MODEL as Vaillant.

**Comment by pepsonEL** [comment]
Or Multimatic.

**Comment by thomasgermain** [comment]
Maybe closed it to early, I can get the the `device_name`, this is something like `VRC700 MultiMatic` or `Flexotherm`

**Comment by pepsonEL** [comment]
I think that Multimatic VRC700 should be ok.

**Comment by thomasgermain** [comment]
It should be done with https://github.com/thomasgermain/vaillant-component/releases/tag/1.7.0b4

**Comment by thomasgermain** [comment]
version 1.7.0 is out and I'm doing some cleaning, please open an new issue if you still have trouble.
