### ISSUE TITLE
Version 1.7.0 - installed via HACS, removed integration, added integration: list index out of range

### ISSUE THREAD

**Issue by lecocqe** [thomasgermain/vaillant-component#79]
Hello,
installed version Version 1.7.0 via HACS, removed integration, added integration: (as suggested) and i got this one:
![image](https://user-images.githubusercontent.com/18657222/125307126-12e70f00-e330-11eb-9867-5d8f32a032f4.png)

but if i only update via HACS, (no remove, and no reinstall), it's ok. small inconvenient is that i have 2 ghost devices. i can live with.

Best regards,

**Comment by thomasgermain** [comment]
Please provide the logs

**Comment by lecocqe** [comment]
tried a 3rd time, and it worked.
we can close it. sorry

**Comment by thomasgermain** [comment]
It would have been nice to have the error log, to know if I can do something about it :stuck_out_tongue:

**Comment by lecocqe** [comment]
i checked before trying again but there was nothing about this error. otherwise, i has been the first thing i had uploaded. ;)
