### ISSUE TITLE
set_holiday_mode service: time conversion issue

### ISSUE THREAD

**Issue by smmoroz** [thomasgermain/vaillant-component#9]
Hi, 

I can't use set_holiday_mode service. I first tried this:
![service_1](https://user-images.githubusercontent.com/64163706/82154495-150e2480-9877-11ea-80dc-ed40277d8c92.gif)

I got this error:

> 2020-05-17 19:36:55 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.2820788336] unconverted data remains: T00:00:00.000Z
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 130, in handle_call_service
    connection.context(msg),
  File "/usr/src/homeassistant/homeassistant/core.py", line 1247, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1282, in _execute_service
    await handler.func(service_call)
  File "/config/custom_components/vaillant/service.py", line 109, in set_holiday_mode
    start = datetime.strptime(start_str, "%Y-%m-%d")
  File "/usr/local/lib/python3.7/_strptime.py", line 577, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/local/lib/python3.7/_strptime.py", line 362, in _strptime
    data_string[found.end():])
ValueError: unconverted data remains: T00:00:00.000Z

After that I removed `T00:00:00.000Z`. But the error still remains.

**Comment by thomasgermain** [comment]
Hi,

Thanks for the issue, I had a look and I also have the problem, I'm working on it.

Regards,

Thomas

**Comment by thomasgermain** [comment]
Hi,

honestly I can't understand from where it comes. During the test, dates sent to the service are in the right format, but on HA runtime, it comes as a datetime.  
Anyway, I did a fix, I also did some improvement and using some helpers coming from HA.

May I ask you to have a look at https://github.com/thomasgermain/vaillant-component/tree/v1_2_3 (release is not published yet) I tested it myself and it seems good.

Thanks,

Thomas

**Comment by lh14576** [comment]
I had the same error and the fix is working for me!

**Comment by thomasgermain** [comment]
Glad to here that :)

**Comment by smmoroz** [comment]
I finally checked it. It works for me!
