### ISSUE TITLE
Problem integrating Vaillant boiler and vr920 gateway (no VRC 700 thermostat). Release 1.8.1

### ISSUE THREAD

**Issue by jopacar1** [thomasgermain/vaillant-component#90]
My Vaillant setup is the following:

* VMW 306/5-7 (H-ES) water heater and central heating device
* VR920

NO other device such as VRC 700. (I use a Honeywell Lyric device as thermostat).

This setup is unsupported so I only expect best effort. Thanks in advance!!!

I have tried the release 1.8.1 of your integration in my rpi4 based HA but it fails and only creates 5 entities: Multimatic Errors, holiday, quick mode, system Online and system update. No devices, sensors etc are created. 

Attached:
* Relevant HA log and HA screenshots
* App Multimatic screenshots

I think the problem is that my setup only supports some of the API calls to Multimatic. I have tried (via pyMultimatic on a linux box) most of them and only some work. I can provide the result of all the API calls if needed.
[log_HA.txt](https://github.com/thomasgermain/vaillant-component/files/7040673/log_HA.txt)
![HA_Captura1](https://user-images.githubusercontent.com/82312235/130654824-186da543-ccfd-4bdc-a175-3adb3b194f72.JPG)
![HA_Captura2](https://user-images.githubusercontent.com/82312235/130654829-b71c3615-2a24-4f75-8f45-60c133e08976.JPG)
![Screenshot_2021-08-24-18-12-58-842_com vaillant android mobildialog3](https://user-images.githubusercontent.com/82312235/130654848-3bc5e240-7265-430f-9171-55ba82743bb7.jpg)
![Screenshot_2021-08-24-18-13-10-435_com vaillant android mobildialog3](https://user-images.githubusercontent.com/82312235/130654852-d47912a2-3a8d-4409-84e1-37f18e7ef675.jpg)
![Screenshot_2021-08-24-18-13-22-431_com vaillant android mobildialog3](https://user-images.githubusercontent.com/82312235/130654853-0da8be70-a091-4745-9570-18599d3b6221.jpg)
![Screenshot_2021-08-24-18-12-39-327_com vaillant android mobildialog3](https://user-images.githubusercontent.com/82312235/130654855-350e710d-5cb1-41bb-aaa2-1ad5142495f3.jpg)
![Screenshot_2021-08-24-18-12-49-223_com vaillant android mobildialog3](https://user-images.githubusercontent.com/82312235/130654857-dd4d5df3-ed43-4429-b970-9be1db847a63.jpg)

**Comment by thomasgermain** [comment]
Ok, so there are multiple points:
- `Missing key: 'capabilities'`: I will make it optional in next release, so you won't have the error anymore.
- This one means you have to run at least HA 2021.8
```
2021-08-24 14:13:58 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform multimatic.sensor: Platform not found (cannot import name 'STATE_CLASS_MEASUREMENT' from 'homeassistant.components.sensor' (/usr/src/homeassistant/homeassistant/components/sensor/__init__.py)).
``` 
- `Unexpected error fetching multimatic_holiday_mode data`: I don't know exactly yet what's the problem, I guess since you don't have a VRC700, you don't have the option. Can you call `https://smart.vaillant.com/mobile/api/v4/facilities/2118XXXXXXXXXXXXXXXXXXXXXXN0/systemcontrol/v1/configuration/holidaymode` directly and give me the result ?

**Comment by jopacar1** [comment]
> Ok, so there are multiple points:
> 
>     * `Missing key: 'capabilities'`: I will make it optional in next release, so you won't have the error anymore.
> 
>     * This one means you have to run at least HA 2021.8
> 
> 
> ```
> 2021-08-24 14:13:58 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform multimatic.sensor: Platform not found (cannot import name 'STATE_CLASS_MEASUREMENT' from 'homeassistant.components.sensor' (/usr/src/homeassistant/homeassistant/components/sensor/__init__.py)).
> ```
> 
>     * `Unexpected error fetching multimatic_holiday_mode data`: I don't know exactly yet what's the problem, I guess since you don't have a VRC700, you don't have the option. Can you call `https://smart.vaillant.com/mobile/api/v4/facilities/2118XXXXXXXXXXXXXXXXXXXXXXN0/systemcontrol/v1/configuration/holidaymode` directly and give me the result ?

I am still in HA 2021.4.3...  It works ok. but I will upgrade asap

The output of holidaymode:

await connector.request('get', urls.system_holiday_mode(serial='2118XXXXXXXXXXXN0'))
Traceback (most recent call last):
  File "mitestv1.py", line 144, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "mitestv1.py", line 103, in main
    response = await connector.request('get', urls.system_holiday_mode(serial='2118XXXXXN0'))
  File "/home/jr/.local/lib/python3.8/site-packages/pymultimatic/api/connector.py", line 164, in request
    raise ApiError(
pymultimatic.api.error.ApiError: Cannot get https://smart.vaillant.com/mobile/api/v4/facilities/2118XXXXXXXN0/systemcontrol/v1/configuration/holidaymode

As I told you, only a limited subset  of the URL's work. A summary:
gateway_type -> OK
facilities_list -> OK
rbr_underfloor_heating_status -> ERROR
rbr_installation_status -> ERROR
hvac -> OK
hvac_update -> ERROR
live_report .> ERROR
live_report_device->ERROR
emf_devices -> OK
emf_report_device -> OK
facilities_details -> OK
facilities_status -> OK
facilities_settings->OK
facilities_default_settings->OK
facilities_installer_info->OK
system-> ERROR
system_configuration->ERROR
system_status->ERROR
system_datetime->ERROR
system_parameters->OK
system_quickmode, system_holiday_mode, dhw, dhws, circulation... -> ERROR

**Comment by thomasgermain** [comment]
could you also print the response (json) and the http status ? `ApiError#status` and `ApiError#response`

**Comment by jopacar1** [comment]
URL:  https://smart.vaillant.com/mobile/api/v4/facilities/2118XXXXXXXXXXXXXXXXN0/systemcontrol/v1/configuration/holidaymode

Response:
{"errorCode":"FACILITY_NOT_COMPATIBLE"}

Payload:
None

Status:
409

**Comment by thomasgermain** [comment]
Release https://github.com/thomasgermain/vaillant-component/releases/tag/1.9.0 is out ! It should allow you to use it without error. Since it's quite hard to test exactly what you can or cannot access, you may still have issues.

**Comment by jopacar1** [comment]
Thanks for tour help!!!

 I am away at the moment but I Will try It when I come back home (in a few daysi)  and report the results.

 Is It required to upgrade HA to the latest version for the integration to run properly?
