### ISSUE TITLE
Energy integration

### ISSUE THREAD

**Issue by pfriedrich84** [thomasgermain/vaillant-component#91]
in 2021.9 they changed the required state_class to "total_increasing".

Example of current sensor not working:
state_class: measurement
last_reset: 1970-01-01T00:00:00+00:00
unit_of_measurement: Wh
device_class: energy

Should be now:
state_class: total_increasing
unit_of_measurement: Wh
device_class: energy

If there is a beta, happy to test! Tried to find it in the component to change manually but not sure where the state class is decided.

Cheers,
Paul

https://developers.home-assistant.io/blog/2021/08/16/state_class_total/

EDIT: found it sensor.py at the end STATE_CLASS_TOTAL_INCREASING ;-)

**Comment by thomasgermain** [comment]
Thanks for the PR !
