### ISSUE TITLE
Energy Usage in kWh also is not aligned with what the Multimatic App displays

### ISSUE THREAD

**Issue by VaillantHassIo** [thomasgermain/vaillant-component#97]
As per conversation, it seems the Sensor for Engery Consumption are somehow incorrctly configured and i am looking for help to query the APi directly.

![image](https://user-images.githubusercontent.com/87522613/133439407-da7379b6-be38-468c-94eb-4a89d96ada24.png)

Equipment:

flexoCompact exclusive 
Mulitmatic VR921
recoVair

**Comment by thomasgermain** [comment]
Thanks, are you using sensoAPP ?

**Comment by VaillantHassIo** [comment]
Multimatic App

**Comment by VaillantHassIo** [comment]
I'll figured that i have  sheduled WLAN disconnect from 22.00-06.00 i am not sure how this will affect the tracking of the energie consumption. Do you have an API Command Set for testing?

**Comment by thomasgermain** [comment]
It should not really affect the entity itself, but you will have some kind of "stale history" and you may have some errors between the time frame. 

Regarding the raw data, you can check here https://github.com/thomasgermain/pymultiMATIC/tree/master/script, there re script to get raw data:
- for windows
there is a `print_response.ps1` script, you can run the script with *powershell* like this:
`./print_response.ps1 user passw https://smart.vaillant.com/mobile/api/v4/facilities/{serial_id}/emf/v1/devices`

- for linux:
`sh print_response.sh user passw https://smart.vaillant.com/mobile/api/v4/facilities/{serial_id}/emf/v1/devices`

You can find your serial_id on your VRXX box. Don't forget some personal/sensitive data if any (like serial id, etc.).

By the way, could you also show me the entity (and the value) from the integration page (not from the energy dashboard), the value there should be in *Wh*. I have the feeling HA (in the energy dashboard) is rounding a bit the value, so you don't see small difference in consumption.

**Comment by VaillantHassIo** [comment]
This is from the Integration Page. Its in Wh but it seems the values are incorrect or at least 10x bigger on what it should be.

![image](https://user-images.githubusercontent.com/87522613/133800034-6e086337-03f8-45fe-97ea-426bfab91c6f.png)

PS: if i want to use the WebBrowser directly for API Query how to add user und pass?

**Comment by VaillantHassIo** [comment]
So while it seems the monthly values matches in HA, Mulitmatic App, HeatPump the weekly and daily values doesnt add up.

**Comment by thomasgermain** [comment]
Ok so, as I can see, entities are correct regarding the API values. 

Actually, the integration is just getting the total values, HA energy dashboard is responsible to compute daily/weekly and monthly value

**Comment by VaillantHassIo** [comment]
Ok. My bad. The values on the heat-pump are all environmental not actual consumtption. So the values add up and i close the ticket hereby
